#  **PyTorch Practice Assignment**
**Name**: Aadharsh Ramachandran

**Roll Number**: 231IT001

## **Instructions:**

- Copy this Notebook to your own Drive! You cannot directly modify it.
- Please show the output of the cells, in case of some operation. You can specify your own **non-trivial** test-case. Also, try and make your snippets into functions to organize your logic.
- You can use any number of cells for a question, you are not restricted to just 1 cell!
- **No using ChatGPT for this assignment**: we highly recommend using the [Pytorch Docs](https://pytorch.org/docs/stable/index.html) as your start reference, as well as the vast internet however. You can also contact any of your mentors for some hints/help!
- You can work on this assignment in Google Colab or on Your Local Machine!

### **Build Up Your Understanding**

1. Write a PyTorch snippet to test whether none of the elements of a given tensor are zero.

In [1]:
import torch
import numpy as np

In [2]:
tensor=torch.rand((2,3))
result=torch.all(tensor!=0)
if result==True:
    print("Zero is not contained in the tensor")
else:
    print("Zero is contained in the tensor")

Zero is not contained in the tensor


2. Write a PyTorch snippet to test element-wise for NaN of a given tensor.

In [3]:
tensor=torch.rand((2,3))
result=torch.isnan(tensor)
result

tensor([[False, False, False],
        [False, False, False]])

3. Write a PyTorch snippet to test whether two tensors are element-wise equal within a tolerance.

In [4]:
tensor1=torch.rand((2,3))
tensor2=torch.rand((2,3))
result=torch.eq(tensor1,tensor2)
result

tensor([[False, False, False],
        [False, False, False]])

4. Write a PyTorch snippet to create a tensor of 10 zeros, 10 ones, and 10 fives stacked on top of each other (try & accomplish everything using nested function calls).

In [5]:
tensor=torch.rand(3,10)
def fill0(i):
    tensor[i]=torch.zeros((10,))
    fill1(i+1)
def fill1(i):
    tensor[i]=torch.ones((10,))
    fill5(i+1)
def fill5(i):
    tensor[i]=torch.tensor(np.full((10,),5))
fill0(0);
tensor

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])

5. Write a PyTorch snippet to generate a random number between 0 and 1.

In [6]:
tensor=torch.rand((1,1))
tensor

tensor([[0.8150]])

6. Write a PyTorch snippet to generate a tensor of 15 random numbers from a standard normal distribution.

In [7]:
tensor=torch.normal(mean=torch.arange(1.,15.))
tensor

tensor([ 0.1002,  3.1178,  2.3765,  2.7623,  4.9563,  5.8527,  7.6393,  5.7587,
         9.3731, 11.4450, 11.4706, 14.6602, 13.2768, 13.2936])

7. Write a Pytorch snippet to create a tensor of length 10 with values evenly distributed between 5 and 50.

In [8]:
tensor=torch.linspace(5,50,10);
tensor

tensor([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

8. Write a Pyorch program to create a tensor with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15.

In [9]:
tensor=torch.rand((10))*20;
for i in range(0,tensor.shape[0]):
    if (tensor[i]>=9)&(tensor[i]<=15):
        tensor[i]=-tensor[i]
tensor

tensor([  2.4276,  -9.2982,   3.2391,   3.1258, -13.3221,   1.1548,  18.7156,
         -9.5255,   4.8026,  19.1622])

9. Write a PyTorch snippet to create a 3x4 2-tensor filled with values from 10 to 21. Same but 12 to 24.

In [10]:
tensor1=torch.rand((3,4))*11+10
tensor2=torch.rand((3,4))*12+12
print(f"Tensor1",tensor1)
print(f"Tensor2",tensor2)

Tensor1 tensor([[11.7481, 13.4695, 11.8541, 10.4078],
        [10.2650, 12.0284, 17.5996, 11.5418],
        [10.1505, 16.1631, 20.4685, 16.5298]])
Tensor2 tensor([[23.8408, 23.2251, 23.1671, 20.9014],
        [16.6447, 23.1954, 17.6324, 16.5106],
        [12.9496, 21.8333, 19.8619, 19.7617]])


10. Write a PyTorch snippet to create a 10x10 2-tensor, in which the elements on the borders will be equal to 1, and inside 0.

In [11]:
tensor1=torch.ones((10,10))
tensor1[1:-1,1:-1]=0
print(tensor1)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])


11. Write a PyTorch snippet to create a 5x5 zero 2-tensor with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [12]:
result=torch.diag(torch.tensor([1,2,3,4,5]))
result

tensor([[1, 0, 0, 0, 0],
        [0, 2, 0, 0, 0],
        [0, 0, 3, 0, 0],
        [0, 0, 0, 4, 0],
        [0, 0, 0, 0, 5]])

12. Write a PyTorch snippet to save a given tensor as a binary to a given path.

In [13]:
tensor=torch.tensor([10,11,12])
torch.save(tensor,'tensor.path')
print("Saved")

Saved


13. Write a NumPy program to create a two-dimensional array of a specified format.

In [14]:
tensor=torch.rand((2,3))
tensor

tensor([[0.9180, 0.1609, 0.2264],
        [0.5613, 0.9355, 0.7558]])

14. Write a PyTorch snippet to create a 2-tensor with shape (8,5) of random numbers. Select these random numbers (to create the tensor) from a normal distribution (200,7) (mean, variance).

In [15]:
import math
tensor=torch.normal(mean=200,std=math.sqrt(7),size=(8,5))
tensor

tensor([[197.7397, 198.6229, 201.7288, 201.3265, 202.4063],
        [200.9527, 205.6269, 199.0549, 203.5176, 198.9315],
        [202.8248, 198.9272, 205.7600, 207.6863, 205.3974],
        [202.8148, 199.7183, 200.9695, 195.1682, 204.4532],
        [197.7201, 202.5931, 203.6357, 205.7718, 198.3048],
        [195.0957, 195.2677, 200.0136, 201.4834, 202.5282],
        [196.5010, 201.7656, 197.5233, 197.1680, 200.2508],
        [197.9319, 196.1728, 205.5951, 198.3528, 199.5573]])

15. Write a PyTorch snippet to generate a uniform, non-uniform random sample from a given vector with and without replacement (do all 4 combinations possible).

In [16]:
print(f"Uniform with replacement",np.random.choice(4,3))
print(f"Uniform without replacement",np.random.choice(4,3,replace=False))
print(f"Non uniform with replacement",np.random.choice(4,3,p=[0.1,0.3,0.4,0.2]))
print(f"Non uniform without replacement",np.random.choice(4,3,p=[0.1,0.3,0.4,0.2],replace=False))

Uniform with replacement [1 1 3]
Uniform without replacement [2 0 3]
Non uniform with replacement [2 2 2]
Non uniform without replacement [2 1 3]


16. Write a Pyorch snippet to create an nxn(input to function) tensor with random values. Create an array from the said array swapping first and last rows.

In [17]:
tensor=torch.rand((3,3))
print(f"Original tensor",tensor)
n=tensor.shape[0]
tensor[[0,n-1]]=tensor[[n-1,0]]
print(f"Swapped tensor",tensor)

Original tensor tensor([[0.1756, 0.3437, 0.2383],
        [0.0846, 0.8093, 0.2208],
        [0.4961, 0.3817, 0.4348]])
Swapped tensor tensor([[0.4961, 0.3817, 0.4348],
        [0.0846, 0.8093, 0.2208],
        [0.1756, 0.3437, 0.2383]])


17. Write a PyTorch snippet to sort a given tensor (1D or 2D) in ascending order.

In [18]:
tensor=torch.rand((1,10))
print(f"Original tensor",tensor)
result=torch.sort(tensor)
print(f"Sorted tensor",result)

Original tensor tensor([[0.6834, 0.5105, 0.9839, 0.9272, 0.8972, 0.6324, 0.7094, 0.5034, 0.3048,
         0.8207]])
Sorted tensor torch.return_types.sort(
values=tensor([[0.3048, 0.5034, 0.5105, 0.6324, 0.6834, 0.7094, 0.8207, 0.8972, 0.9272,
         0.9839]]),
indices=tensor([[8, 7, 1, 5, 0, 6, 9, 4, 3, 2]]))


18. Write a PyTorch snippet to create a tensor of equal shape and data type for a given tensor (any dimensional)

In [19]:
tensor=torch.rand((5,5),dtype=torch.float32)
tensor

tensor([[0.9950, 0.7298, 0.1807, 0.2365, 0.0028],
        [0.1741, 0.5465, 0.5272, 0.1889, 0.5546],
        [0.8035, 0.2548, 0.4204, 0.4978, 0.5214],
        [0.2509, 0.1032, 0.2146, 0.5294, 0.9261],
        [0.2946, 0.9861, 0.3005, 0.3088, 0.1034]])

19. Write a PyTorch snippet to create an 8x8 matrix and fill it with a checkerboard pattern.
Checkerboard pattern:
```py
[[0 1 0 1 0 1 0 1]
..........
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]]
```

In [20]:
tensor=torch.zeros((8,8))
tensor[1::2,::2]=1
tensor[::2,1::2]=1
tensor

tensor([[0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0.],
        [0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0.],
        [0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0.],
        [0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0.]])

20. Write a Pytorch snippet to convert Centigrade to Fahrenheit and vice versa (controlled by a parameter). Ensure you operation is vectorized i.e **no explicit looping**

Sample Array: `[0, 12, 45.21, 34, 99.91]`

In [21]:
tensor=torch.tensor([0,12,45.21,34,99.91])
tensor1=(9/5)*tensor+32
print(f"Centigrade to Fahrenheit",tensor1)
tensor2=(5/9)*(tensor1-32)
print(f"Fahrenheit to Centigrade",tensor2)

Centigrade to Fahrenheit tensor([ 32.0000,  53.6000, 113.3780,  93.2000, 211.8380])
Fahrenheit to Centigrade tensor([ 0.0000, 12.0000, 45.2100, 34.0000, 99.9100])


21. Write a PyTorch snippet to get the values of the elements that are bigger than a given *number* in a given tensor.

Original tensor:
```
[[ 0 10 20]
[20 30 40]]
```
Number: 10

Values bigger than 10 = `[20 20 30 40]`

In [22]:
tensor=torch.rand((3,3))*30
print(f"Original tensor",tensor)
print(f"Conditioned tensor",tensor[tensor>20])

Original tensor tensor([[ 1.4676, 16.8040, 28.6306],
        [22.3167, 16.3733, 18.7931],
        [ 4.0581, 21.7332, 13.6791]])
Conditioned tensor tensor([28.6306, 22.3167, 21.7332])


## 22. Write a PyTorch snippet to create another shape from an array without changing its data. After carrying out the operation, change the data in one place and see if the other tensor changes

Reshape 3x2:
```
[[1 2]
[3 4]
[5 6]]
```
Reshape 2x3:
```
[[1 2 3]
[4 5 6]]
```

In [23]:
tensor=torch.rand((4,3))
print(f"Original tensor",tensor)
result=torch.reshape(tensor,(6,2))
print(f"Reshaped tensor",result)

Original tensor tensor([[0.5474, 0.3017, 0.0508],
        [0.2930, 0.2125, 0.5948],
        [0.0292, 0.4058, 0.5866],
        [0.5952, 0.3243, 0.9005]])
Reshaped tensor tensor([[0.5474, 0.3017],
        [0.0508, 0.2930],
        [0.2125, 0.5948],
        [0.0292, 0.4058],
        [0.5866, 0.5952],
        [0.3243, 0.9005]])


23. Write a PyTorch snipppet to change an tensor's data type.
```
[[ 2 4 6]
[ 6 8 10]]
```
Data type of the array x is: `int32`

New Type: `float64`
```
[[ 2. 4. 6.]
[ 6. 8. 10.]]
```

In [24]:
tensor=torch.tensor([[2,4,6],[6,8,10]],dtype=torch.int32)
print(f"Int tensor",tensor)
tensor1=tensor.to(torch.float64)
print(f"Float tensor",tensor1)

Int tensor tensor([[ 2,  4,  6],
        [ 6,  8, 10]], dtype=torch.int32)
Float tensor tensor([[ 2.,  4.,  6.],
        [ 6.,  8., 10.]], dtype=torch.float64)


24. Write a PyTorch snippet to insert a new axis within a 2-tensor, based on a **parameter**.

Ex: If 2-tensor has shape (3, 4).

Then, new shape can be (1, 3, 4), (3, 1, 4), or (3, 4, 1) depending on....

In [25]:
tensor=torch.rand((4,3))
print(f"Original tensor",tensor)
result=torch.reshape(tensor,(4,3,1))
print(f"Reshaped tensor",result)

Original tensor tensor([[0.5437, 0.4351, 0.1831],
        [0.0959, 0.9782, 0.3163],
        [0.4486, 0.1390, 0.6358],
        [0.3124, 0.5950, 0.2792]])
Reshaped tensor tensor([[[0.5437],
         [0.4351],
         [0.1831]],

        [[0.0959],
         [0.9782],
         [0.3163]],

        [[0.4486],
         [0.1390],
         [0.6358]],

        [[0.3124],
         [0.5950],
         [0.2792]]])


25. Write a PyTorch snippet to stack tensors based on a parameter, **axis**.
First discover what this means with 2-tensors, then extend it to 3-tensors. Print your findings.

Sample Output:

Original tensors:

Tensor-1
```
[[0 1 2]
[3 4 5]
[6 7 8]]
```
Tensor-2
```
[[ 0 3 6]
[ 9 12 15]
[18 21 24]]
```
Stack tensors such that axis=1:
```
[[ 0 1 2 0 3 6]
[ 3 4 5 9 12 15]
[ 6 7 8 18 21 24]]
```

In [26]:
tensor1=torch.rand((3,3))
tensor2=torch.rand((3,3))
print(f"Original tensor1",tensor1)
print(f"Original tensor2",tensor2)
result=torch.cat((tensor1,tensor2),1)
result

Original tensor1 tensor([[0.9345, 0.0449, 0.7231],
        [0.1163, 0.2252, 0.4381],
        [0.7978, 0.1683, 0.6996]])
Original tensor2 tensor([[0.8452, 0.9941, 0.4172],
        [0.9144, 0.0667, 0.2165],
        [0.8341, 0.6382, 0.1734]])


tensor([[0.9345, 0.0449, 0.7231, 0.8452, 0.9941, 0.4172],
        [0.1163, 0.2252, 0.4381, 0.9144, 0.0667, 0.2165],
        [0.7978, 0.1683, 0.6996, 0.8341, 0.6382, 0.1734]])

26. Write a PyTorch snippet to extract the **m**th to **n**th elements of the **m**th to **n**th rows from the **m**th to nth elemnts of given 3-tensor, of shape `(p, q, r)` where m, n < p, q, r.

Take a 3-tensor of (say) size `(5,6,7)` and `(m, n)` = `(4, 5)` as a test case!

In [27]:
tensor=torch.rand((5,6,7))
tensor[:,:,4:5]

tensor([[[0.6739],
         [0.5661],
         [0.4653],
         [0.1933],
         [0.8246],
         [0.8167]],

        [[0.0469],
         [0.6090],
         [0.4335],
         [0.2302],
         [0.6834],
         [0.1546]],

        [[0.2130],
         [0.5999],
         [0.8922],
         [0.6203],
         [0.8771],
         [0.8374]],

        [[0.7116],
         [0.5198],
         [0.7933],
         [0.6900],
         [0.3114],
         [0.5136]],

        [[0.9127],
         [0.0044],
         [0.9070],
         [0.1434],
         [0.8086],
         [0.7955]]])

### **Test your Understanding**

1. Given a 3D tensor of shape `(a, b, c)`*italicised text*, permute its axes to obtain tensors of all other shape combinations (i.e 5).

In [28]:
tensor=torch.rand(2,3,4)
permutations=[(0,1,2),(1,2,0),(0,2,1),(1,0,2),(2,1,0),(2,0,1)]
for i in range(0,6):
    result=tensor.permute(permutations[i])
    print(result)

tensor([[[0.4364, 0.7213, 0.3794, 0.8288],
         [0.8781, 0.6378, 0.5296, 0.7354],
         [0.7381, 0.2510, 0.3954, 0.9031]],

        [[0.8191, 0.3140, 0.4558, 0.3704],
         [0.9688, 0.6931, 0.6498, 0.9006],
         [0.2623, 0.6448, 0.1423, 0.2781]]])
tensor([[[0.4364, 0.8191],
         [0.7213, 0.3140],
         [0.3794, 0.4558],
         [0.8288, 0.3704]],

        [[0.8781, 0.9688],
         [0.6378, 0.6931],
         [0.5296, 0.6498],
         [0.7354, 0.9006]],

        [[0.7381, 0.2623],
         [0.2510, 0.6448],
         [0.3954, 0.1423],
         [0.9031, 0.2781]]])
tensor([[[0.4364, 0.8781, 0.7381],
         [0.7213, 0.6378, 0.2510],
         [0.3794, 0.5296, 0.3954],
         [0.8288, 0.7354, 0.9031]],

        [[0.8191, 0.9688, 0.2623],
         [0.3140, 0.6931, 0.6448],
         [0.4558, 0.6498, 0.1423],
         [0.3704, 0.9006, 0.2781]]])
tensor([[[0.4364, 0.7213, 0.3794, 0.8288],
         [0.8191, 0.3140, 0.4558, 0.3704]],

        [[0.8781, 0.6378, 0.5296, 0.

2. Given a 4D tensor of shape `(2, 3, 4, 5)`, transpose it to obtain a tensor of shape `(2, 4, 5, 3)`. Also explore what is_contiguous() means...

In [29]:
tensor=torch.rand((2,3,4,5))
print(f"Original tensor",tensor)
result=tensor.permute((0,2,3,1))
print(f"Reshaped tensor",result)

Original tensor tensor([[[[0.0684, 0.7163, 0.5954, 0.5382, 0.8947],
          [0.8224, 0.3587, 0.5123, 0.6071, 0.8807],
          [0.7023, 0.9853, 0.9516, 0.1201, 0.3861],
          [0.4426, 0.5325, 0.2675, 0.2077, 0.2003]],

         [[0.0586, 0.1422, 0.0501, 0.5539, 0.1409],
          [0.2753, 0.2529, 0.6945, 0.4246, 0.4559],
          [0.6290, 0.2343, 0.7676, 0.6397, 0.0987],
          [0.2862, 0.8262, 0.8714, 0.6305, 0.0834]],

         [[0.5571, 0.8655, 0.0118, 0.7217, 0.5668],
          [0.7498, 0.4178, 0.8724, 0.4108, 0.2054],
          [0.1057, 0.7035, 0.4391, 0.9224, 0.3754],
          [0.1502, 0.2451, 0.0889, 0.7482, 0.4944]]],


        [[[0.3888, 0.9199, 0.2019, 0.9115, 0.0267],
          [0.9753, 0.2989, 0.9291, 0.3989, 0.5720],
          [0.3688, 0.3224, 0.4580, 0.2970, 0.6146],
          [0.7044, 0.6728, 0.5799, 0.3528, 0.2321]],

         [[0.5972, 0.6812, 0.6957, 0.7294, 0.4695],
          [0.4917, 0.4447, 0.2365, 0.0387, 0.2657],
          [0.3431, 0.2460, 0.0585, 0.2

3. Given two tensors, one of shape (n, 1) and another of shape (m, ), perform an element-wise addition **manually**. Then, test out what direct addition does and compare your results!

In [30]:
tensor1=torch.rand(2,1)
tensor2=torch.rand(3,)
print(f"Original tensor1",tensor1)
print(f"Original tensor2",tensor2)
result1=tensor1+tensor2
print(f"Result 1",result1)
result=torch.add(tensor1,tensor2)
print(f"Result 2",result)

Original tensor1 tensor([[0.8079],
        [0.2202]])
Original tensor2 tensor([0.1518, 0.1576, 0.5475])
Result 1 tensor([[0.9596, 0.9655, 1.3554],
        [0.3720, 0.3778, 0.7678]])
Result 2 tensor([[0.9596, 0.9655, 1.3554],
        [0.3720, 0.3778, 0.7678]])


4. Given a 3D tensor of shape `(4, 4, 4)`, extract a sub-tensor of shape `(2, 2, 2)` starting from the element at index `(1, 1, 1)`**bold text**.

In [31]:
tensor=torch.rand((4,4,4))
tensor[1:3,1:3,1:3]

tensor([[[0.0540, 0.8469],
         [0.2154, 0.2730]],

        [[0.6790, 0.9822],
         [0.8592, 0.0281]]])

5. Given a 2-tensor of arbitrary shape, rotate it 90 degrees anticlockwise.



In [32]:
tensor=torch.rand((2,2))
print(f"Original tensor",tensor)
print(f"Rotated tensor",torch.rot90(tensor,1))

Original tensor tensor([[0.5332, 0.5299],
        [0.0330, 0.6748]])
Rotated tensor tensor([[0.5299, 0.6748],
        [0.5332, 0.0330]])


### **EVEN I HAD TO THINK...**

1. Implement a custom operation that computes the **element-wise** **sine** of a tensor *and* its **gradient** using torch.autograd.Function.
- You need to implement both the forward() and backward() methods.
- For an example, look no further than the [PyTorch docs](https://pytorch.org/docs/stable/autograd.html#function)!
- Test it out on a matrix of arbitrary size!

2. One of the most important aspects of improving model performance ins normalization. Implement a custom NN normalization layer that performs either a **batch** or **layer** normalization (based on a **dim** parameter)and integrate it into a simple feedforward neural network.
- Note that you dont need to implement any backward() here, for simplicity.
- Consider your input tensor to the neural network as of shape (m, n) where m is num of examples, n is num of features.
- Which value of **dim** leads to batch and layer normalization?

In [33]:
import torch
import torch.nn as nn

class CustomNormalization(nn.Module):
    def __init__(self, dim):
        super(CustomNormalization, self).__init__()
        self.dim = dim
        self.eps = 1e-5
        self.gamma = nn.Parameter(torch.ones(dim))
        self.beta = nn.Parameter(torch.zeros(dim))

    def forward(self, x):
        if self.dim == 0:
            # Batch normalization
            mean = x.mean(dim=0, keepdim=True)
            std = x.std(dim=0, keepdim=True)
        elif self.dim == 1:
            # Layer normalization
            mean = x.mean(dim=1, keepdim=True)
            std = x.std(dim=1, keepdim=True)
        else:
            raise ValueError("dim must be 0 (batch normalization) or 1 (layer normalization)")

        x_normalized = (x - mean) / (std + self.eps)
        return self.gamma * x_normalized + self.beta

class SimpleFeedForwardNN(nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim, normalization_dim):
        super(SimpleFeedForwardNN, self).__init__()
        self.fc1 = nn.Linear(input_dim, hidden_dim)
        self.norm1 = CustomNormalization(normalization_dim)
        self.fc2 = nn.Linear(hidden_dim, output_dim)

    def forward(self, x):
        x = self.fc1(x)
        x = self.norm1(x)
        x = torch.relu(x)
        x = self.fc2(x)
        return x


hidden_dim = 5
output_dim = 1
normalization_dim = 1
input_dim=10
model = SimpleFeedForwardNN(input_dim, hidden_dim, output_dim, normalization_dim)


input_tensor = torch.randn(8, input_dim)  

output = model(input_tensor)
print(output)

tensor([[-0.3068],
        [-0.8037],
        [-0.7468],
        [-0.5429],
        [-0.6772],
        [-0.6960],
        [-0.5377],
        [-0.5637]], grad_fn=<AddmmBackward0>)


3. Given a 4D tensor of shape (2, 3, 4, 5), create a mask that sets all elements in positions where the sum of indices is even to zero.

In [34]:
import torch
shape = (2, 3, 4, 5)
mask = torch.ones(shape)
for i in range(shape[0]):
    for j in range(shape[1]):
        for k in range(shape[2]):
            for l in range(shape[3]):
                # Check if the sum of indices is even
                if (i + j + k + l) % 2 == 0:
                    # Set the corresponding position in the mask to zero
                    mask[i, j, k, l] = 0

print(mask)


tensor([[[[0., 1., 0., 1., 0.],
          [1., 0., 1., 0., 1.],
          [0., 1., 0., 1., 0.],
          [1., 0., 1., 0., 1.]],

         [[1., 0., 1., 0., 1.],
          [0., 1., 0., 1., 0.],
          [1., 0., 1., 0., 1.],
          [0., 1., 0., 1., 0.]],

         [[0., 1., 0., 1., 0.],
          [1., 0., 1., 0., 1.],
          [0., 1., 0., 1., 0.],
          [1., 0., 1., 0., 1.]]],


        [[[1., 0., 1., 0., 1.],
          [0., 1., 0., 1., 0.],
          [1., 0., 1., 0., 1.],
          [0., 1., 0., 1., 0.]],

         [[0., 1., 0., 1., 0.],
          [1., 0., 1., 0., 1.],
          [0., 1., 0., 1., 0.],
          [1., 0., 1., 0., 1.]],

         [[1., 0., 1., 0., 1.],
          [0., 1., 0., 1., 0.],
          [1., 0., 1., 0., 1.],
          [0., 1., 0., 1., 0.]]]])


3. Given two tensors, one of shape `(3, 1, 4)` and another of shape `(1, 5, 1)`, compute their element-wise multiplication using broadcasting and then sum over specific axes to obtain a tensor of shape `(3, 5)`.

In [35]:
tensor=torch.rand(3,1,4)
tensor1=torch.rand(1,5,1)
print(f"Original tensor1",tensor)
print(f"Original tensor2",tensor1)
result=tensor1*tensor
result.sum(dim=2)

Original tensor1 tensor([[[0.0291, 0.6026, 0.4579, 0.2502]],

        [[0.5808, 0.4142, 0.5096, 0.0223]],

        [[0.1731, 0.7559, 0.5900, 0.3614]]])
Original tensor2 tensor([[[0.8489],
         [0.8232],
         [0.3205],
         [0.5426],
         [0.6911]]])


tensor([[1.1375, 1.1029, 0.4294, 0.7271, 0.9259],
        [1.2962, 1.2569, 0.4893, 0.8285, 1.0552],
        [1.5963, 1.5479, 0.6026, 1.0204, 1.2995]])