<a href="https://colab.research.google.com/github/nagamukesh/NLP-SMP/blob/Aaryan_reddy/Copy_of_PyTorch_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  **PyTorch Practice Assignment**
**Name**: Aaryan Reddy

**Roll Number**: 231AI001

## **Instructions:**

- Copy this Notebook to your own Drive! You cannot directly modify it.
- Please show the output of the cells, in case of some operation. You can specify your own **non-trivial** test-case. Also, try and make your snippets into functions to organize your logic.
- You can use any number of cells for a question, you are not restricted to just 1 cell!
- **No using ChatGPT for this assignment**: we highly recommend using the [Pytorch Docs](https://pytorch.org/docs/stable/index.html) as your start reference, as well as the vast internet however. You can also contact any of your mentors for some hints/help!
- You can work on this assignment in Google Colab or on Your Local Machine!

### **Build Up Your Understanding**

1. Write a PyTorch snippet to test whether none of the elements of a given tensor are zero.

In [ ]:
import torch
tensor  = torch.tensor([0,0])
check=torch.all(tensor != 0)
print(check)
tensor  = torch.tensor([1,2])
check=torch.all(tensor != 0)
print(check)

tensor(False)
tensor(True)


2. Write a PyTorch snippet to test element-wise for NaN of a given tensor.

In [ ]:
import torch
tensor = torch.tensor([1.0, float('nan'), 3.0, 4.0, float('nan')])
nan_elements = torch.isnan(tensor)
print(nan_elements)

tensor([False,  True, False, False,  True])


3. Write a PyTorch snippet to test whether two tensors are element-wise equal within a tolerance.

In [ ]:
import torch

def compare_tensors_with_tolerance(tensor1, tensor2, tolerance):

  if tensor1.shape != tensor2.shape:
    return False

  diff = torch.abs(tensor1 - tensor2)

  return torch.all(diff < tolerance)

tensor1 = torch.tensor([1.0, 2.0, 3.0])
tensor2 = torch.tensor([1.001, 2.002, 2.999])
tolerance = 0.01

result = compare_tensors_with_tolerance(tensor1, tensor2, tolerance)

print(result)

tensor(True)


4. Write a PyTorch snippet to create a tensor of 10 zeros, 10 ones, and 10 fives stacked on top of each other (try & accomplish everything using nested function calls).

In [ ]:
zeros = torch.zeros(10)
ones = torch.ones(10)
fives = torch.ones(10) * 5
stacked_tensor = torch.cat((zeros, ones, fives), dim=0)
print(stacked_tensor)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])


5. Write a PyTorch snippet to generate a random number between 0 and 1.

In [ ]:
import torch

rng = torch.Generator().manual_seed(42)

random_number = torch.rand(1, generator=rng).item()

print(random_number)

0.8822692632675171


6. Write a PyTorch snippet to generate a tensor of 15 random numbers from a standard normal distribution.

In [ ]:
import torch

tensor = torch.randn(15)

print(tensor)

tensor([ 0.2201,  0.2892,  0.5624, -0.5250,  0.5047, -0.6959,  0.7108,  1.2519,
         0.4320, -1.7442,  0.9805,  1.0260, -0.3395,  0.1141, -1.1218])


7. Write a Pytorch snippet to create a tensor of length 10 with values evenly distributed between 5 and 50.

In [ ]:
import torch

tensor = torch.linspace(5, 50, 10)

print(tensor)

tensor([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])


8. Write a Pyorch program to create a tensor with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15.

In [ ]:
import torch

tensor = torch.arange(0, 21)

tensor[9:16] = -tensor[9:16]

print(tensor)

tensor([  0,   1,   2,   3,   4,   5,   6,   7,   8,  -9, -10, -11, -12, -13,
        -14, -15,  16,  17,  18,  19,  20])


9. Write a PyTorch snippet to create a 3x4 2-tensor filled with values from 10 to 21. Same but 12 to 24.

In [ ]:
tensor1 = torch.arange(10, 22, dtype=torch.float32).reshape(3, 4)
print(tensor1)
tensor2 = torch.arange(12, 25, dtype=torch.float32).reshape(3, 4)
print(tensor2)

tensor([[10., 11., 12., 13.],
        [14., 15., 16., 17.],
        [18., 19., 20., 21.]])


RuntimeError: shape '[3, 4]' is invalid for input of size 13

10. Write a PyTorch snippet to create a 10x10 2-tensor, in which the elements on the borders will be equal to 1, and inside 0.

In [ ]:
import torch

def create_bordered_tensor(size):

  tensor = torch.zeros(size)
  tensor[:, 0] = 1
  tensor[:, -1] = 1
  tensor[0, :] = 1
  tensor[-1, :] = 1
  return tensor

bordered_tensor = create_bordered_tensor((10, 10))
print(bordered_tensor)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])


11. Write a PyTorch snippet to create a 5x5 zero 2-tensor with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [ ]:
import torch

tensor = torch.zeros(5, 5)

for i in range(5):
  tensor[i, i] = i + 1

print(tensor)

12. Write a PyTorch snippet to save a given tensor as a binary to a given path.

In [ ]:
import torch

tensor = torch.randn(10)

path = "/content/tensor.pt"

torch.save(tensor, path)

tensor([-0.9709, -0.4601,  0.8910,  0.5510,  0.9310,  0.6391,  0.9554, -1.1747,
        -3.0113, -0.2222])


13. Write a NumPy program to create a two-dimensional array of a specified format.

In [ ]:
import numpy as np

array = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)

print(array)

[[1 2 3]
 [4 5 6]]


14. Write a PyTorch snippet to create a 2-tensor with shape (8,5) of random numbers. Select these random numbers (to create the tensor) from a normal distribution (200,7) (mean, variance).

In [ ]:
import torch

tensor = torch.randn(8, 5) * 7 + 200

print(tensor)

tensor([[192.4615, 195.0171, 204.1281, 205.8712, 202.8202],
        [203.2595, 192.8205, 201.6251, 192.0166, 199.0007],
        [198.4003, 206.9262, 199.4760, 208.6663, 202.7212],
        [201.5409, 182.5845, 205.0250, 190.1066, 192.1980],
        [206.0843, 199.8443, 195.2063, 195.4208, 198.9473],
        [201.7142, 192.8449, 205.7640, 194.5427, 206.4491],
        [201.5978, 196.2404, 197.3504, 201.2698, 209.7018],
        [194.2733, 191.2282, 198.8698, 190.2480, 188.6052]])


15. Write a PyTorch snippet to generate a uniform, non-uniform random sample from a given vector with and without replacement (do all 4 combinations possible).

In [ ]:
import torch

tensor = torch.rand(10)
uniform_sample_with_replacement = torch.randperm(len(tensor))[0:5]
print("Uniform random sample with replacement:", tensor[uniform_sample_with_replacement])

uniform_sample_without_replacement = torch.randperm(len(tensor))[0:5]
print("Uniform random sample without replacement:", tensor[uniform_sample_without_replacement])

non_uniform_sample_with_replacement = torch.multinomial(torch.rand(10), 5)
print("Non-uniform random sample with replacement:", tensor[non_uniform_sample_with_replacement])

non_uniform_sample_without_replacement = torch.multinomial(torch.rand(10), 5, replacement=False)
print("Non-uniform random sample without replacement:", tensor[non_uniform_sample_without_replacement])

Uniform random sample with replacement: tensor([0.2456, 0.1903, 0.3370, 0.5627, 0.1456])
Uniform random sample without replacement: tensor([0.1456, 0.5627, 0.0419, 0.1903, 0.3370])
Non-uniform random sample with replacement: tensor([0.2689, 0.9628, 0.1456, 0.4515, 0.3370])
Non-uniform random sample without replacement: tensor([0.2689, 0.0419, 0.4887, 0.2456, 0.4515])


16. Write a Pyorch snippet to create an nxn(input to function) tensor with random values. Create an array from the said array swapping first and last rows.

In [ ]:
import torch

def create_tensor_and_swap_rows(n):

  tensor = torch.rand(n, n)

  array = tensor.numpy()

  array[[0, -1]] = array[[-1, 0]]

  return array

array = create_tensor_and_swap_rows(5)

print(array)

[[0.4445182  0.0800131  0.28520924 0.48869908 0.22761053]
 [0.70339006 0.720431   0.54107744 0.61866677 0.8534196 ]
 [0.371028   0.13173735 0.73949337 0.09359401 0.6089768 ]
 [0.8149576  0.5099763  0.37306148 0.5716677  0.7496285 ]
 [0.9815309  0.32882923 0.79012424 0.11300647 0.99073553]]


17. Write a PyTorch snippet to sort a given tensor (1D or 2D) in ascending order.

In [ ]:
import torch

def sort_tensor(tensor):

  if tensor.ndim == 1:
    return torch.sort(tensor)[0]

  elif tensor.ndim == 2:
    return torch.sort(tensor, dim=1)[0]

  else:
    raise ValueError("Only 1D and 2D tensors are supported.")

tensor1 = torch.tensor([5, 2, 8, 1, 4])

sorted_tensor1 = sort_tensor(tensor1)

print("Original 1D tensor:", tensor1)
print("Sorted 1D tensor:", sorted_tensor1)

tensor2 = torch.tensor([[5, 2, 8],
                       [1, 4, 3]])

sorted_tensor2 = sort_tensor(tensor2)

print("Original 2D tensor:", tensor2)
print("Sorted 2D tensor:", sorted_tensor2)

Original 1D tensor: tensor([5, 2, 8, 1, 4])
Sorted 1D tensor: tensor([1, 2, 4, 5, 8])
Original 2D tensor: tensor([[5, 2, 8],
        [1, 4, 3]])
Sorted 2D tensor: tensor([[2, 5, 8],
        [1, 3, 4]])


18. Write a PyTorch snippet to create a tensor of equal shape and data type for a given tensor (any dimensional)

In [ ]:
import torch

def create_tensor_with_same_shape_and_dtype(input_tensor):

  return torch.empty_like(input_tensor)

input_tensor = torch.rand(3, 4, 5)

new_tensor = create_tensor_with_same_shape_and_dtype(input_tensor)

print("Input tensor shape:", input_tensor.shape)
print("Input tensor data type:", input_tensor.dtype)

print("New tensor shape:", new_tensor.shape)
print("New tensor data type:", new_tensor.dtype)


Input tensor shape: torch.Size([3, 4, 5])
Input tensor data type: torch.float32
New tensor shape: torch.Size([3, 4, 5])
New tensor data type: torch.float32


19. Write a PyTorch snippet to create an 8x8 matrix and fill it with a checkerboard pattern.
Checkerboard pattern:
```py
[[0 1 0 1 0 1 0 1]
..........
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]]
```

In [ ]:
import torch

def create_checkerboard_matrix(size):

  matrix = torch.zeros(size, size)

  for i in range(size):
    for j in range(size):
      if (i + j) % 2 == 0:
        matrix[i][j] = 1

  return matrix

checkerboard_matrix = create_checkerboard_matrix(12)

print(checkerboard_matrix)

tensor([[1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.]])


20. Write a Pytorch snippet to convert Centigrade to Fahrenheit and vice versa (controlled by a parameter). Ensure you operation is vectorized i.e **no explicit looping**

Sample Array: `[0, 12, 45.21, 34, 99.91]`

In [ ]:
import torch

def convert_temperature(temperature, to_fahrenheit):

  if to_fahrenheit:
    return temperature * 9 / 5 + 32
  else:
    return (temperature - 32) * 5 / 9

temperature_array = torch.tensor([0, 12, 45.21, 34, 99.91])

fahrenheit_array = convert_temperature(temperature_array, to_fahrenheit=True)
print("Converted to Fahrenheit:", fahrenheit_array)

centigrade_array = convert_temperature(fahrenheit_array, to_fahrenheit=False)
print("Converted to Centigrade:", centigrade_array)

Converted to Fahrenheit: tensor([ 32.0000,  53.6000, 113.3780,  93.2000, 211.8380])
Converted to Centigrade: tensor([ 0.0000, 12.0000, 45.2100, 34.0000, 99.9100])


21. Write a PyTorch snippet to get the values of the elements that are bigger than a given *number* in a given tensor.

Original tensor:
```
[[ 0 10 20]
[20 30 40]]
```
Number: 10

Values bigger than 10 = `[20 20 30 40]`

In [ ]:
import torch

def get_values_greater_than(tensor, number):

  mask = tensor > number

  return tensor[mask]

tensor = torch.tensor([[0, 10, 20],
                       [20, 30, 40]])

values_greater_than_10 = get_values_greater_than(tensor, 10)

print(values_greater_than_10)

tensor([20, 20, 30, 40])


22. Write a PyTorch snippet to create another shape from an array without changing its data. After carrying out the operation, change the data in one place and see if the other tensor changes

Reshape 3x2:
```
[[1 2]
[3 4]
[5 6]]
```
Reshape 2x3:
```
[[1 2 3]
[4 5 6]]
```

In [ ]:
import torch

tensor_3x2 = torch.tensor([[1, 2],
                           [3, 4],
                           [5, 6]])

tensor_2x3 = tensor_3x2.view(2, 3)

tensor_3x2[0, 0] = 10

print("3x2 tensor after change:", tensor_3x2)
print("2x3 tensor after change:", tensor_2x3)

3x2 tensor after change: tensor([[10,  2],
        [ 3,  4],
        [ 5,  6]])
2x3 tensor after change: tensor([[10,  2,  3],
        [ 4,  5,  6]])


23. Write a PyTorch snipppet to change an tensor's data type.
```
[[ 2 4 6]
[ 6 8 10]]
```
Data type of the array x is: `int32`

New Type: `float64`
```
[[ 2. 4. 6.]
[ 6. 8. 10.]]
```

In [ ]:
import torch

tensor = torch.tensor([[2, 4, 6],
                       [6, 8, 10]], dtype=torch.int32)

tensor = tensor.to(torch.float64)

print(tensor)
print(tensor.dtype)

tensor([[ 2.,  4.,  6.],
        [ 6.,  8., 10.]], dtype=torch.float64)
torch.float64


24. Write a PyTorch snippet to insert a new axis within a 2-tensor, based on a **parameter**.

Ex: If 2-tensor has shape (3, 4).

Then, new shape can be (1, 3, 4), (3, 1, 4), or (3, 4, 1) depending on....

In [ ]:
def insert_new_axis(tensor, axis):

  if axis < 0 or axis > tensor.ndim:
    raise ValueError("Invalid axis value.")

  return tensor.unsqueeze(axis)

tensor = torch.tensor([[1, 2, 3],
                       [4, 5, 6]])

new_tensor_1 = insert_new_axis(tensor, 0)
new_tensor_2 = insert_new_axis(tensor, 1)
new_tensor_3 = insert_new_axis(tensor, 2)

print("Original tensor shape:", tensor.shape)
print("New tensor shape (axis=0):", new_tensor_1.shape)
print("New tensor shape (axis=1):", new_tensor_2.shape)
print("New tensor shape (axis=2):", new_tensor_3.shape)

Original tensor shape: torch.Size([2, 3])
New tensor shape (axis=0): torch.Size([1, 2, 3])
New tensor shape (axis=1): torch.Size([2, 1, 3])
New tensor shape (axis=2): torch.Size([2, 3, 1])


25. Write a PyTorch snippet to stack tensors based on a parameter, **axis**.
First discover what this means with 2-tensors, then extend it to 3-tensors. Print your findings.

Sample Output:

Original tensors:

Tensor-1
```
[[0 1 2]
[3 4 5]
[6 7 8]]
```
Tensor-2
```
[[ 0 3 6]
[ 9 12 15]
[18 21 24]]
```
Stack tensors such that axis=1:
```
[[ 0 1 2 0 3 6]
[ 3 4 5 9 12 15]
[ 6 7 8 18 21 24]]
```

In [ ]:
import torch

tensor1 = torch.tensor([[0, 1, 2],
                       [3, 4, 5],
                       [6, 7, 8]])
tensor2 = torch.tensor([[0, 3, 6],
                       [9, 12, 15],
                       [18, 21, 24]])

stacked_tensor = torch.stack((tensor1, tensor2), dim=1)
print(tensor1,'\n\n',tensor2,'\n\n')
print("Stacked tensor along axis=1:")
print(stacked_tensor)

tensor3 = torch.tensor([[[0, 1, 2],
                       [3, 4, 5],
                       [6, 7, 8]],
                      [[9, 10, 11],
                       [12, 13, 14],
                       [15, 16, 17]]])
tensor4 = torch.tensor([[[18, 19, 20],
                       [21, 22, 23],
                       [24, 25, 26]],
                      [[27, 28, 29],
                       [30, 31, 32],
                       [33, 34, 35]]])

stacked_tensor = torch.stack((tensor3, tensor4), dim=0)

print("\nStacked tensor along axis=0:")
print(stacked_tensor)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]) 

 tensor([[ 0,  3,  6],
        [ 9, 12, 15],
        [18, 21, 24]]) 


Stacked tensor along axis=1:
tensor([[[ 0,  1,  2],
         [ 0,  3,  6]],

        [[ 3,  4,  5],
         [ 9, 12, 15]],

        [[ 6,  7,  8],
         [18, 21, 24]]])

Stacked tensor along axis=0:
tensor([[[[ 0,  1,  2],
          [ 3,  4,  5],
          [ 6,  7,  8]],

         [[ 9, 10, 11],
          [12, 13, 14],
          [15, 16, 17]]],


        [[[18, 19, 20],
          [21, 22, 23],
          [24, 25, 26]],

         [[27, 28, 29],
          [30, 31, 32],
          [33, 34, 35]]]])


26. Write a PyTorch snippet to extract the **m**th to **n**th elements of the **m**th to **n**th rows from the **m**th to nth elemnts of given 3-tensor, of shape `(p, q, r)` where m, n < p, q, r.

Take a 3-tensor of (say) size `(5,6,7)` and `(m, n)` = `(4, 5)` as a test case!

In [ ]:
import torch

tensor = torch.arange(3*4*5).reshape(3, 4, 5)

m = 1
n = 2

extracted_tensor = tensor[m:n+1, m:n+1, m:n+1]

print("Original tensor:\n", tensor)
print(f"Extracted sub-tensor from index {m} to {n}:\n", extracted_tensor)

Original tensor:
 tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39]],

        [[40, 41, 42, 43, 44],
         [45, 46, 47, 48, 49],
         [50, 51, 52, 53, 54],
         [55, 56, 57, 58, 59]]])
Extracted sub-tensor from index 1 to 2:
 tensor([[[26, 27],
         [31, 32]],

        [[46, 47],
         [51, 52]]])


### **Test your Understanding**

1. Given a 3D tensor of shape `(a, b, c)`*italicised text*, permute its axes to obtain tensors of all other shape combinations (i.e 5).

In [ ]:
import torch

tensor = torch.arange(24).reshape(2, 3, 4)

permutations = [(0, 1, 2), (0, 2, 1), (1, 0, 2), (1, 2, 0), (2, 0, 1), (2, 1, 0)]

for permutation in permutations:
  permuted_tensor = tensor.permute(permutation)
  print(f"Shape: {permuted_tensor.shape}")
  print(permuted_tensor)
  print()

Shape: torch.Size([2, 3, 4])
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

Shape: torch.Size([2, 4, 3])
tensor([[[ 0,  4,  8],
         [ 1,  5,  9],
         [ 2,  6, 10],
         [ 3,  7, 11]],

        [[12, 16, 20],
         [13, 17, 21],
         [14, 18, 22],
         [15, 19, 23]]])

Shape: torch.Size([3, 2, 4])
tensor([[[ 0,  1,  2,  3],
         [12, 13, 14, 15]],

        [[ 4,  5,  6,  7],
         [16, 17, 18, 19]],

        [[ 8,  9, 10, 11],
         [20, 21, 22, 23]]])

Shape: torch.Size([3, 4, 2])
tensor([[[ 0, 12],
         [ 1, 13],
         [ 2, 14],
         [ 3, 15]],

        [[ 4, 16],
         [ 5, 17],
         [ 6, 18],
         [ 7, 19]],

        [[ 8, 20],
         [ 9, 21],
         [10, 22],
         [11, 23]]])

Shape: torch.Size([4, 2, 3])
tensor([[[ 0,  4,  8],
         [12, 16, 20]],

        [[ 1,  5,  9],
         [13, 17, 21]],


2. Given a 4D tensor of shape `(2, 3, 4, 5)`, transpose it to obtain a tensor of shape `(2, 4, 5, 3)`. Also explore what is_contiguous() means...

In [ ]:
import torch

tensor = torch.arange(2 * 3 * 4 * 5).reshape(2, 3, 4, 5)

transposed_tensor = tensor.transpose(1, 2)

print(transposed_tensor.shape)

print(transposed_tensor.is_contiguous())

torch.Size([2, 4, 3, 5])
False


3. Given two tensors, one of shape (n, 1) and another of shape (m, ), perform an element-wise addition **manually**. Then, test out what direct addition does and compare your results!

In [2]:
import numpy as np

n = 4
m = 3
A = np.array([[1], [2], [3], [4]])
B = np.array([10, 20, 30])

result_manual = np.zeros((n, m))
for i in range(n):
    for j in range(m):
        result_manual[i, j] = A[i, 0] + B[j]

result_direct = A + B

print(result_manual)
print(result_direct)

print( np.array_equal(result_manual, result_direct))

[[11. 21. 31.]
 [12. 22. 32.]
 [13. 23. 33.]
 [14. 24. 34.]]
[[11 21 31]
 [12 22 32]
 [13 23 33]
 [14 24 34]]
True


4. Given a 3D tensor of shape `(4, 4, 4)`, extract a sub-tensor of shape `(2, 2, 2)` starting from the element at index `(1, 1, 1)`**bold text**.

In [4]:
import torch

original_tensor = torch.arange(64).reshape(4, 4, 4)

sub_tensor = original_tensor[1:3, 1:3, 1:3]

print(original_tensor)
print(sub_tensor)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15]],

        [[16, 17, 18, 19],
         [20, 21, 22, 23],
         [24, 25, 26, 27],
         [28, 29, 30, 31]],

        [[32, 33, 34, 35],
         [36, 37, 38, 39],
         [40, 41, 42, 43],
         [44, 45, 46, 47]],

        [[48, 49, 50, 51],
         [52, 53, 54, 55],
         [56, 57, 58, 59],
         [60, 61, 62, 63]]])
tensor([[[21, 22],
         [25, 26]],

        [[37, 38],
         [41, 42]]])


5. Given a 2-tensor of arbitrary shape, rotate it 90 degrees anticlockwise.



In [7]:
import numpy as np

def rotate_90_anticlockwise(matrix):
    transposed_matrix = np.transpose(matrix)
    rotated_matrix = np.flipud(transposed_matrix)
    return rotated_matrix

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

rotated_matrix = rotate_90_anticlockwise(matrix)
print(rotated_matrix)

[[3 6 9]
 [2 5 8]
 [1 4 7]]


### **EVEN I HAD TO THINK...**

1. Implement a custom operation that computes the **element-wise** **sine** of a tensor *and* its **gradient** using torch.autograd.Function.
- You need to implement both the forward() and backward() methods.
- For an example, look no further than the [PyTorch docs](https://pytorch.org/docs/stable/autograd.html#function)!
- Test it out on a matrix of arbitrary size!

2. One of the most important aspects of improving model performance ins normalization. Implement a custom NN normalization layer that performs either a **batch** or **layer** normalization (based on a **dim** parameter)and integrate it into a simple feedforward neural network.
- Note that you dont need to implement any backward() here, for simplicity.
- Consider your input tensor to the neural network as of shape (m, n) where m is num of examples, n is num of features.
- Which value of **dim** leads to batch and layer normalization?

In [8]:
import torch
import torch.nn as nn

class CustomNormalization(nn.Module):
    def __init__(self, dim, eps=1e-5):
        super(CustomNormalization, self).__init__()
        self.dim = dim
        self.eps = eps

    def forward(self, x):
        if self.dim == 0:
            mean = x.mean(dim=0, keepdim=True)
            std = x.std(dim=0, keepdim=True)
        elif self.dim == 1:
            mean = x.mean(dim=1, keepdim=True)
            std = x.std(dim=1, keepdim=True)
        else:
            raise ValueError("Invalid dim value.")

        return (x - mean) / (std + self.eps)

class MyNetwork(nn.Module):
    def __init__(self, input_size, hidden_size):
        super(MyNetwork, self).__init__()
        self.linear1 = nn.Linear(input_size, hidden_size)
        self.norm = CustomNormalization(dim=1)
        self.linear2 = nn.Linear(hidden_size, 1)

    def forward(self, x):
        x = self.linear1(x)
        x = self.norm(x)
        x = self.linear2(x)
        return x

net = MyNetwork(10, 5)

x = torch.randn(64, 10)

y = net(x)

print(y)

tensor([[-0.8023],
        [-0.7135],
        [-0.2798],
        [-0.6428],
        [-0.3294],
        [-0.4747],
        [ 0.2609],
        [-0.6380],
        [-0.3840],
        [ 0.0745],
        [-0.2844],
        [-0.6170],
        [ 0.0858],
        [-0.5191],
        [-0.6459],
        [-0.3341],
        [-0.3769],
        [-0.5137],
        [-0.6314],
        [-0.5256],
        [-0.5757],
        [-0.1562],
        [-0.3107],
        [-0.0571],
        [-0.6922],
        [-0.3468],
        [-0.5834],
        [ 0.3710],
        [-0.8132],
        [-0.0062],
        [-0.0056],
        [ 0.0792],
        [-0.0292],
        [-0.8632],
        [-0.0481],
        [-0.4015],
        [-0.2991],
        [ 0.0633],
        [-0.3862],
        [-0.8190],
        [-0.4389],
        [-0.3752],
        [ 0.1632],
        [-0.0055],
        [-0.6140],
        [-0.1484],
        [ 0.0472],
        [-0.3831],
        [-0.1401],
        [-0.1260],
        [-0.1099],
        [-0.4038],
        [-0.

3. Given a 4D tensor of shape (2, 3, 4, 5), create a mask that sets all elements in positions where the sum of indices is even to zero.

In [9]:
import torch

def create_mask_for_even_indices(tensor):

  mask = torch.ones_like(tensor)

  for i in range(tensor.shape[0]):
    for j in range(tensor.shape[1]):
      for k in range(tensor.shape[2]):
        for l in range(tensor.shape[3]):
          if (i + j + k + l) % 2 == 0:
            mask[i, j, k, l] = 0

  return mask

tensor = torch.arange(120).reshape(2, 3, 4, 5)

mask = create_mask_for_even_indices(tensor)

masked_tensor = tensor * mask

print(masked_tensor)

tensor([[[[  0,   1,   0,   3,   0],
          [  5,   0,   7,   0,   9],
          [  0,  11,   0,  13,   0],
          [ 15,   0,  17,   0,  19]],

         [[ 20,   0,  22,   0,  24],
          [  0,  26,   0,  28,   0],
          [ 30,   0,  32,   0,  34],
          [  0,  36,   0,  38,   0]],

         [[  0,  41,   0,  43,   0],
          [ 45,   0,  47,   0,  49],
          [  0,  51,   0,  53,   0],
          [ 55,   0,  57,   0,  59]]],


        [[[ 60,   0,  62,   0,  64],
          [  0,  66,   0,  68,   0],
          [ 70,   0,  72,   0,  74],
          [  0,  76,   0,  78,   0]],

         [[  0,  81,   0,  83,   0],
          [ 85,   0,  87,   0,  89],
          [  0,  91,   0,  93,   0],
          [ 95,   0,  97,   0,  99]],

         [[100,   0, 102,   0, 104],
          [  0, 106,   0, 108,   0],
          [110,   0, 112,   0, 114],
          [  0, 116,   0, 118,   0]]]])


3. Given two tensors, one of shape `(3, 1, 4)` and another of shape `(1, 5, 1)`, compute their element-wise multiplication using broadcasting and then sum over specific axes to obtain a tensor of shape `(3, 5)`.

In [10]:
import torch

tensor1 = torch.tensor([[1, 2, 3, 4],
                       [5, 6, 7, 8],
                       [9, 10, 11, 12]])
tensor1 = tensor1.reshape(3, 1, 4)

tensor2 = torch.tensor([[[10],
                       [20],
                       [30],
                       [40],
                       [50]]])
tensor2 = tensor2.reshape(1, 5, 1)

tensor3 = tensor1 * tensor2

tensor4 = tensor3.sum(dim=2)

print(tensor4)

tensor([[ 100,  200,  300,  400,  500],
        [ 260,  520,  780, 1040, 1300],
        [ 420,  840, 1260, 1680, 2100]])
