#  **PyTorch Practice Assignment**
**Name**: Aayush Anand

**Roll Number**: 231EE101

## **Instructions:**

- Copy this Notebook to your own Drive! You cannot directly modify it.
- Please show the output of the cells, in case of some operation. You can specify your own **non-trivial** test-case. Also, try and make your snippets into functions to organize your logic.
- You can use any number of cells for a question, you are not restricted to just 1 cell!
- **No using ChatGPT for this assignment**: we highly recommend using the [Pytorch Docs](https://pytorch.org/docs/stable/index.html) as your start reference, as well as the vast internet however. You can also contact any of your mentors for some hints/help!
- You can work on this assignment in Google Colab or on Your Local Machine!

In [2]:
import torch

### **Build Up Your Understanding**

1. Write a PyTorch snippet to test whether none of the elements of a given tensor are zero.

In [ ]:
ones = torch.ones(5,5)
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [ ]:
0 in ones

False

In [ ]:
ones[2][2] = 0
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 0., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [ ]:
0 in ones

True

2. Write a PyTorch snippet to test element-wise for NaN of a given tensor.

In [ ]:
tensor1 = torch.tensor(([2,4,6],[float('nan'),8,12],[6,12,float('nan')]))
tensor1

tensor([[ 2.,  4.,  6.],
        [nan,  8., 12.],
        [ 6., 12., nan]])

In [ ]:
torch.isnan(tensor1)

tensor([[False, False, False],
        [ True, False, False],
        [False, False,  True]])

3. Write a PyTorch snippet to test whether two tensors are element-wise equal within a tolerance.

In [ ]:
tensor2 = torch.rand(5,4)
tensor2

tensor([[0.3325, 0.6326, 0.6840, 0.0622],
        [0.4050, 0.1255, 0.3409, 0.6486],
        [0.1586, 0.3605, 0.2638, 0.8656],
        [0.0219, 0.1122, 0.9878, 0.0756],
        [0.3585, 0.1503, 0.8112, 0.1986]])

In [ ]:
tensor3 = tensor2 + 0.00000003
tensor4 = tensor2 + 0.003

In [ ]:
rtol = 1e-5           #relative tolerance
atol = 1e-8           #absolute tolerance
torch.isclose(tensor2,tensor3,rtol=rtol,atol=rtol)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [ ]:
torch.isclose(tensor2,tensor4,rtol=rtol,atol=rtol)

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

4. Write a PyTorch snippet to create a tensor of 10 zeros, 10 ones, and 10 fives stacked on top of each other (try & accomplish everything using nested function calls).

In [ ]:
torch.stack([torch.zeros(10,dtype=int),torch.ones(10,dtype=int),torch.ones(10,dtype=int)*5],dim=0)

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

5. Write a PyTorch snippet to generate a random number between 0 and 1.

In [49]:
zeros_arr = torch.zeros(10,dtype=int)
torch.stack([zeros_arr,zeros_arr+1,zeros_arr+5])      #dim=0 by default

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

6. Write a PyTorch snippet to generate a tensor of 15 random numbers from a standard normal distribution.

In [ ]:
torch.randn(15)

tensor([ 0.4991, -1.0101, -0.4802,  0.3947, -0.5015, -0.3226, -0.3944,  1.0351,
        -0.3325, -0.6029, -0.2497, -0.0390, -1.8357,  0.9156,  1.5187])

7. Write a Pytorch snippet to create a tensor of length 10 with values evenly distributed between 5 and 50.

In [ ]:
torch.arange(5,51,5)

tensor([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

8. Write a Pyorch program to create a tensor with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15.

In [ ]:
tensor5 = torch.arange(0,21,1)
tensor5

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20])

In [ ]:
tensor5[9:16] *= -1
tensor5

tensor([  0,   1,   2,   3,   4,   5,   6,   7,   8,  -9, -10, -11, -12, -13,
        -14, -15,  16,  17,  18,  19,  20])

9. Write a PyTorch snippet to create a 3x4 2-tensor filled with values from 10 to 21. Same but 12 to 24.

In [ ]:
t6 = torch.arange(10,22).reshape(3,4)
t6

tensor([[10, 11, 12, 13],
        [14, 15, 16, 17],
        [18, 19, 20, 21]])

In [ ]:
t6 + 2

tensor([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])

10. Write a PyTorch snippet to create a 10x10 2-tensor, in which the elements on the borders will be equal to 1, and inside 0.

In [ ]:
upline = torch.ones(1,8)
centre = torch.zeros(8,8)
sideline = torch.ones(10,1)
torch.cat([sideline,torch.cat([upline,centre,upline],dim=0),sideline],dim=1)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
ones_mat = torch.ones(10,10)
ones_mat[1:9,1:9] = 0
ones_mat

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

11. Write a PyTorch snippet to create a 5x5 zero 2-tensor with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [ ]:
t8 = torch.zeros(5,5)
diag = torch.arange(1,6).type_as(t8)
indices = torch.arange(t8.size(0))
t8[indices,indices]=diag
t8

tensor([[1., 0., 0., 0., 0.],
        [0., 2., 0., 0., 0.],
        [0., 0., 3., 0., 0.],
        [0., 0., 0., 4., 0.],
        [0., 0., 0., 0., 5.]])

12. Write a PyTorch snippet to save a given tensor as a binary to a given path.

In [ ]:
t9 = torch.rand(5,5)
t9

tensor([[0.2190, 0.1986, 0.4369, 0.4098, 0.1237],
        [0.3889, 0.0071, 0.1540, 0.0294, 0.3675],
        [0.9146, 0.0369, 0.0237, 0.7262, 0.0120],
        [0.8793, 0.9684, 0.0588, 0.7492, 0.2270],
        [0.0195, 0.9542, 0.8329, 0.3318, 0.9027]])

In [ ]:
torch.save(t9,'t9_tensor.bin')

In [ ]:
torch.load('t9_tensor.bin')

tensor([[0.2190, 0.1986, 0.4369, 0.4098, 0.1237],
        [0.3889, 0.0071, 0.1540, 0.0294, 0.3675],
        [0.9146, 0.0369, 0.0237, 0.7262, 0.0120],
        [0.8793, 0.9684, 0.0588, 0.7492, 0.2270],
        [0.0195, 0.9542, 0.8329, 0.3318, 0.9027]])

13. Write a NumPy program to create a two-dimensional array of a specified format.

In [ ]:
import numpy as np
def create_mat(dim1,dim2):
  mat = np.random.rand(dim1*dim2).reshape(dim1,dim2)
  return mat

create_mat(5,4)

array([[0.59441083, 0.93117881, 0.80189379, 0.43757554],
       [0.61116194, 0.42387203, 0.45213012, 0.79887358],
       [0.94764047, 0.12967238, 0.21162766, 0.72581253],
       [0.94104686, 0.67798077, 0.01700862, 0.79510659],
       [0.0286566 , 0.16694346, 0.55308182, 0.88125786]])

14. Write a PyTorch snippet to create a 2-tensor with shape (8,5) of random numbers. Select these random numbers (to create the tensor) from a normal distribution (200,7) (mean, variance).

In [ ]:
t10 = torch.randn(8,5)
t10, t10.mean(), t10.var()

(tensor([[ 0.6757,  0.8218,  0.4032, -0.1847,  1.6876],
         [ 0.5756,  0.1897,  0.2380,  0.1871,  0.7908],
         [ 2.5054,  0.1817,  0.8243, -0.8027,  1.3730],
         [ 0.8437, -1.8024, -0.3297, -0.9022, -0.1322],
         [ 2.4176,  0.0995, -0.9584,  0.9955, -1.2712],
         [ 0.1264, -1.5144, -1.5899,  0.3845, -0.1481],
         [-0.9644, -0.9947, -0.8798,  0.4167, -0.9430],
         [-0.5097,  0.5377, -0.7008,  0.4687, -0.6374]]),
 tensor(0.0370),
 tensor(1.0111))

In [ ]:
mean = 200
var = 7
std = torch.sqrt(torch.tensor(var))

t10_modified = t10 * std + mean
t10_modified, t10_modified.mean(), t10.var()

(tensor([[201.7878, 202.1743, 201.0667, 199.5114, 204.4649],
         [201.5228, 200.5018, 200.6297, 200.4949, 202.0922],
         [206.6286, 200.4807, 202.1809, 197.8763, 203.6325],
         [202.2323, 195.2314, 199.1276, 197.6130, 199.6503],
         [206.3963, 200.2633, 197.4644, 202.6338, 196.6367],
         [200.3345, 195.9934, 195.7936, 201.0173, 199.6082],
         [197.4484, 197.3684, 197.6722, 201.1024, 197.5052],
         [198.6515, 201.4226, 198.1460, 201.2399, 198.3137]]),
 tensor(200.0978),
 tensor(1.0111))

15. Write a PyTorch snippet to generate a uniform, non-uniform random sample from a given vector with and without replacement (do all 4 combinations possible).

16. Write a Pyorch snippet to create an nxn(input to function) tensor with random values. Create an array from the said array swapping first and last rows.

In [ ]:
def swaping(n):
  tsr = torch.rand(n,n)
  tsr_clone = tsr.clone()
  tsr[:,0] = tsr_clone[:,n-1]
  tsr[:,n-1] = tsr_clone[:,0]
  return tsr, tsr_clone

swaping(5)

(tensor([[0.4528, 0.2060, 0.8672, 0.1063, 0.7433],
         [0.0294, 0.8432, 0.0818, 0.4639, 0.2458],
         [0.9872, 0.2592, 0.8293, 0.4236, 0.2974],
         [0.3953, 0.8903, 0.3900, 0.8445, 0.9184],
         [0.0429, 0.4522, 0.9411, 0.3165, 0.6726]]),
 tensor([[0.7433, 0.2060, 0.8672, 0.1063, 0.4528],
         [0.2458, 0.8432, 0.0818, 0.4639, 0.0294],
         [0.2974, 0.2592, 0.8293, 0.4236, 0.9872],
         [0.9184, 0.8903, 0.3900, 0.8445, 0.3953],
         [0.6726, 0.4522, 0.9411, 0.3165, 0.0429]]))

17. Write a PyTorch snippet to sort a given tensor (1D or 2D) in ascending order.

In [ ]:
smpl = torch.randint(10,25,(3,4))
smpl, torch.sort(smpl,dim=0)        #dim = 0 sorted within row, dim = 1 sorted within coloumn

(tensor([[24, 21, 14, 12],
         [12, 19, 13, 14],
         [18, 19, 15, 11]]),
 torch.return_types.sort(
 values=tensor([[12, 19, 13, 11],
         [18, 19, 14, 12],
         [24, 21, 15, 14]]),
 indices=tensor([[1, 1, 1, 2],
         [2, 2, 0, 0],
         [0, 0, 2, 1]])))

In [ ]:
smpl2 = torch.randint(5,10,(7,))
sorted_tsr, sorted_indices = torch.sort(smpl2)
sorted_tsr, sorted_indices

(tensor([5, 5, 5, 5, 6, 8, 8]), tensor([1, 3, 4, 6, 2, 0, 5]))

18. Write a PyTorch snippet to create a tensor of equal shape and data type for a given tensor (any dimensional)

In [ ]:
example = torch.randint(5,50,(6,3))
new = torch.empty_like(example)
example.shape, new.shape, example.dtype, new.dtype, example, new

(torch.Size([6, 3]),
 torch.Size([6, 3]),
 torch.int64,
 torch.int64,
 tensor([[13, 40,  7],
         [40, 38, 40],
         [20, 27, 39],
         [ 8, 11, 40],
         [13, 22, 29],
         [36, 15, 10]]),
 tensor([[138835024232784, 138836148583728, 138836147312016],
         [138836148583728, 138835024243968, 138836132582448],
         [138836147314896, 138836132582448, 138836132582448],
         [138836132582448, 138835024248192, 138836148583728],
         [138836148790224, 138836147945712, 138836147314896],
         [138836147945712, 138836148583728, 138836147313120]]))

19. Write a PyTorch snippet to create an 8x8 matrix and fill it with a checkerboard pattern.
Checkerboard pattern:
```py
[[0 1 0 1 0 1 0 1]
..........
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]]
```

In [ ]:
block1 =torch.cat([torch.tensor([0,1],dtype=int)]*4,dim=0)
block2 = block1.flip(dims=[0])
block = torch.stack([block1,block2],dim=0)
board = torch.cat([block]*4,dim=0)
board

tensor([[0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0],
        [0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0],
        [0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0],
        [0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0]])

20. Write a Pytorch snippet to convert Centigrade to Fahrenheit and vice versa (controlled by a parameter). Ensure you operation is vectorized i.e **no explicit looping**

Sample Array: `[0, 12, 45.21, 34, 99.91]`

In [ ]:
def temp_conversion(C:torch.Tensor):
  F = 9/5 * C +32
  return F

sample = torch.tensor([0,12,45.21,34,99.91])
temp_in_F = temp_conversion(sample)
temp_in_F

tensor([ 32.0000,  53.6000, 113.3780,  93.2000, 211.8380])

21. Write a PyTorch snippet to get the values of the elements that are bigger than a given *number* in a given tensor.

Original tensor:
```
[[ 0 10 20]
[20 30 40]]
```
Number: 10

Values bigger than 10 = `[20 20 30 40]`

In [ ]:
sample_tsr = torch.tensor([[ 0, 10, 20],[20, 30, 40]])
sample_tsr[sample_tsr>10]

tensor([20, 20, 30, 40])

22. Write a PyTorch snippet to create another shape from an array without changing its data. After carrying out the operation, change the data in one place and see if the other tensor changes

Reshape 3x2:
```
[[1 2]
[3 4]
[5 6]]
```
Reshape 2x3:
```
[[1 2 3]
[4 5 6]]
```

In [ ]:
data1 = torch.arange(1,7,1).reshape(2,3)
data2 = data1.reshape(3,2)
data1, data2

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 tensor([[1, 2],
         [3, 4],
         [5, 6]]))

In [ ]:
data1[1][2]=10
data1,data2

(tensor([[ 1,  2,  3],
         [ 4,  5, 10]]),
 tensor([[ 1,  2],
         [ 3,  4],
         [ 5, 10]]))

23. Write a PyTorch snipppet to change an tensor's data type.
```
[[ 2 4 6]
[ 6 8 10]]
```
Data type of the array x is: `int32`

New Type: `float64`
```
[[ 2. 4. 6.]
[ 6. 8. 10.]]
```

In [ ]:
data3 = torch.tensor([[2,4,6],[6,8,10]]).reshape(2,3)
data3

tensor([[ 2,  4,  6],
        [ 6,  8, 10]])

In [ ]:
data3 = data3.float()
data3

tensor([[ 2.,  4.,  6.],
        [ 6.,  8., 10.]])

24. Write a PyTorch snippet to insert a new axis within a 2-tensor, based on a **parameter**.

Ex: If 2-tensor has shape (3, 4).

Then, new shape can be (1, 3, 4), (3, 1, 4), or (3, 4, 1) depending on....

In [ ]:
tsr = torch.rand(3,4)
tsr_new0 = tsr.unsqueeze(dim=0)
tsr_new1 = tsr.unsqueeze(dim=1)
tsr_new2 = tsr.unsqueeze(dim=2)
tsr_new0.shape, tsr_new1.shape, tsr_new2.shape

(torch.Size([1, 3, 4]), torch.Size([3, 1, 4]), torch.Size([3, 4, 1]))

25. Write a PyTorch snippet to stack tensors based on a parameter, **axis**.
First discover what this means with 2-tensors, then extend it to 3-tensors. Print your findings.

Sample Output:

Original tensors:

Tensor-1
```
[[0 1 2]
[3 4 5]
[6 7 8]]
```
Tensor-2
```
[[ 0 3 6]
[ 9 12 15]
[18 21 24]]
```
Stack tensors such that axis=1:
```
[[ 0 1 2 0 3 6]
[ 3 4 5 9 12 15]
[ 6 7 8 18 21 24]]
```

In [ ]:
b1 = torch.arange(0,9,1).reshape(3,3)
b2 = b1 *3
stacked = torch.cat([b1,b2],axis=1)
b1, b2, stacked

(tensor([[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]),
 tensor([[ 0,  3,  6],
         [ 9, 12, 15],
         [18, 21, 24]]),
 tensor([[ 0,  1,  2,  0,  3,  6],
         [ 3,  4,  5,  9, 12, 15],
         [ 6,  7,  8, 18, 21, 24]]))

In [ ]:
torch.hstack([b1,b2])

tensor([[ 0,  1,  2,  0,  3,  6],
        [ 3,  4,  5,  9, 12, 15],
        [ 6,  7,  8, 18, 21, 24]])

26. Write a PyTorch snippet to extract the **m**th to **n**th elements of the **m**th to **n**th rows from the **m**th to nth elemnts of given 3-tensor, of shape `(p, q, r)` where m, n < p, q, r.

Take a 3-tensor of (say) size `(5,6,7)` and `(m, n)` = `(4, 5)` as a test case!

In [ ]:
tsr_smpl = torch.rand(5,6,7)
m,n=2,5
tsr_smpl[m:n,m:n,m:n]

tensor([[[0.5476, 0.2622, 0.6584],
         [0.7747, 0.3713, 0.2853],
         [0.8555, 0.4334, 0.7561]],

        [[0.4318, 0.9879, 0.4917],
         [0.7115, 0.5039, 0.7958],
         [0.6500, 0.8525, 0.5197]],

        [[0.4010, 0.7248, 0.6461],
         [0.9495, 0.0913, 0.7702],
         [0.8024, 0.1221, 0.2752]]])

### **Test your Understanding**

1. Given a 3D tensor of shape `(a, b, c)`*italicised text*, permute its axes to obtain tensors of all other shape combinations (i.e 5).

In [4]:
def permute(a,b,c):
  tensor_3d = torch.rand(a, b, c)

  tensor_acb = tensor_3d.permute(0, 2, 1)  # Shape (a, c, b)
  tensor_bac = tensor_3d.permute(1, 0, 2)  # Shape (b, a, c)
  tensor_bca = tensor_3d.permute(1, 2, 0)  # Shape (b, c, a)
  tensor_cab = tensor_3d.permute(2, 0, 1)  # Shape (c, a, b)
  tensor_cba = tensor_3d.permute(2, 1, 0)  # Shape (c, b, a)

  print("Original tensor shape (a, b, c):", tensor_3d.shape)
  print("Permuted tensor shape (a, c, b):", tensor_acb.shape)
  print("Permuted tensor shape (b, a, c):", tensor_bac.shape)
  print("Permuted tensor shape (b, c, a):", tensor_bca.shape)
  print("Permuted tensor shape (c, a, b):", tensor_cab.shape)
  print("Permuted tensor shape (c, b, a):", tensor_cba.shape)

  return

permute(2,4,6)


Original tensor shape (a, b, c): torch.Size([2, 4, 6])
Permuted tensor shape (a, c, b): torch.Size([2, 6, 4])
Permuted tensor shape (b, a, c): torch.Size([4, 2, 6])
Permuted tensor shape (b, c, a): torch.Size([4, 6, 2])
Permuted tensor shape (c, a, b): torch.Size([6, 2, 4])
Permuted tensor shape (c, b, a): torch.Size([6, 4, 2])


2. Given a 4D tensor of shape `(2, 3, 4, 5)`, transpose it to obtain a tensor of shape `(2, 4, 5, 3)`. Also explore what is_contiguous() means...

In [10]:
tensor_4d = torch.rand(2, 3, 4, 5)
transpose = tensor_4d.permute(0, 2, 3, 1)

tensor_4d.shape, transpose.shape

(torch.Size([2, 3, 4, 5]), torch.Size([2, 4, 5, 3]))

In [8]:
tensor_4d.is_contiguous(), transpose.is_contiguous()

(True, False)

In [12]:
transpose = transpose.contiguous()          # saving contiguous in the same varriable
transpose.is_contiguous()

## for better  performance a tensor should be contigous
## permutations and transpose make tensor discontiguous

True

3. Given two tensors, one of shape (n, 1) and another of shape (m, ), perform an element-wise addition.

In [21]:
n = 5
m = 6

tsr1 = torch.randint(1,5,(n,1))
tsr2 = torch.randint(5,10,(m,))

tsr1,tsr2,tsr1.shape, tsr2.shape

(tensor([[2],
         [4],
         [2],
         [2],
         [3]]),
 tensor([7, 6, 5, 9, 7, 8]),
 torch.Size([5, 1]),
 torch.Size([6]))

In [26]:
addition = tsr1 + tsr2     # broadcasting
addition, addition.shape

(tensor([[ 9,  8,  7, 11,  9, 10],
         [11, 10,  9, 13, 11, 12],
         [ 9,  8,  7, 11,  9, 10],
         [ 9,  8,  7, 11,  9, 10],
         [10,  9,  8, 12, 10, 11]]),
 torch.Size([5, 6]))

4. Given a 3D tensor of shape `(4, 4, 4)`, extract a sub-tensor of shape `(2, 2, 2)` starting from the element at index `(1, 1, 1)`**bold text**.

In [34]:
tsr_3d  = torch.randint(1,20,(4,4,4))
sub_tsr_3d = tsr_3d[1:3,1:3,1:3]

tsr_3d, sub_tsr_3d

(tensor([[[ 3, 18, 16, 17],
          [19, 18, 17, 10],
          [ 9, 18,  5, 12],
          [ 5, 12,  4, 15]],
 
         [[12, 18,  2, 16],
          [ 4,  3, 18, 17],
          [16,  5, 13, 13],
          [19,  8, 12,  9]],
 
         [[ 2,  5, 11,  8],
          [17,  9, 18,  2],
          [ 4,  3,  8, 15],
          [ 6, 12, 17, 16]],
 
         [[19,  9, 10, 19],
          [ 1, 15, 12,  5],
          [ 7, 19,  2, 19],
          [18, 14, 10,  9]]]),
 tensor([[[ 3, 18],
          [ 5, 13]],
 
         [[ 9, 18],
          [ 3,  8]]]))

5. Given a 2-tensor of arbitrary shape, rotate it 90 degrees anticlockwise.



In [35]:
tsr_2d = torch.randint(1,100,(5,7))

def rotate(tensor:torch.Tensor):
  return tensor.T.flip(dims=[1])

tsr_2d, rotate(tsr_2d)

(tensor([[64, 20,  2,  5, 16,  6, 63],
         [54, 55, 49, 75, 35, 30, 67],
         [25, 79, 65, 64,  4, 24, 27],
         [68, 15, 55, 40, 34, 41, 62],
         [58, 46, 90,  6, 42, 94, 92]]),
 tensor([[58, 68, 25, 54, 64],
         [46, 15, 79, 55, 20],
         [90, 55, 65, 49,  2],
         [ 6, 40, 64, 75,  5],
         [42, 34,  4, 35, 16],
         [94, 41, 24, 30,  6],
         [92, 62, 27, 67, 63]]))

### **EVEN I HAD TO THINK...**

1. Implement a custom operation that computes the **element-wise** **sine** of a tensor *and* its **gradient** using torch.autograd.Function.
- You need to implement both the forward() and backward() methods.
- For an example, look no further than the [PyTorch docs](https://pytorch.org/docs/stable/autograd.html#function)!
- Test it out on a matrix of arbitrary size!

2. One of the most important aspects of improving model performance ins normalization. Implement a custom NN normalization layer that performs either a **batch** or **layer** normalization (based on a **dim** parameter)and integrate it into a simple feedforward neural network.
- Note that you dont need to implement any backward() here, for simplicity.
- Consider your input tensor to the neural network as of shape (m, n) where m is num of examples, n is num of features.
- Which value of **dim** leads to batch and layer normalization?

In [23]:
m = 8 # num of examples
n = 5 # num of features
inp_tsr = torch.randint(10,20,(m,n)).float()
inp_tsr

tensor([[15., 13., 11., 18., 16.],
        [12., 18., 12., 19., 13.],
        [10., 17., 15., 10., 15.],
        [15., 12., 13., 18., 11.],
        [14., 14., 13., 13., 13.],
        [18., 13., 16., 12., 18.],
        [19., 12., 14., 18., 16.],
        [16., 13., 15., 14., 18.]])

In [15]:
import torch.nn as nn

class CustomNormLayer(nn.Module):
  def __init__(self,tensor:torch.Tensor, num_features, dim):
    super().__init__()

    if self.dim == 'batch':
      self.norm = nn.BatchNorm1d(num_features)
    elif self.dim == 'layer':
      self.norm = nn.LayerNorm(num_features)

  def forward(self,tensor):
    return self.norm(tensor)

In [24]:
inp_tsr = inp_tsr
batch_norm = CustomNormLayer(num_features = inp_tsr.size(1), dim='batch')
layer_norm = CustomNormLayer(num_features = inp_tsr.size(1), dim='layer')
batch_norm(inp_tsr), layer_norm(inp_tsr)

(tensor([[ 4.5314e-02, -4.7140e-01, -1.6654e+00,  8.6159e-01,  4.2640e-01],
         [-1.0422e+00,  1.8856e+00, -1.0310e+00,  1.1749e+00, -8.5280e-01],
         [-1.7673e+00,  1.4142e+00,  8.7235e-01, -1.6448e+00,  8.9407e-08],
         [ 4.5314e-02, -9.4281e-01, -3.9653e-01,  8.6159e-01, -1.7056e+00],
         [-3.1720e-01,  1.7881e-07, -3.9653e-01, -7.0493e-01, -8.5280e-01],
         [ 1.1329e+00, -4.7140e-01,  1.5068e+00, -1.0182e+00,  1.2792e+00],
         [ 1.4954e+00, -9.4281e-01,  2.3791e-01,  8.6159e-01,  4.2640e-01],
         [ 4.0783e-01, -4.7140e-01,  8.7235e-01, -3.9163e-01,  1.2792e+00]],
        grad_fn=<NativeBatchNormBackward0>),
 tensor([[ 0.1655, -0.6621, -1.4897,  1.4069,  0.5793],
         [-0.9152,  1.0460, -0.9152,  1.3728, -0.5883],
         [-1.1844,  1.2541,  0.5574, -1.1844,  0.5574],
         [ 0.4835, -0.7252, -0.3223,  1.6922, -1.1282],
         [ 1.2247,  1.2247, -0.8165, -0.8165, -0.8165],
         [ 1.0408, -0.9608,  0.2402, -1.3611,  1.0408],
         [

3. Given a 4D tensor of shape (2, 3, 4, 5), create a mask that sets all elements in positions where the sum of indices is even to zero.

In [43]:
tsr_4d = torch.empty(2,3,4,5)

index0 = torch.arange(tsr_4d.shape[0]).view(-1, 1, 1, 1)
index1 = torch.arange(tsr_4d.shape[1]).view(1, -1, 1, 1)
index2 = torch.arange(tsr_4d.shape[2]).view(1, 1, -1, 1)
index3 = torch.arange(tsr_4d.shape[3]).view(1, 1, 1, -1)

sum_indices = index0 + index1 + index2 + index3     #broadcasting
sum_indices

tensor([[[[ 0,  1,  2,  3,  4],
          [ 1,  2,  3,  4,  5],
          [ 2,  3,  4,  5,  6],
          [ 3,  4,  5,  6,  7]],

         [[ 1,  2,  3,  4,  5],
          [ 2,  3,  4,  5,  6],
          [ 3,  4,  5,  6,  7],
          [ 4,  5,  6,  7,  8]],

         [[ 2,  3,  4,  5,  6],
          [ 3,  4,  5,  6,  7],
          [ 4,  5,  6,  7,  8],
          [ 5,  6,  7,  8,  9]]],


        [[[ 1,  2,  3,  4,  5],
          [ 2,  3,  4,  5,  6],
          [ 3,  4,  5,  6,  7],
          [ 4,  5,  6,  7,  8]],

         [[ 2,  3,  4,  5,  6],
          [ 3,  4,  5,  6,  7],
          [ 4,  5,  6,  7,  8],
          [ 5,  6,  7,  8,  9]],

         [[ 3,  4,  5,  6,  7],
          [ 4,  5,  6,  7,  8],
          [ 5,  6,  7,  8,  9],
          [ 6,  7,  8,  9, 10]]]])

In [34]:
mask = (sum_indices % 2 == 0)
mask

tensor([[[[ True, False,  True, False,  True],
          [False,  True, False,  True, False],
          [ True, False,  True, False,  True],
          [False,  True, False,  True, False]],

         [[False,  True, False,  True, False],
          [ True, False,  True, False,  True],
          [False,  True, False,  True, False],
          [ True, False,  True, False,  True]],

         [[ True, False,  True, False,  True],
          [False,  True, False,  True, False],
          [ True, False,  True, False,  True],
          [False,  True, False,  True, False]]],


        [[[False,  True, False,  True, False],
          [ True, False,  True, False,  True],
          [False,  True, False,  True, False],
          [ True, False,  True, False,  True]],

         [[ True, False,  True, False,  True],
          [False,  True, False,  True, False],
          [ True, False,  True, False,  True],
          [False,  True, False,  True, False]],

         [[False,  True, False,  True, False],
 

In [36]:
from torch.masked import masked_tensor
mt = masked_tensor(sum_indices.float(), mask = mask)
mt

/usr/local/lib/python3.10/dist-packages/torch/masked/maskedtensor/core.py:156: UserWarning: The PyTorch API of MaskedTensors is in prototype stage and will change in the near future. Please open a Github issue for features requests and see our documentation on the torch.masked module for further information about the project.
  warnings.warn(("The PyTorch API of MaskedTensors is in prototype stage "


MaskedTensor(
  [
    [
      [
        [  0.0000,       --,   2.0000,       --,   4.0000],
        [      --,   2.0000,       --,   4.0000,       --],
        [  2.0000,       --,   4.0000,       --,   6.0000],
        [      --,   4.0000,       --,   6.0000,       --]
      ],
      [
        [      --,   2.0000,       --,   4.0000,       --],
        [  2.0000,       --,   4.0000,       --,   6.0000],
        [      --,   4.0000,       --,   6.0000,       --],
        [  4.0000,       --,   6.0000,       --,   8.0000]
      ],
      [
        [  2.0000,       --,   4.0000,       --,   6.0000],
        [      --,   4.0000,       --,   6.0000,       --],
        [  4.0000,       --,   6.0000,       --,   8.0000],
        [      --,   6.0000,       --,   8.0000,       --]
      ]
    ],
    [
      [
        [      --,   2.0000,       --,   4.0000,       --],
        [  2.0000,       --,   4.0000,       --,   6.0000],
        [      --,   4.0000,       --,   6.0000,       --],
        

3. Given two tensors, one of shape `(3, 1, 4)` and another of shape `(1, 5, 1)`, compute their element-wise multiplication using broadcasting and then sum over specific axes to obtain a tensor of shape `(3, 5)`.

In [45]:
tnsr1 = torch.randint(2,6,(3,1,4))
tnsr2 = torch.randint(3,9,(1,5,1))

product = tnsr1 * tnsr2
product, product.shape

(tensor([[[12,  8, 16, 12],
          [ 9,  6, 12,  9],
          [18, 12, 24, 18],
          [18, 12, 24, 18],
          [12,  8, 16, 12]],
 
         [[16, 16,  8, 20],
          [12, 12,  6, 15],
          [24, 24, 12, 30],
          [24, 24, 12, 30],
          [16, 16,  8, 20]],
 
         [[12, 20, 16, 12],
          [ 9, 15, 12,  9],
          [18, 30, 24, 18],
          [18, 30, 24, 18],
          [12, 20, 16, 12]]]),
 torch.Size([3, 5, 4]))

In [47]:
sum = product.sum(dim=2)
sum, sum.shape

(tensor([[48, 36, 72, 72, 48],
         [60, 45, 90, 90, 60],
         [60, 45, 90, 90, 60]]),
 torch.Size([3, 5]))