<a href="https://colab.research.google.com/github/nagamukesh/NLP-SMP/blob/Sanstuti_Mishra/Copy_of_PyTorch_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  **PyTorch Practice Assignment**
**Name**: Sanstuti Mishra

**Roll Number**: 231ME247


## **Instructions:**

- Copy this Notebook to your own Drive! You cannot directly modify it.
- Please show the output of the cells, in case of some operation. You can specify your own **non-trivial** test-case. Also, try and make your snippets into functions to organize your logic.
- You can use any number of cells for a question, you are not restricted to just 1 cell!
- **No using ChatGPT for this assignment**: we highly recommend using the [Pytorch Docs](https://pytorch.org/docs/stable/index.html) as your start reference, as well as the vast internet however. You can also contact any of your mentors for some hints/help!
- You can work on this assignment in Google Colab or on Your Local Machine!

### **Build Up Your Understanding**

1. Write a PyTorch snippet to test whether none of the elements of a given tensor are zero.

In [ ]:
import torch

def nonzero_elements(tensor):
    return len(torch.nonzero(tensor)) > 0

# Example usage:
tensor = torch.tensor([1, 2, 0, 3, 0])
print(nonzero_elements(tensor))        #Output:True

True


2. Write a PyTorch snippet to test element-wise for NaN of a given tensor.

In [ ]:
import torch

def nan_elements(tensor):
    return torch.isnan(tensor).any()

# Example usage:
tensor = torch.tensor([1.0, 2.0, float('nan'), 3.0])
print(nan_elements(tensor))       #Output:tensor(True)

tensor(True)


3. Write a PyTorch snippet to test whether two tensors are element-wise equal within a tolerance.

In [ ]:
import torch

def equal_or_not(tensor1, tensor2, tolerance):
    return torch.allclose(tensor1, tensor2, tolerance)

# Example usage:
tensor1 = torch.tensor([1.0, 2.0, 3.0])
tensor2 = torch.tensor([1.01, 2.02, 3.03])
tolerance = 1e-2

print(equal_or_not(tensor1, tensor2, tolerance)) #Output: True

True


4. Write a PyTorch snippet to create a tensor of 10 zeros, 10 ones, and 10 fives stacked on top of each other (try & accomplish everything using nested function calls).

5. Write a PyTorch snippet to generate a random number between 0 and 1.

In [ ]:
import torch

def random_number():
    return torch.rand(1).item()

# Example usage:
print(random_number())

0.38988208770751953


6. Write a PyTorch snippet to generate a tensor of 15 random numbers from a standard normal distribution.

In [ ]:
import torch

def random_tensor():
    return torch.randn(15)

# Example usage:
print(random_tensor())

tensor([ 0.7600,  0.5972, -0.1885, -0.0633,  1.1972,  1.6491, -1.7098, -0.9246,
         1.2610, -1.2940,  0.8311, -0.1468, -1.7141,  0.5369,  0.1142])


7. Write a Pytorch snippet to create a tensor of length 10 with values evenly distributed between 5 and 50.

In [ ]:
import torch

def even_tensor():
    return torch.linspace(5, 50, 10)

# Example usage:
print(even_tensor())
#Output: tensor([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

tensor([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])


8. Write a Pyorch program to create a tensor with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15.

In [58]:
import torch

tensor = torch.arange(21)
tensor[9:16] *= -1

print(tensor)


tensor([  0,   1,   2,   3,   4,   5,   6,   7,   8,  -9, -10, -11, -12, -13,
        -14, -15,  16,  17,  18,  19,  20])


9. Write a PyTorch snippet to create a 3x4 2-tensor filled with values from 10 to 21. Same but 12 to 24.

In [65]:
import torch

def create_tensor(lower_range, higher_range):
    new_tensor = torch.arange(lower_range, (higher_range+1)).reshape(3, 4)
    return new_tensor

# Example usage:
print(create_tensor(10, 21))
print(create_tensor(12, 23))

tensor([[10, 11, 12, 13],
        [14, 15, 16, 17],
        [18, 19, 20, 21]])
tensor([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])


10. Write a PyTorch snippet to create a 10x10 2-tensor, in which the elements on the borders will be equal to 1, and inside 0.

In [68]:
import torch

tensor = torch.zeros(10, 10)

tensor[0, :] = 1
tensor[:, 0] = 1
tensor[-1, :] = 1
tensor[:, -1] = 1

print(tensor)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])


11. Write a PyTorch snippet to create a 5x5 zero 2-tensor with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [76]:
import torch

tensor = torch.zeros(5, 5)

values = torch.tensor([1, 2, 3, 4, 5])
tensor = torch.diag_embed(values, offset=0, dim1=-2, dim2=-1)

print(tensor)

tensor([[1, 0, 0, 0, 0],
        [0, 2, 0, 0, 0],
        [0, 0, 3, 0, 0],
        [0, 0, 0, 4, 0],
        [0, 0, 0, 0, 5]])


12. Write a PyTorch snippet to save a given tensor as a binary to a given path.

In [78]:
import torch

def save_tensor(tensor, path):
    torch.save(tensor, path)

# Example usage:
tensor = torch.tensor([[1, 2, 3],
                       [4, 5, 6]])

path = 'tensor.pt'
save_tensor(tensor, path)

13. Write a NumPy program to create a two-dimensional array of a specified format.

In [83]:
import numpy as np

numpy_array = np.full((2, 2), 2)
print(numpy_array)

[[2 2]
 [2 2]]


14. Write a PyTorch snippet to create a 2-tensor with shape (8,5) of random numbers. Select these random numbers (to create the tensor) from a normal distribution (200,7) (mean, variance).

In [92]:
import torch

mean = 200
variance = 7
normal_distribution = torch.normal(mean=torch.tensor(mean), std=torch.tensor(variance))
tensor_shape = (8, 5)
random_tensor = normal_distribution.view(*tensor_shape)

print(random_tensor)


RuntimeError: "normal_kernel_cpu" not implemented for 'Long'

15. Write a PyTorch snippet to generate a uniform, non-uniform random sample from a given vector with and without replacement (do all 4 combinations possible).

16. Write a Pyorch snippet to create an nxn(input to function) tensor with random values. Create an array from the said array swapping first and last rows.

In [99]:
import torch

def random_tensor(n):
    return torch.rand((n, n))

# Example usage
n = 5
new_tensor = random_tensor(n)
print(new_tensor)

def swap(tensor):
    tensor[0], tensor[-1] = tensor[-1], tensor[0]
    return tensor

swap(new_tensor)
print(new_tensor)


tensor([[0.9938, 0.4837, 0.1191, 0.6261, 0.2492],
        [0.1238, 0.8463, 0.8669, 0.9866, 0.7566],
        [0.7651, 0.6654, 0.1065, 0.1313, 0.7377],
        [0.9805, 0.9058, 0.1119, 0.3761, 0.2116],
        [0.2598, 0.1797, 0.0566, 0.7213, 0.0283]])
tensor([[0.2598, 0.1797, 0.0566, 0.7213, 0.0283],
        [0.1238, 0.8463, 0.8669, 0.9866, 0.7566],
        [0.7651, 0.6654, 0.1065, 0.1313, 0.7377],
        [0.9805, 0.9058, 0.1119, 0.3761, 0.2116],
        [0.2598, 0.1797, 0.0566, 0.7213, 0.0283]])


17. Write a PyTorch snippet to sort a given tensor (1D or 2D) in ascending order.

In [88]:
import torch

def sort_tensor(input_tensor):
    sorted_tensor, _ = torch.sort(input_tensor)
    return sorted_tensor

# Example usage:
tensor = torch.tensor([5, 3, 7, 1, 4])
print(sort_tensor(tensor))

tensor([1, 3, 4, 5, 7])


18. Write a PyTorch snippet to create a tensor of equal shape and data type for a given tensor (any dimensional)

In [57]:
import torch

def equal_tensor(given_tensor):
    new_tensor = torch.empty_like(given_tensor)
    return new_tensor

# Example usage:
tensor = torch.tensor([[1, 2, 3],
                       [4, 5, 6]])
print(equal_tensor(tensor))

tensor([[7309453675965983778, 8315168162784306286, 8367752027310484831],
        [7954801838398993778, 2459029315949324647, 3544390503882568245]])


19. Write a PyTorch snippet to create an 8x8 matrix and fill it with a checkerboard pattern.
Checkerboard pattern:
```py
[[0 1 0 1 0 1 0 1]
..........
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]]
```

In [52]:
import torch

matrix = torch.zeros(8, 8, dtype=torch.int32)

matrix[::2, ::2] = 1
matrix[1::2, 1::2] = 1

print(matrix)

tensor([[1, 0, 1, 0, 1, 0, 1, 0],
        [0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0],
        [0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0],
        [0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0],
        [0, 1, 0, 1, 0, 1, 0, 1]], dtype=torch.int32)


20. Write a Pytorch snippet to convert Centigrade to Fahrenheit and vice versa (controlled by a parameter). Ensure you operation is vectorized i.e **no explicit looping**

Sample Array: `[0, 12, 45.21, 34, 99.91]`

In [49]:
import torch

def celsius_to_fahrenheit(celsius_temp):
    return (celsius_temp * 9/5) + 32

def fahrenheit_to_celsius(fahrenheit_temp):
    return (fahrenheit_temp - 32) * 5/9

# Example usage:
celsius_value = torch.tensor([0, 12, 45.21, 34, 99.91])
fahrenheit_value = celsius_to_fahrenheit(celsius_value)
celsius_again = fahrenheit_to_celsius(fahrenheit_value)

print(fahrenheit_value)
print(celsius_again)


tensor([ 32.0000,  53.6000, 113.3780,  93.2000, 211.8380])
tensor([ 0.0000, 12.0000, 45.2100, 34.0000, 99.9100])


21. Write a PyTorch snippet to get the values of the elements that are bigger than a given *number* in a given tensor.

Original tensor:
```
[[ 0 10 20]
[20 30 40]]
```
Number: 10

Values bigger than 10 = `[20 20 30 40]`

In [46]:
import torch

def greater_elements(tensor, number):
    return tensor[tensor > number]

# Example usage:
tensor = torch.tensor([[0, 10, 20],
                      [20, 30, 40]])
number = 10
values = greater_elements(tensor, number)
print(values)

tensor([20, 20, 30, 40])


22. Write a PyTorch snippet to create another shape from an array without changing its data. After carrying out the operation, change the data in one place and see if the other tensor changes

Reshape 3x2:
```
[[1 2]
[3 4]
[5 6]]
```
Reshape 2x3:
```
[[1 2 3]
[4 5 6]]
```

In [43]:
import torch

def reshape_tensor(original_tensor, new_shape):
    reshaped_tensor = original_tensor.reshape(*new_shape)
    return reshaped_tensor

# Example usage:
original_tensor = torch.tensor([1, 2, 3, 4, 5, 6])
new_shape = (3, 2)
reshaped_tensor = reshape_tensor(original_tensor, new_shape)
print(reshaped_tensor)

# Changing data in reshaped tensor
reshaped_tensor[0, 1] = 99

# Checking if original tensor also changes
print(original_tensor)
print(reshaped_tensor)
# Output: It changes the data in original tensor as well

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([ 1, 99,  3,  4,  5,  6])
tensor([[ 1, 99],
        [ 3,  4],
        [ 5,  6]])


23. Write a PyTorch snipppet to change an tensor's data type.
```
[[ 2 4 6]
[ 6 8 10]]
```
Data type of the array x is: `int32`

New Type: `float64`
```
[[ 2. 4. 6.]
[ 6. 8. 10.]]
```

In [37]:
import torch

def change_datatype(tensor, new_datatype):
    return tensor.to(new_datatype)

#Example usage
tensor = torch.tensor([[2, 4, 6],
                       [6, 8, 10]])
print(tensor.dtype)

new_datatype = torch.float64
new_tensor = change_datatype(tensor, new_datatype)
print(new_tensor)

torch.int64
tensor([[ 2.,  4.,  6.],
        [ 6.,  8., 10.]], dtype=torch.float64)


24. Write a PyTorch snippet to insert a new axis within a 2-tensor, based on a **parameter**.

Ex: If 2-tensor has shape (3, 4).

Then, new shape can be (1, 3, 4), (3, 1, 4), or (3, 4, 1) depending on....

In [5]:
import torch

def insert_axis(tensor, axis):
    return tensor.unsqueeze(axis)

# Example usage:
a = torch.zeros(3, 4)
result = insert_axis(a, 1)
print(result.shape)  # Output: torch.Size([3, 1, 4])

torch.Size([3, 1, 4])


25. Write a PyTorch snippet to stack tensors based on a parameter, **axis**.
First discover what this means with 2-tensors, then extend it to 3-tensors. Print your findings.

Sample Output:

Original tensors:

Tensor-1
```
[[0 1 2]
[3 4 5]
[6 7 8]]
```
Tensor-2
```
[[ 0 3 6]
[ 9 12 15]
[18 21 24]]
```
Stack tensors such that axis=1:
```
[[ 0 1 2 0 3 6]
[ 3 4 5 9 12 15]
[ 6 7 8 18 21 24]]
```

In [20]:
def stack_tensors(tensor1, tensor2, axis):
    return torch.cat((tensor1, tensor2), axis)

# Example usage with 2-tensors:
a = torch.tensor([[0, 1, 2],
                  [3, 4, 5],
                  [6, 7, 8]])

b = torch.tensor([[ 0,  3,  6],
                  [ 9, 12, 15],
                  [18, 21, 24]])
stacked_tensor = stack_tensors(a, b, axis=1)
print(stacked_tensor)

# Example usage for 3-tensors
a = torch.tensor([[[0, 1, 2],
                   [3, 4, 5],
                   [6, 7, 8]],

                  [[9, 10, 11],
                   [12, 13, 14],
                   [15, 16, 17]]])

b = torch.tensor([[[18, 19, 20],
                   [21, 22, 23],
                   [24, 25, 26]],

                  [[27, 28, 29],
                   [30, 31, 32],
                   [33, 34, 35]]])
stacked_tensor = stack_tensors(a, b, axis=1)
print(stacked_tensor)

tensor([[ 0,  1,  2,  0,  3,  6],
        [ 3,  4,  5,  9, 12, 15],
        [ 6,  7,  8, 18, 21, 24]])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17],
         [27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]]])


26. Write a PyTorch snippet to extract the **m**th to **n**th elements of the **m**th to **n**th rows from the **m**th to nth elemnts of given 3-tensor, of shape `(p, q, r)` where m, n < p, q, r.

Take a 3-tensor of (say) size `(5,6,7)` and `(m, n)` = `(4, 5)` as a test case!

In [ ]:
import torch

def extract_tensor(tensor, m, n):
    return tensor[m:n+1, m:n+1, m:n+1]

# Example usage:
tensor_shape = (5, 6, 7)
m, n = 4, 5
print(extract_tensor(tensor, m, n))

tensor([[[1.0366, 0.1832],
         [0.7528, 1.8704]]])


### **Test your Understanding**

1. Given a 3D tensor of shape `(a, b, c)`*italicised text*, permute its axes to obtain tensors of all other shape combinations (i.e 5).

In [33]:
import torch

def permute_axes(tensor):
    permutations = [(0, 1, 2),
                    (0, 2, 1),
                    (1, 0, 2),
                    (1, 2, 0),
                    (2, 0, 1),
                    (2, 1, 0)]
    return [tensor.permute(i) for i in permutations]

# Example usage:
original_tensor = torch.randn(2, 4 ,5)
print(permute_axes(original_tensor))

[tensor([[[ 0.6790, -1.4020,  0.5383,  0.0896, -0.2544],
         [ 0.1654,  1.2860,  0.6851,  0.3731, -0.3579],
         [-1.0351, -0.3293,  1.4889,  1.5361,  0.3572],
         [-0.7358,  2.2874, -0.2308,  0.0544, -0.8444]],

        [[ 0.6092, -0.6432,  0.4797, -1.1051, -0.7015],
         [-0.2104,  0.3929,  0.6973, -2.8372,  0.8182],
         [ 1.1326,  2.6702,  1.2828, -0.2966, -1.3022],
         [-0.0385,  0.1172, -0.5642,  0.1300,  0.9224]]]), tensor([[[ 0.6790,  0.1654, -1.0351, -0.7358],
         [-1.4020,  1.2860, -0.3293,  2.2874],
         [ 0.5383,  0.6851,  1.4889, -0.2308],
         [ 0.0896,  0.3731,  1.5361,  0.0544],
         [-0.2544, -0.3579,  0.3572, -0.8444]],

        [[ 0.6092, -0.2104,  1.1326, -0.0385],
         [-0.6432,  0.3929,  2.6702,  0.1172],
         [ 0.4797,  0.6973,  1.2828, -0.5642],
         [-1.1051, -2.8372, -0.2966,  0.1300],
         [-0.7015,  0.8182, -1.3022,  0.9224]]]), tensor([[[ 0.6790, -1.4020,  0.5383,  0.0896, -0.2544],
         [ 0.60

2. Given a 4D tensor of shape `(2, 3, 4, 5)`, transpose it to obtain a tensor of shape `(2, 4, 5, 3)`. Also explore what is_contiguous() means...

In [ ]:
import torch

tensor = torch.randn(2, 3, 4, 5)
transposed_tensor = tensor.transpose(2, 3)
transposed_tensor = transposed_tensor.transpose(1, 3)

print(transposed_tensor.shape)
print(transposed_tensor)

torch.Size([2, 4, 5, 3])
tensor([[[[ 0.7068, -0.8304, -0.0231],
          [ 0.8708, -0.6613, -1.0567],
          [ 0.7315, -1.0097,  0.4622],
          [ 1.1516, -0.2933,  0.6300],
          [-1.0263, -0.3773, -0.4838]],

         [[-0.7692,  0.4892, -0.8640],
          [-1.2688,  1.1114,  0.9330],
          [ 0.5496,  0.1260, -1.0150],
          [-0.0653,  0.3990,  0.0253],
          [-0.2764, -1.4378, -1.4530]],

         [[-0.2507, -0.3169,  1.8980],
          [ 0.2121,  0.0205,  0.5908],
          [-1.5223, -0.6931,  1.0523],
          [ 0.6414, -1.2129,  0.9456],
          [ 1.7891,  0.6697,  0.5333]],

         [[-1.7217, -1.5795, -1.4623],
          [ 0.3157, -1.4710, -0.6845],
          [ 0.0264, -1.6196, -0.3152],
          [ 0.9831,  0.9202,  0.6696],
          [-0.1942,  0.9141, -0.0047]]],


        [[[-0.5461,  0.1659,  0.5767],
          [-0.5637,  0.1548, -1.5013],
          [-1.6061,  0.2966, -0.9212],
          [ 1.1221,  0.4159, -0.2510],
          [-0.2127, -0.0940, 

3. Given two tensors, one of shape (n, 1) and another of shape (m, ), perform an element-wise addition **manually**. Then, test out what direct addition does and compare your results!

4. Given a 3D tensor of shape `(4, 4, 4)`, extract a sub-tensor of shape `(2, 2, 2)` starting from the element at index `(1, 1, 1)`**bold text**.

In [24]:
import torch

tensor = torch.arange(64).reshape(4, 4, 4)
sub_tensor = tensor[1:3, 1:3, 1:3]
print(tensor)
print(sub_tensor)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15]],

        [[16, 17, 18, 19],
         [20, 21, 22, 23],
         [24, 25, 26, 27],
         [28, 29, 30, 31]],

        [[32, 33, 34, 35],
         [36, 37, 38, 39],
         [40, 41, 42, 43],
         [44, 45, 46, 47]],

        [[48, 49, 50, 51],
         [52, 53, 54, 55],
         [56, 57, 58, 59],
         [60, 61, 62, 63]]])
tensor([[[21, 22],
         [25, 26]],

        [[37, 38],
         [41, 42]]])


5. Given a 2-tensor of arbitrary shape, rotate it 90 degrees anticlockwise.



In [ ]:
import torch

def rotate_tensor(x):
    rotated_x = torch.rot90(x, k=1, dims=[0, 1])
    return rotated_x

# Example usage:
tensor = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])
print(rotate_tensor(tensor))


tensor([[3, 6, 9],
        [2, 5, 8],
        [1, 4, 7]])


### **EVEN I HAD TO THINK...**

1. Implement a custom operation that computes the **element-wise** **sine** of a tensor *and* its **gradient** using torch.autograd.Function.
- You need to implement both the forward() and backward() methods.
- For an example, look no further than the [PyTorch docs](https://pytorch.org/docs/stable/autograd.html#function)!
- Test it out on a matrix of arbitrary size!

2. One of the most important aspects of improving model performance ins normalization. Implement a custom NN normalization layer that performs either a **batch** or **layer** normalization (based on a **dim** parameter)and integrate it into a simple feedforward neural network.
- Note that you dont need to implement any backward() here, for simplicity.
- Consider your input tensor to the neural network as of shape (m, n) where m is num of examples, n is num of features.
- Which value of **dim** leads to batch and layer normalization?

3. Given a 4D tensor of shape (2, 3, 4, 5), create a mask that sets all elements in positions where the sum of indices is even to zero.

3. Given two tensors, one of shape `(3, 1, 4)` and another of shape `(1, 5, 1)`, compute their element-wise multiplication using broadcasting and then sum over specific axes to obtain a tensor of shape `(3, 5)`.

In [29]:
import torch

tensor1 = torch.randn(3, 1, 4)
tensor2 = torch.randn(1, 5, 1)

result = tensor1 * tensor2
sum = result.sum(dim=2)

print(sum.shape)    # output: (3, 5)


torch.Size([3, 5])
