<a href="https://colab.research.google.com/github/nagamukesh/NLP-SMP/blob/Dinesh_Manideep/DineshManideep_week1_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  **PyTorch Practice Assignment**
**Name**: Paluvadi Dinesh Manideep

**Roll Number**: 231IT047

## **Instructions:**

- Copy this Notebook to your own Drive! You cannot directly modify it.
- Please show the output of the cells, in case of some operation. You can specify your own **non-trivial** test-case. Also, try and make your snippets into functions to organize your logic.
- You can use any number of cells for a question, you are not restricted to just 1 cell!
- **No using ChatGPT for this assignment**: we highly recommend using the [Pytorch Docs](https://pytorch.org/docs/stable/index.html) as your start reference, as well as the vast internet however. You can also contact any of your mentors for some hints/help!
- You can work on this assignment in Google Colab or on Your Local Machine!

In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np

### **Build Up Your Understanding**

1. Write a PyTorch snippet to test whether none of the elements of a given tensor are zero.

In [ ]:
p=torch.tensor([[2,3,45],[3,7,7]])

if p.all():
  print("None of the elements are equal to zero")
else:
  print("some elements of the tensor are equal to zero")

None of the elements are equal to zero


2. Write a PyTorch snippet to test element-wise for NaN of a given tensor.

In [ ]:
ten=torch.tensor([[1,2,3],[7,float('nan'),78]])
ten.isnan()

tensor([[False, False, False],
        [False,  True, False]])

3. Write a PyTorch snippet to test whether two tensors are element-wise equal within a tolerance.

In [ ]:
a=torch.rand(3,5)
b=torch.rand(3,5)
print(torch.eq(a,b))
if(torch.all(torch.eq(a,b))):
  print("The two tensors are equal")
else:
  print("the given tensors are not equal")

tensor([[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]])
the given tensors are not equal


4. Write a PyTorch snippet to create a tensor of 10 zeros, 10 ones, and 10 fives stacked on top of each other (try & accomplish everything using nested function calls).

In [ ]:
a = torch.cat((
    torch.zeros(10).unsqueeze(0),
    torch.ones(10).unsqueeze(0),
    torch.full((1, 10), 5)
), dim=0)

print(a)

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])


5. Write a PyTorch snippet to generate a random number between 0 and 1.

In [ ]:
torch.rand(1)

tensor([0.6172])

6. Write a PyTorch snippet to generate a tensor of 15 random numbers from a standard normal distribution.

In [ ]:
torch.rand(15)

tensor([0.0344, 0.5435, 0.3924, 0.1936, 0.8663, 0.2008, 0.8751, 0.5446, 0.4840,
        0.0236, 0.7424, 0.7894, 0.0317, 0.4199, 0.1954])

7. Write a Pytorch snippet to create a tensor of length 10 with values evenly distributed between 5 and 50.

In [ ]:
torch.arange(5,55,5)

tensor([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

8. Write a Pyorch program to create a tensor with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15.

In [ ]:
a=torch.arange(0,21)
a[9:16]=-a[9:16]
print(a)

tensor([  0,   1,   2,   3,   4,   5,   6,   7,   8,  -9, -10, -11, -12, -13,
        -14, -15,  16,  17,  18,  19,  20])


9. Write a PyTorch snippet to create a 3x4 2-tensor filled with values from 10 to 21. Same but 12 to 24.

In [ ]:
b=torch.arange(10,22,1)
b=b.reshape(3,4)
c=torch.arange(12,24,1)
c=c.reshape(3,4)
print(b)
print(c)

tensor([[10, 11, 12, 13],
        [14, 15, 16, 17],
        [18, 19, 20, 21]])
tensor([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])


10. Write a PyTorch snippet to create a 10x10 2-tensor, in which the elements on the borders will be equal to 1, and inside 0.

In [ ]:
z=torch.zeros(10,10)
z[0,:]=1
z[9,:]=1
z[:,0]=1
z[:,9]=1
print(z[0,0])
print(z)

tensor(1.)
tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])


11. Write a PyTorch snippet to create a 5x5 zero 2-tensor with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [ ]:
p=torch.zeros(5,5)

torch.diagonal(p).copy_(torch.arange(1,6))
print(p)

tensor([[1., 0., 0., 0., 0.],
        [0., 2., 0., 0., 0.],
        [0., 0., 3., 0., 0.],
        [0., 0., 0., 4., 0.],
        [0., 0., 0., 0., 5.]])


12. Write a PyTorch snippet to save a given tensor as a binary to a given path.

In [ ]:
path="data"
torch.save(p,path)

13. Write a NumPy program to create a two-dimensional array of a specified format.

In [ ]:
y=np.array([3,5])
print(y)

[3 5]


14. Write a PyTorch snippet to create a 2-tensor with shape (8,5) of random numbers. Select random numbers from a normal distribution (200,7) (mean, variance).

In [ ]:

mean = 200
var = 7
std_dev = var ** 0.5
t = torch.normal(mean, std_dev, size=(8, 5))
print(t)

tensor([[198.5609, 200.5960, 193.6224, 202.4721, 197.2944],
        [199.3685, 203.4498, 197.2782, 198.2697, 199.7448],
        [197.5080, 202.1228, 201.8537, 196.0445, 195.2853],
        [203.2751, 200.4396, 200.1591, 200.1295, 202.4474],
        [195.8905, 200.9134, 197.5169, 206.1516, 198.2888],
        [199.8424, 200.3794, 197.2105, 199.4647, 199.1599],
        [197.2578, 197.1456, 198.2422, 199.1407, 199.2640],
        [198.4792, 202.1242, 200.7878, 198.8065, 195.0144]])


15. Write a PyTorch snippet to generate a uniform, non-uniform random sample from a given vector with and without replacement (do all 4 combinations possible).

In [ ]:

vector = torch.tensor([2,4,6,0,3,9])
uniform_weights = torch.ones_like(vector, dtype=torch.float)
non_uniform_weights = torch.tensor([1, 2, 3, 4, 5], dtype=torch.float)
num_samples = 3
#tensors
uniform_with_replacement = torch.multinomial(uniform_weights, num_samples, replacement=True)
print("Uniform with replacement:", vector[uniform_with_replacement])
uniform_without_replacement = torch.multinomial(uniform_weights, num_samples, replacement=False)
print("Uniform without replacement:", vector[uniform_without_replacement])
non_uniform_with_replacement = torch.multinomial(non_uniform_weights, num_samples, replacement=True)
print("Non-uniform with replacement:", vector[non_uniform_with_replacement])
non_uniform_without_replacement = torch.multinomial(non_uniform_weights, num_samples, replacement=False)
print("Non-uniform without replacement:", vector[non_uniform_without_replacement])

Uniform with replacement: tensor([9, 2, 9])
Uniform without replacement: tensor([2, 9, 3])
Non-uniform with replacement: tensor([3, 3, 2])
Non-uniform without replacement: tensor([4, 3, 6])


16. Write a Pyorch snippet to create an nxn(input to function) tensor with random values. Create an array from the said array swapping first and last rows.

In [ ]:
n=5
a=torch.rand(n,n)
a[[0,n-1]]=a[[n-1,0]]
print(a)

tensor([[0.4741, 0.2700, 0.9948, 0.7020, 0.4998],
        [0.6241, 0.3354, 0.7488, 0.0605, 0.6945],
        [0.5511, 0.6207, 0.9581, 0.8376, 0.9498],
        [0.7769, 0.8441, 0.2430, 0.4541, 0.5474],
        [0.1435, 0.6053, 0.0908, 0.0753, 0.6932]])


17. Write a PyTorch snippet to sort a given tensor (1D or 2D) in ascending order.

In [ ]:
a=torch.rand(8)
print("unsorted 1D tensor")
print(a)
a=torch.sort(a)
print("sorted 1D tensor")
print(a)
a=torch.rand(3,5)
print("unsorted 2D tensor")
print(a)
a=torch.sort(a)
print("sorted 2D tensor")
print(a)

unsorted 1D tensor
tensor([0.4550, 0.6257, 0.0476, 0.9717, 0.7690, 0.1599, 0.1633, 0.5440])
sorted 1D tensor
torch.return_types.sort(
values=tensor([0.0476, 0.1599, 0.1633, 0.4550, 0.5440, 0.6257, 0.7690, 0.9717]),
indices=tensor([2, 5, 6, 0, 7, 1, 4, 3]))
unsorted 2D tensor
tensor([[0.2103, 0.3666, 0.0409, 0.0986, 0.3325],
        [0.3371, 0.0080, 0.6915, 0.0625, 0.6707],
        [0.0167, 0.5502, 0.3582, 0.4404, 0.6113]])
sorted 2D tensor
torch.return_types.sort(
values=tensor([[0.0409, 0.0986, 0.2103, 0.3325, 0.3666],
        [0.0080, 0.0625, 0.3371, 0.6707, 0.6915],
        [0.0167, 0.3582, 0.4404, 0.5502, 0.6113]]),
indices=tensor([[2, 3, 0, 4, 1],
        [1, 3, 0, 4, 2],
        [0, 2, 3, 1, 4]]))


18. Write a PyTorch snippet to create a tensor of equal shape and data type for a given tensor (any dimensional)

In [ ]:
a=torch.rand(5,5)
p=torch.zeros_like(a)
print(p)


tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


19. Write a PyTorch snippet to create an 8x8 matrix and fill it with a checkerboard pattern.
Checkerboard pattern:
```py
[[0 1 0 1 0 1 0 1]
..........
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]]
```

In [ ]:
a=torch.zeros(8,8,dtype=torch.int64)
print(a)
for i in range(8):
  for j in range(8):
    if((i+j)%2==0):
      a[i,j]=0
    else:
      a[i,j]=1

print(a)

tensor([[0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0]])
tensor([[0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0],
        [0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0],
        [0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0],
        [0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0]])


20. Write a Pytorch snippet to convert Centigrade to Fahrenheit and vice versa (controlled by a parameter). Ensure you operation is vectorized i.e **no explicit looping**

Sample Array: `[0, 12, 45.21, 34, 99.91]`

In [ ]:
a=[0, 12, 45.21, 34, 99.91]
a=torch.tensor(a)
a=a*9/5
a=a+32
print(a)

tensor([ 32.0000,  53.6000, 113.3780,  93.2000, 211.8380])


21. Write a PyTorch snippet to get the values of the elements that are bigger than a given *number* in a given tensor.

Original tensor:
```
[[ 0 10 20]
[20 30 40]]
```
Number: 10

Values bigger than 10 = `[20 20 30 40]`

In [ ]:
k=[[ 0, 10, 20],
[20, 30 ,40]]
k=torch.tensor(k)
ans=k[k>10]
print(ans)

tensor([20, 20, 30, 40])


22. Write a PyTorch snippet to create another shape from an array without changing its data. After carrying out the operation, change the data in one place and see if the other tensor changes

Reshape 3x2:
```
[[1 2]
[3 4]
[5 6]]
```
Reshape 2x3:
```
[[1 2 3]
[4 5 6]]
```

In [ ]:
a=[[1, 2],
[3, 4],
[5, 6]]
a=torch.tensor(a)
z=a.reshape(2,3)
print("before change")
print(z)
print(a)

z[0,0]=9
print("after change")
print(z)
print(a)

#the original tensor changes with change in new tensor

before change
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2],
        [3, 4],
        [5, 6]])
after change
tensor([[9, 2, 3],
        [4, 5, 6]])
tensor([[9, 2],
        [3, 4],
        [5, 6]])


23. Write a PyTorch snipppet to change an tensor's data type.
```
[[ 2 4 6]
[ 6 8 10]]
```
Data type of the array x is: `int32`

New Type: `float64`
```
[[ 2. 4. 6.]
[ 6. 8. 10.]]
```

In [4]:
k=[[ 2, 4, 6],
[ 6 ,8 ,10]]
k=torch.tensor(k,dtype=torch.int32)
print(k.dtype)
k=k.to(torch.float32)
print(k.dtype)


torch.int32
torch.float32


24. Write a PyTorch snippet to insert a new axis within a 2-tensor, based on a **parameter**.

Ex: If 2-tensor has shape (3, 4).

Then, new shape can be (1, 3, 4), (3, 1, 4), or (3, 4, 1) depending on....

In [ ]:
q=torch.rand(3,5)
print(q)
print(q.size())
z=torch.unsqueeze(q,0)
print(z)
print(z.size())
z=torch.unsqueeze(q,2)
print(z)
print(z.size())

tensor([[0.7981, 0.3776, 0.0074, 0.9615, 0.8834],
        [0.8521, 0.6848, 0.5445, 0.9314, 0.3998],
        [0.9037, 0.1409, 0.4357, 0.5268, 0.0185]])
torch.Size([3, 5])
tensor([[[0.7981, 0.3776, 0.0074, 0.9615, 0.8834],
         [0.8521, 0.6848, 0.5445, 0.9314, 0.3998],
         [0.9037, 0.1409, 0.4357, 0.5268, 0.0185]]])
torch.Size([1, 3, 5])
tensor([[[0.7981],
         [0.3776],
         [0.0074],
         [0.9615],
         [0.8834]],

        [[0.8521],
         [0.6848],
         [0.5445],
         [0.9314],
         [0.3998]],

        [[0.9037],
         [0.1409],
         [0.4357],
         [0.5268],
         [0.0185]]])
torch.Size([3, 5, 1])


25. Write a PyTorch snippet to stack tensors based on a parameter, **axis**.
First discover what this means with 2-tensors, then extend it to 3-tensors. Print your findings.

Sample Output:

Original tensors:

Tensor-1
```
[[0 1 2]
[3 4 5]
[6 7 8]]
```
Tensor-2
```
[[ 0 3 6]
[ 9 12 15]
[18 21 24]]
```
Stack tensors such that axis=1:
```
[[ 0 1 2 0 3 6]
[ 3 4 5 9 12 15]
[ 6 7 8 18 21 24]]
```

In [ ]:
ten_1=[[0, 1, 2],
[3, 4, 5],
[6, 7, 8]]
ten_1=torch.tensor(ten_1)
ten_2=[[ 0, 3, 6],
[ 9, 12, 15],
[18, 21, 24]]
ten_2=torch.tensor(ten_2)

axis=1

ans=torch.cat((ten_1,ten_2),axis)
print(ans)

ten_3=[[ 0, 3, 6],
[ 9, 12, 15],
[18, 21, 24]]
ten_3=torch.tensor(ten_3)

a=torch.cat((ten_1,ten_2,ten_3),axis)
print(a)


print("with three tensors it works similar to 2 tensor")

tensor([[ 0,  1,  2,  0,  3,  6],
        [ 3,  4,  5,  9, 12, 15],
        [ 6,  7,  8, 18, 21, 24]])
tensor([[ 0,  1,  2,  0,  3,  6,  0,  3,  6],
        [ 3,  4,  5,  9, 12, 15,  9, 12, 15],
        [ 6,  7,  8, 18, 21, 24, 18, 21, 24]])
with three tensors it works similar to 2 tensor


26. Write a PyTorch snippet to extract the **m**th to **n**th elements of the **m**th to **n**th rows from the **m**th to nth elemnts of given 3-tensor, of shape `(p, q, r)` where m, n < p, q, r.

Take a 3-tensor of (say) size `(5,6,7)` and `(m, n)` = `(4, 5)` as a test case!

In [ ]:
b=torch.rand(5,6,7)
m=4
n=5
print(b)
print(b[m,n,:])

tensor([[[0.0360, 0.8920, 0.1085, 0.4015, 0.2461, 0.6903, 0.2101],
         [0.0806, 0.8759, 0.1553, 0.3884, 0.3090, 0.5088, 0.8685],
         [0.2747, 0.1344, 0.5189, 0.2371, 0.7033, 0.9598, 0.3147],
         [0.6057, 0.9433, 0.7336, 0.3373, 0.4931, 0.5230, 0.0411],
         [0.3939, 0.4364, 0.5442, 0.7958, 0.6359, 0.9710, 0.9965],
         [0.9073, 0.9595, 0.3512, 0.9649, 0.4584, 0.3081, 0.5579]],

        [[0.5222, 0.2245, 0.8617, 0.2906, 0.2356, 0.1070, 0.1478],
         [0.1570, 0.9005, 0.9582, 0.7584, 0.9258, 0.7955, 0.6319],
         [0.4850, 0.4500, 0.3121, 0.9610, 0.7005, 0.7664, 0.6215],
         [0.2001, 0.2299, 0.9773, 0.0709, 0.8678, 0.2659, 0.1375],
         [0.1077, 0.8514, 0.5896, 0.8052, 0.3690, 0.1435, 0.8500],
         [0.3255, 0.9639, 0.4361, 0.2128, 0.2984, 0.3988, 0.8207]],

        [[0.6599, 0.9686, 0.0746, 0.3541, 0.7159, 0.0272, 0.4505],
         [0.7939, 0.1535, 0.9776, 0.7907, 0.5374, 0.6902, 0.7741],
         [0.6266, 0.9330, 0.2202, 0.4086, 0.0100, 0.1965, 

### **Test your Understanding**

1. Given a 3D tensor of shape `(a, b, c)`*italicised text*, permute its axes to obtain tensors of all other shape combinations (i.e 5).

In [ ]:
shape=torch.rand(3,4,5)
print(f"original tensor {shape}")
shape=shape.permute((0,2,1))
print(f"first permutation {shape}")
shape=shape.permute((2,1,0))
print(f"second permutation{shape}")
shape=shape.permute((2,0,1))
print(f"third permutation{shape}")
shape=shape.permute((1,2,0))
print(f"fourth permutation {shape}")
shape=shape.permute((1,0,2))
print(f"fifth permutaion {shape}")


original tensor tensor([[[6.6459e-01, 9.2443e-01, 3.7409e-01, 9.4291e-01, 6.3707e-01],
         [4.7361e-01, 5.1087e-01, 8.9752e-01, 7.3345e-01, 6.7849e-01],
         [7.8552e-01, 2.0424e-01, 2.9944e-01, 3.6286e-01, 3.7256e-03],
         [2.1634e-01, 8.2296e-01, 4.2996e-01, 6.2112e-01, 4.9642e-01]],

        [[7.3193e-01, 7.4580e-01, 1.9971e-01, 5.4694e-01, 9.2835e-01],
         [4.1596e-01, 1.9881e-01, 5.9809e-01, 8.5608e-01, 9.9739e-01],
         [9.9440e-01, 7.1575e-01, 4.3112e-01, 2.8601e-01, 9.0608e-01],
         [9.9052e-01, 1.7398e-01, 1.0763e-01, 8.3347e-01, 5.7019e-01]],

        [[5.7545e-01, 8.3838e-01, 2.0439e-02, 9.2322e-01, 7.0294e-01],
         [4.2581e-01, 4.4971e-01, 2.5173e-01, 2.3505e-01, 9.3164e-01],
         [1.5920e-04, 2.3572e-01, 9.5173e-01, 6.4317e-01, 4.8725e-02],
         [9.5768e-01, 3.3038e-01, 8.4508e-01, 9.2946e-01, 4.2310e-01]]])
first permutation tensor([[[6.6459e-01, 4.7361e-01, 7.8552e-01, 2.1634e-01],
         [9.2443e-01, 5.1087e-01, 2.0424e-01, 8.2

2. Given a 4D tensor of shape `(2, 3, 4, 5)`, transpose it to obtain a tensor of shape `(2, 4, 5, 3)`. Also explore what is_contiguous() means...

In [ ]:
ten=torch.rand(2,3,4,5)
ten=ten.permute(0,2,3,1)
print(ten)
print(ten.shape)

tensor([[[[0.5360, 0.9702, 0.7171],
          [0.9274, 0.7075, 0.5692],
          [0.3915, 0.9585, 0.4865],
          [0.6480, 0.2725, 0.5785],
          [0.6180, 0.1252, 0.9104]],

         [[0.0055, 0.2961, 0.2689],
          [0.9469, 0.5507, 0.7138],
          [0.1634, 0.1155, 0.8859],
          [0.2759, 0.4862, 0.8614],
          [0.9136, 0.2349, 0.2309]],

         [[0.7749, 0.2346, 0.0200],
          [0.9226, 0.9757, 0.4632],
          [0.4766, 0.6690, 0.9909],
          [0.9733, 0.8706, 0.3200],
          [0.4031, 0.8658, 0.3800]],

         [[0.3470, 0.6733, 0.5699],
          [0.7106, 0.1510, 0.8775],
          [0.4961, 0.3167, 0.2783],
          [0.1275, 0.8977, 0.0565],
          [0.1353, 0.5196, 0.9362]]],


        [[[0.4023, 0.9561, 0.4321],
          [0.8090, 0.8111, 0.9678],
          [0.4674, 0.1901, 0.1713],
          [0.1818, 0.0475, 0.4338],
          [0.1452, 0.0317, 0.7130]],

         [[0.8314, 0.2506, 0.6097],
          [0.8445, 0.7322, 0.1298],
          [0.083

3. Given two tensors, one of shape (n, 1) and another of shape (m, ), perform an element-wise addition.

In [ ]:
n, m = 5, 3
tensor1 = torch.randn(n, 1)
tensor2 = torch.randn(m)

result = tensor1 + tensor2
print(f"tensor_1{tensor1}")
print(f"tensor_2{tensor2}")
print(f"result {result}")
print(f"result shape {result.size()}")

tensor_1tensor([[-0.8209],
        [-0.7814],
        [-0.2197],
        [-1.8309],
        [ 0.0318]])
tensor_2tensor([-1.4207,  1.4746, -0.1698])
result tensor([[-2.2416,  0.6537, -0.9907],
        [-2.2021,  0.6932, -0.9512],
        [-1.6404,  1.2549, -0.3895],
        [-3.2516, -0.3563, -2.0007],
        [-1.3889,  1.5064, -0.1380]])
result shape torch.Size([5, 3])


4. Given a 3D tensor of shape `(4, 4, 4)`, extract a sub-tensor of shape `(2, 2, 2)` starting from the element at index `(1, 1, 1)`**bold text**.

In [ ]:
ten=torch.rand(4,4,4)
print(f"original tensor {ten}")
sub=ten[1:3,1:3,1:3]
print(f"sub tensor{sub}")
print(sub.shape)

original tensor tensor([[[0.4552, 0.8978, 0.6144, 0.8943],
         [0.9769, 0.5367, 0.5561, 0.7012],
         [0.1736, 0.2349, 0.8525, 0.2318],
         [0.8700, 0.0814, 0.1705, 0.8486]],

        [[0.0459, 0.3290, 0.4355, 0.7830],
         [0.3386, 0.3198, 0.0747, 0.3852],
         [0.0128, 0.5151, 0.6174, 0.2170],
         [0.8595, 0.5475, 0.1924, 0.9385]],

        [[0.1908, 0.9321, 0.1785, 0.7736],
         [0.1886, 0.9813, 0.2817, 0.8219],
         [0.8467, 0.7782, 0.0998, 0.8243],
         [0.1232, 0.3923, 0.3314, 0.7339]],

        [[0.4955, 0.1150, 0.3243, 0.6364],
         [0.2074, 0.3831, 0.2856, 0.2613],
         [0.4126, 0.2130, 0.2610, 0.7227],
         [0.3726, 0.0791, 0.1219, 0.8844]]])
sub tensortensor([[[0.3198, 0.0747],
         [0.5151, 0.6174]],

        [[0.9813, 0.2817],
         [0.7782, 0.0998]]])
torch.Size([2, 2, 2])


5. Given a 2-tensor of arbitrary shape, rotate it 90 degrees anticlockwise.



In [ ]:
a=torch.rand(4,5)
print(f"original tensor {a}")
b=torch.rot90(a,1)
print(b)

original tensor tensor([[0.9626, 0.0940, 0.5059, 0.5552, 0.0401],
        [0.5279, 0.7808, 0.6768, 0.3707, 0.8917],
        [0.8098, 0.2746, 0.2653, 0.1907, 0.5132],
        [0.1418, 0.2241, 0.1053, 0.6440, 0.4196]])
tensor([[0.0401, 0.8917, 0.5132, 0.4196],
        [0.5552, 0.3707, 0.1907, 0.6440],
        [0.5059, 0.6768, 0.2653, 0.1053],
        [0.0940, 0.7808, 0.2746, 0.2241],
        [0.9626, 0.5279, 0.8098, 0.1418]])


### **EVEN I HAD TO THINK...**

1. Implement a custom operation that computes the **element-wise** **sine** of a tensor *and* its **gradient** using torch.autograd.Function.
- You need to implement both the forward() and backward() methods.
- For an example, look no further than the [PyTorch docs](https://pytorch.org/docs/stable/autograd.html#function)!
- Test it out on a matrix of arbitrary size!

2. One of the most important aspects of improving model performance ins normalization. Implement a custom NN normalization layer that performs either a **batch** or **layer** normalization (based on a **dim** parameter)and integrate it into a simple feedforward neural network.
- Note that you dont need to implement any backward() here, for simplicity.
- Consider your input tensor to the neural network as of shape (m, n) where m is num of examples, n is num of features.
- Which value of **dim** leads to batch and layer normalization?

In [39]:


class CustomNormalization(nn.Module):
    def __init__(self, dim):
        super(CustomNormalization, self).__init__()
        self.dim = dim

    def forward(self, x):
        if self.dim == 0:
            # Batch normalization
            mean = x.mean(dim=0, keepdim=True)
            std = x.std(dim=0, keepdim=True)
        elif self.dim == 1:
            # Layer normalization
            mean = x.mean(dim=1, keepdim=True)
            std = x.std(dim=1, keepdim=True)
        else:
            raise ValueError("dim should be either 0 (batch normalization) or 1 (layer normalization)")

        normalized_x = (x - mean) / (std + 1e-5)
        return normalized_x

# Example usage:
x = torch.randn(5, 10)  # 5 examples, 10 features

# Batch normalization
batch_norm_layer = CustomNormalization(dim=0)
batch_normalized_x = batch_norm_layer(x)
print("Batch Normalized:\n", batch_normalized_x)

# Layer normalization
layer_norm_layer = CustomNormalization(dim=1)
layer_normalized_x = layer_norm_layer(x)
print("Layer Normalized:\n", layer_normalized_x)




class SimpleNN(nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim, norm_dim):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(input_dim, hidden_dim)
        self.norm1 = CustomNormalization(dim=norm_dim)
        self.fc2 = nn.Linear(hidden_dim, output_dim)

    def forward(self, x):
        x = self.fc1(x)
        x = F.relu(x)
        x = self.norm1(x)
        x = self.fc2(x)
        return x

# Example usage:
input_dim = 10
hidden_dim = 5
output_dim = 2
norm_dim = 1  # Layer normalization

model = SimpleNN(input_dim, hidden_dim, output_dim, norm_dim)


input_data = torch.randn(5, input_dim)  # 5 examples, 10 features
output_data = model(input_data)
print("Output:\n", output_data)



Batch Normalized:
 tensor([[-0.3935, -0.5172, -1.1634, -1.2547, -1.0160,  0.3033,  0.0401, -0.1053,
          0.3280,  0.8198],
        [ 0.7695, -0.1904,  0.2565,  0.1817,  0.5212, -0.8106, -0.1772,  1.7209,
         -0.5681,  0.9507],
        [-1.2005,  1.7697,  1.2371,  1.3734,  0.5996, -1.1759,  0.1604, -0.2878,
          0.6691, -0.4694],
        [ 1.2701, -0.5382, -0.8707,  0.3300, -1.1320,  0.3667,  1.3920, -0.4862,
         -1.4453, -1.4743],
        [-0.4456, -0.5239,  0.5405, -0.6304,  1.0272,  1.3166, -1.4154, -0.8416,
          1.0163,  0.1732]])
Layer Normalized:
 tensor([[-0.3079, -0.2784, -1.9602, -1.1318, -0.0142,  0.9274,  0.7199,  0.3767,
          0.2052,  1.4634],
        [ 0.0602, -0.6701,  0.1115,  0.3040,  0.1577, -0.7858, -0.3762,  2.2158,
         -1.5649,  0.5478],
        [-1.5241,  0.8839,  1.4143,  1.5195,  0.0781, -0.9549, -0.1125, -0.6675,
         -0.2571, -0.3796],
        [ 0.9493, -0.3555, -1.0970,  0.9418, -0.2096,  0.5609,  1.5761, -0.3471,
        

3. Given a 4D tensor of shape (2, 3, 4, 5), create a mask that sets all elements in positions where the sum of indices is even to zero.

In [ ]:
tensor = torch.randn(2, 3, 4, 5)
indices = torch.meshgrid(torch.arange(2), torch.arange(3), torch.arange(4), torch.arange(5), indexing='ij')
sum_indices = indices[0] + indices[1] + indices[2] + indices[3]
mask = (sum_indices % 2 == 0)
tensor[mask] = 0
print("Tensor after applying the mask:\n", tensor)


Tensor after applying the mask:
 tensor([[[[ 0.0000,  1.6038,  0.0000,  0.6781,  0.0000],
          [-0.4945,  0.0000,  0.4836,  0.0000,  0.5509],
          [ 0.0000,  0.6023,  0.0000,  2.4460,  0.0000],
          [-0.4428,  0.0000, -0.7583,  0.0000, -0.0349]],

         [[ 0.5459,  0.0000,  0.8838,  0.0000, -2.2990],
          [ 0.0000,  1.2019,  0.0000,  0.0559,  0.0000],
          [-0.9217,  0.0000, -1.2171,  0.0000,  1.8073],
          [ 0.0000,  1.8638,  0.0000, -0.0295,  0.0000]],

         [[ 0.0000,  2.0336,  0.0000, -0.2817,  0.0000],
          [-0.9481,  0.0000,  0.4616,  0.0000,  0.5607],
          [ 0.0000,  0.0661,  0.0000,  0.1018,  0.0000],
          [ 0.7582,  0.0000,  1.3591,  0.0000, -0.5934]]],


        [[[-0.5954,  0.0000, -3.3771,  0.0000, -2.1201],
          [ 0.0000, -0.6342,  0.0000, -2.0532,  0.0000],
          [ 1.0365,  0.0000,  1.2197,  0.0000, -1.4299],
          [ 0.0000,  0.8383,  0.0000,  2.3319,  0.0000]],

         [[ 0.0000,  1.3096,  0.0000,  0.2440

3. Given two tensors, one of shape `(3, 1, 4)` and another of shape `(1, 5, 1)`, compute their element-wise multiplication using broadcasting and then sum over specific axes to obtain a tensor of shape `(3, 5)`.

In [ ]:
a=torch.rand(3,1,4)
b=torch.rand(1,5,1)
print(f"first array {a}")
print(f"first array {b}")
c=a*b
print(c)
print(c.size())
c=c.sum(dim=2)
print(c)
print(c.size())


first array tensor([[[0.7124, 0.5901, 0.3329, 0.5866]],

        [[0.3941, 0.7003, 0.0526, 0.9100]],

        [[0.4228, 0.7916, 0.2499, 0.9410]]])
first array tensor([[[0.6445],
         [0.3604],
         [0.4484],
         [0.4534],
         [0.1471]]])
tensor([[[0.4591, 0.3803, 0.2146, 0.3781],
         [0.2568, 0.2127, 0.1200, 0.2114],
         [0.3194, 0.2646, 0.1493, 0.2630],
         [0.3230, 0.2675, 0.1510, 0.2660],
         [0.1048, 0.0868, 0.0490, 0.0863]],

        [[0.2540, 0.4514, 0.0339, 0.5865],
         [0.1420, 0.2524, 0.0189, 0.3280],
         [0.1767, 0.3140, 0.0236, 0.4080],
         [0.1787, 0.3175, 0.0238, 0.4126],
         [0.0579, 0.1030, 0.0077, 0.1338]],

        [[0.2725, 0.5102, 0.1611, 0.6064],
         [0.1524, 0.2853, 0.0901, 0.3392],
         [0.1896, 0.3549, 0.1121, 0.4219],
         [0.1917, 0.3589, 0.1133, 0.4266],
         [0.0622, 0.1164, 0.0368, 0.1384]]])
torch.Size([3, 5, 4])
tensor([[1.4320, 0.8009, 0.9963, 1.0075, 0.3267],
        [1.3257, 0.74