#  **PyTorch Practice Assignment**
**Name**: Ananya A K

**Roll Number**: 231CS208

## **Instructions:**

- Copy this Notebook to your own Drive! You cannot directly modify it.
- Please show the output of the cells, in case of some operation. You can specify your own **non-trivial** test-case. Also, try and make your snippets into functions to organize your logic.
- You can use any number of cells for a question, you are not restricted to just 1 cell!
- **No using ChatGPT for this assignment**: we highly recommend using the [Pytorch Docs](https://pytorch.org/docs/stable/index.html) as your start reference, as well as the vast internet however. You can also contact any of your mentors for some hints/help!
- You can work on this assignment in Google Colab or on Your Local Machine!

In [13]:
import torch

### **Build Up Your Understanding**

1. Write a PyTorch snippet to test whether none of the elements of a given tensor are zero.

In [ ]:
a = torch.rand(size=(2,3))
a

tensor([[0.7580, 0.6864, 0.2011],
        [0.2124, 0.0690, 0.6979]])

In [ ]:
torch.all(a) # True if all elements are non-zero

tensor(True)

2. Write a PyTorch snippet to test element-wise for NaN of a given tensor.

In [ ]:
a = torch.rand(size=(2,3))
a

tensor([[0.0855, 0.3814, 0.0181],
        [0.3027, 0.2256, 0.6116]])

In [ ]:
torch.isnan(a) # True if that element is NanN

tensor([[False, False, False],
        [False, False, False]])

3. Write a PyTorch snippet to test whether two tensors are element-wise equal within a tolerance.

In [ ]:
a = torch.rand(size=(2,3))
a

tensor([[0.6252, 0.5875, 0.9221],
        [0.3858, 0.0419, 0.8401]])

In [ ]:
b = torch.rand(size=(2,3))
b

tensor([[0.6700, 0.3275, 0.1052],
        [0.6689, 0.9281, 0.8171]])

In [ ]:
torch.equal(a,b)  # True if the two tensors are element-wise equal

False

4. Write a PyTorch snippet to create a tensor of 10 zeros, 10 ones, and 10 fives stacked on top of each other (try & accomplish everything using nested function calls).

In [ ]:
a = torch.vstack((torch.zeros(10),torch.ones(10),torch.full((10,),5)))
a

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])

5. Write a PyTorch snippet to generate a random number between 0 and 1.

In [ ]:
torch.rand(1).item()

0.7595442533493042

6. Write a PyTorch snippet to generate a tensor of 15 random numbers from a standard normal distribution.

In [ ]:
torch.normal(0, 1, size=(1, 15))  # torch.normal(mean, standard deviation, size)
# For a standard normal distribution, mean=0 and standard deviation=1

tensor([[-0.7283, -0.3638, -0.7125, -1.1957, -0.6134,  0.3719,  1.3737,  0.3619,
         -0.1787, -0.2389, -0.9504,  0.5313,  1.3797,  0.6585, -0.8103]])

In [ ]:
#Another method (standard normal distributions only)
torch.randn(1,15)

tensor([[ 0.7939,  0.1161,  0.3547,  0.7281,  0.3227, -0.4696,  0.0507,  0.0444,
          2.6296,  1.8317,  1.1380, -0.9753, -0.0869, -0.2418,  0.1704]])

7. Write a Pytorch snippet to create a tensor of length 10 with values evenly distributed between 5 and 50.

In [ ]:
a = torch.arange(start=5, end=51, step=5)
a

tensor([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

8. Write a Pyorch program to create a tensor with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15.

In [ ]:
a = torch.arange(21)
a

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20])

In [ ]:
a[(a>8)&(a<16)]*=(-1)
a

tensor([  0,   1,   2,   3,   4,   5,   6,   7,   8,  -9, -10, -11, -12, -13,
        -14, -15,  16,  17,  18,  19,  20])

9. Write a PyTorch snippet to create a 3x4 2-tensor filled with values from 10 to 21. Same but 12 to 24.

In [ ]:
a = torch.arange(start=10, end=22, step=1).reshape(3,4)
a

tensor([[10, 11, 12, 13],
        [14, 15, 16, 17],
        [18, 19, 20, 21]])

In [ ]:
b = torch.randint(12,25,(3,4))
b

tensor([[21, 21, 18, 24],
        [19, 12, 20, 17],
        [17, 15, 13, 23]])

10. Write a PyTorch snippet to create a 10x10 2-tensor, in which the elements on the borders will be equal to 1, and inside 0.

In [ ]:
a = torch.zeros(10,10).type(torch.int64)
a

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
a[0,:]=1 #First row
a[-1,:]=1 #Last row
a[:,0]=1 #First column
a[:,-1]=1 #Last column
a

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

11. Write a PyTorch snippet to create a 5x5 zero 2-tensor with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [ ]:
a = torch.zeros(5,5).type(torch.int64)
a

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]])

In [ ]:
a[0,0]=1
a[1,1]=2
a[2,2]=3
a[3,3]=4
a[4,4]=5
a

tensor([[1, 0, 0, 0, 0],
        [0, 2, 0, 0, 0],
        [0, 0, 3, 0, 0],
        [0, 0, 0, 4, 0],
        [0, 0, 0, 0, 5]])

12. Write a PyTorch snippet to save a given tensor as a binary to a given path.

In [ ]:
torch.save(a,"file1.bin")

13. Write a NumPy program to create a two-dimensional array of a specified format.

In [ ]:
import numpy as np

In [ ]:
a = np.random.randint(0, 10, (3,4))
a

array([[8, 8, 2, 0],
       [9, 3, 1, 5],
       [1, 0, 0, 4]])

14. Write a PyTorch snippet to create a 2-tensor with shape (8,5) of random numbers. Select these random numbers (to create the tensor) from a normal distribution (200,7) (mean, variance).

In [ ]:
a = torch.normal(200, np.sqrt(7), size=(8, 5)) #standard deviation=sqrt(variance)
a

tensor([[198.7813, 198.5034, 200.0081, 200.9547, 208.2757],
        [202.2819, 199.9696, 202.7132, 199.7283, 198.0742],
        [204.9684, 194.2558, 204.5312, 194.6466, 199.4124],
        [200.0699, 203.3092, 204.0299, 195.1228, 201.2071],
        [198.2218, 195.7533, 199.1996, 198.5974, 201.4911],
        [199.0251, 198.4268, 197.9748, 200.3855, 205.9078],
        [199.8089, 196.7822, 200.9776, 197.9053, 206.4102],
        [199.2184, 200.6030, 192.1710, 201.6237, 203.5253]])

15. Write a PyTorch snippet to generate a uniform, non-uniform random sample from a given vector with and without replacement (do all 4 combinations possible).

In [10]:
#Uniform w/ replacement
a = torch.arange(10)
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
a2 = a[torch.randint(0,len(a),(5,))]
a2

tensor([2, 4, 6, 5, 6])

In [6]:
#Uniform w/o replacement(samples size=5, vector length=10)
b = torch.randperm(10)
b

tensor([9, 7, 5, 3, 8, 6, 0, 4, 2, 1])

In [7]:
b2 = b[:5]
b2

tensor([9, 7, 5, 3, 8])

In [21]:
#Non-Uniform w/o replacement
weights = torch.tensor([8, 10, 3, 0]).type(torch.float64)
weights

tensor([ 8., 10.,  3.,  0.], dtype=torch.float64)

In [22]:
c = torch.multinomial(weights, 2)
c

tensor([0, 1])

In [23]:
#Non-Uniform w/ replacement
weights = torch.tensor([8, 10, 3, 0]).type(torch.float64)
weights

tensor([ 8., 10.,  3.,  0.], dtype=torch.float64)

In [24]:
torch.multinomial(weights, 4, replacement=True)

tensor([0, 1, 1, 1])

16. Write a Pyorch snippet to create an nxn(input to function) tensor with random values. Create an array from the said array swapping first and last rows.

In [ ]:
n = 4

In [ ]:
a = torch.arange(4*4).reshape(4,4)
a

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

In [ ]:
first_row = a[0,:]
a[0,:]=a[n-1,:]
a[n-1,:]=first_row
a

tensor([[12, 13, 14, 15],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

17. Write a PyTorch snippet to sort a given tensor (1D or 2D) in ascending order.

In [ ]:
a = torch.rand(1,5)
a

tensor([[0.2126, 0.2464, 0.4109, 0.0556, 0.2901]])

In [ ]:
sorted, indices = torch.sort(a,descending=False)
sorted

tensor([[0.0556, 0.2126, 0.2464, 0.2901, 0.4109]])

18. Write a PyTorch snippet to create a tensor of equal shape and data type for a given tensor (any dimensional)

In [ ]:
a = torch.randn(3,4)
a, a.dtype

(tensor([[ 1.6452,  1.1526,  0.1129,  0.9185],
         [-1.0933,  1.0226, -0.8607,  1.6618],
         [-0.1234, -0.4756,  0.6395,  0.2567]]),
 torch.float32)

In [ ]:
b = torch.clone(a)
b, b.dtype

(tensor([[ 1.6452,  1.1526,  0.1129,  0.9185],
         [-1.0933,  1.0226, -0.8607,  1.6618],
         [-0.1234, -0.4756,  0.6395,  0.2567]]),
 torch.float32)

19. Write a PyTorch snippet to create an 8x8 matrix and fill it with a checkerboard pattern.
Checkerboard pattern:
```py
[[0 1 0 1 0 1 0 1]
..........
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]]
```

In [ ]:
a = torch.tensor([0,1,0,1,0,1,0,1])
b = torch.tensor([1,0,1,0,1,0,1,0])
c = torch.vstack((torch.vstack((a,b)),torch.vstack((a,b))))
d = torch.vstack((c,c))
d

tensor([[0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0],
        [0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0],
        [0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0],
        [0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0]])

20. Write a Pytorch snippet to convert Centigrade to Fahrenheit and vice versa (controlled by a parameter). Ensure you operation is vectorized i.e **no explicit looping**

Sample Array: `[0, 12, 45.21, 34, 99.91]`

In [30]:
a = torch.randn(1,5)
a

tensor([[-1.4342,  0.5277,  0.9972,  0.3680, -0.8096]])

In [34]:
def convertor(inp_unit,val):
  if inp_unit == "c" or inp_unit == "C":
    return (val*9/5) + 32
  elif inp_unit == "f" | inp_unit == "F":
    return (val - 32)*5/9
  else:
    print("Unit must Celcius(c) or Farhenheit(f)")

In [35]:
convertor("c",a)

tensor([[29.4184, 32.9499, 33.7949, 32.6624, 30.5427]])

21. Write a PyTorch snippet to get the values of the elements that are bigger than a given *number* in a given tensor.

Original tensor:
```
[[ 0 10 20]
[20 30 40]]
```
Number: 10

Values bigger than 10 = `[20 20 30 40]`

In [ ]:
a = torch.randn(2,3)
a

tensor([[ 1.5569,  0.8340,  0.5788],
        [-0.3074,  0.5047, -0.6708]])

In [ ]:
a[a>0]

tensor([1.5569, 0.8340, 0.5788, 0.5047])

22. Write a PyTorch snippet to create another shape from an array without changing its data. After carrying out the operation, change the data in one place and see if the other tensor changes

Reshape 3x2:
```
[[1 2]
[3 4]
[5 6]]
```
Reshape 2x3:
```
[[1 2 3]
[4 5 6]]
```

In [ ]:
a = torch.randn(3,2)
a

tensor([[-0.2333, -0.1472],
        [-0.6752,  1.2798],
        [-1.3121,  0.4583]])

In [ ]:
b = torch.reshape(a,(2,3))
b

tensor([[-0.2333, -0.1472, -0.6752],
        [ 1.2798, -1.3121,  0.4583]])

23. Write a PyTorch snipppet to change an tensor's data type.
```
[[ 2 4 6]
[ 6 8 10]]
```
Data type of the array x is: `int32`

New Type: `float64`
```
[[ 2. 4. 6.]
[ 6. 8. 10.]]
```

In [ ]:
a = torch.arange(5)
a, a.dtype

(tensor([0, 1, 2, 3, 4]), torch.int64)

In [ ]:
b = a.type(torch.float64)
b

tensor([0., 1., 2., 3., 4.], dtype=torch.float64)

24. Write a PyTorch snippet to insert a new axis within a 2-tensor, based on a **parameter**.

Ex: If 2-tensor has shape (3, 4).

Then, new shape can be (1, 3, 4), (3, 1, 4), or (3, 4, 1) depending on....

In [ ]:
a = torch.randn(3,4)
a, a.shape

(tensor([[-0.3630,  0.1313, -0.9897, -1.3024],
         [ 1.2956, -0.3222,  0.1484,  0.8915],
         [ 2.0638, -0.5392, -1.4175, -0.4414]]),
 torch.Size([3, 4]))

In [ ]:
b = a.reshape(1,3,4)
b, b.shape

(tensor([[[-0.3630,  0.1313, -0.9897, -1.3024],
          [ 1.2956, -0.3222,  0.1484,  0.8915],
          [ 2.0638, -0.5392, -1.4175, -0.4414]]]),
 torch.Size([1, 3, 4]))

In [ ]:
c = a.reshape(3,4,1)
c, c.shape

(tensor([[[-0.3630],
          [ 0.1313],
          [-0.9897],
          [-1.3024]],
 
         [[ 1.2956],
          [-0.3222],
          [ 0.1484],
          [ 0.8915]],
 
         [[ 2.0638],
          [-0.5392],
          [-1.4175],
          [-0.4414]]]),
 torch.Size([3, 4, 1]))

In [ ]:
d = a.reshape(3,1,4)
d, d.shape

(tensor([[[-0.3630,  0.1313, -0.9897, -1.3024]],
 
         [[ 1.2956, -0.3222,  0.1484,  0.8915]],
 
         [[ 2.0638, -0.5392, -1.4175, -0.4414]]]),
 torch.Size([3, 1, 4]))

25. Write a PyTorch snippet to stack tensors based on a parameter, **axis**.
First discover what this means with 2-tensors, then extend it to 3-tensors. Print your findings.

Sample Output:

Original tensors:

Tensor-1
```
[[0 1 2]
[3 4 5]
[6 7 8]]
```
Tensor-2
```
[[ 0 3 6]
[ 9 12 15]
[18 21 24]]
```
Stack tensors such that axis=1:
```
[[ 0 1 2 0 3 6]
[ 3 4 5 9 12 15]
[ 6 7 8 18 21 24]]
```

In [ ]:
a = torch.arange(0,9,1).reshape(3,3)
b = torch.arange(9,18,1).reshape(3,3)
a, b

(tensor([[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]),
 tensor([[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]))

In [ ]:
c = torch.hstack((a,b))
c

tensor([[ 0,  1,  2,  9, 10, 11],
        [ 3,  4,  5, 12, 13, 14],
        [ 6,  7,  8, 15, 16, 17]])

26. Write a PyTorch snippet to extract the **m**th to **n**th elements of the **m**th to **n**th rows from the **m**th to nth elemnts of given 3-tensor, of shape `(p, q, r)` where m, n < p, q, r.

Take a 3-tensor of (say) size `(5,6,7)` and `(m, n)` = `(4, 5)` as a test case!

In [ ]:
p = 5
q = 6
r = 7
m = 3
n = 4

In [ ]:
x = torch.arange(p*q*r).reshape(p,q,r)
x

tensor([[[  0,   1,   2,   3,   4,   5,   6],
         [  7,   8,   9,  10,  11,  12,  13],
         [ 14,  15,  16,  17,  18,  19,  20],
         [ 21,  22,  23,  24,  25,  26,  27],
         [ 28,  29,  30,  31,  32,  33,  34],
         [ 35,  36,  37,  38,  39,  40,  41]],

        [[ 42,  43,  44,  45,  46,  47,  48],
         [ 49,  50,  51,  52,  53,  54,  55],
         [ 56,  57,  58,  59,  60,  61,  62],
         [ 63,  64,  65,  66,  67,  68,  69],
         [ 70,  71,  72,  73,  74,  75,  76],
         [ 77,  78,  79,  80,  81,  82,  83]],

        [[ 84,  85,  86,  87,  88,  89,  90],
         [ 91,  92,  93,  94,  95,  96,  97],
         [ 98,  99, 100, 101, 102, 103, 104],
         [105, 106, 107, 108, 109, 110, 111],
         [112, 113, 114, 115, 116, 117, 118],
         [119, 120, 121, 122, 123, 124, 125]],

        [[126, 127, 128, 129, 130, 131, 132],
         [133, 134, 135, 136, 137, 138, 139],
         [140, 141, 142, 143, 144, 145, 146],
         [147, 148, 149, 150

In [ ]:
y = x[m:n+1, m:n+1, m:n+1]
y

tensor([[[150, 151],
         [157, 158]],

        [[192, 193],
         [199, 200]]])

### **Test your Understanding**

1. Given a 3D tensor of shape `(a, b, c)`*italicised text*, permute its axes to obtain tensors of all other shape combinations (i.e 5).

In [ ]:
a = 2
b = 3
c = 4

In [ ]:
x = torch.rand(a,b,c)
x, x.shape

(tensor([[[0.8190, 0.0825, 0.3152, 0.4047],
          [0.8869, 0.8547, 0.8596, 0.3957],
          [0.4127, 0.3657, 0.5912, 0.2012]],
 
         [[0.9690, 0.7423, 0.5487, 0.0716],
          [0.2117, 0.5458, 0.8087, 0.9008],
          [0.8198, 0.1592, 0.0990, 0.9839]]]),
 torch.Size([2, 3, 4]))

In [ ]:
p1 = torch.transpose(x,0,1)
p1, p1.shape

(tensor([[[0.8190, 0.0825, 0.3152, 0.4047],
          [0.9690, 0.7423, 0.5487, 0.0716]],
 
         [[0.8869, 0.8547, 0.8596, 0.3957],
          [0.2117, 0.5458, 0.8087, 0.9008]],
 
         [[0.4127, 0.3657, 0.5912, 0.2012],
          [0.8198, 0.1592, 0.0990, 0.9839]]]),
 torch.Size([3, 2, 4]))

In [ ]:
p2 = torch.transpose(x,0,2)
p2, p2.shape

(tensor([[[0.8190, 0.9690],
          [0.8869, 0.2117],
          [0.4127, 0.8198]],
 
         [[0.0825, 0.7423],
          [0.8547, 0.5458],
          [0.3657, 0.1592]],
 
         [[0.3152, 0.5487],
          [0.8596, 0.8087],
          [0.5912, 0.0990]],
 
         [[0.4047, 0.0716],
          [0.3957, 0.9008],
          [0.2012, 0.9839]]]),
 torch.Size([4, 3, 2]))

In [ ]:
p3 = torch.transpose(x,2,1)
p3, p3.shape

(tensor([[[0.8190, 0.8869, 0.4127],
          [0.0825, 0.8547, 0.3657],
          [0.3152, 0.8596, 0.5912],
          [0.4047, 0.3957, 0.2012]],
 
         [[0.9690, 0.2117, 0.8198],
          [0.7423, 0.5458, 0.1592],
          [0.5487, 0.8087, 0.0990],
          [0.0716, 0.9008, 0.9839]]]),
 torch.Size([2, 4, 3]))

In [ ]:
p4 = torch.transpose(torch.transpose(x,0,2),1,2)
p4, p4.shape

(tensor([[[0.8190, 0.8869, 0.4127],
          [0.9690, 0.2117, 0.8198]],
 
         [[0.0825, 0.8547, 0.3657],
          [0.7423, 0.5458, 0.1592]],
 
         [[0.3152, 0.8596, 0.5912],
          [0.5487, 0.8087, 0.0990]],
 
         [[0.4047, 0.3957, 0.2012],
          [0.0716, 0.9008, 0.9839]]]),
 torch.Size([4, 2, 3]))

In [ ]:
p5 = torch.transpose(torch.transpose(x,0,1),1,2)
p5, p5.shape

(tensor([[[0.8190, 0.9690],
          [0.0825, 0.7423],
          [0.3152, 0.5487],
          [0.4047, 0.0716]],
 
         [[0.8869, 0.2117],
          [0.8547, 0.5458],
          [0.8596, 0.8087],
          [0.3957, 0.9008]],
 
         [[0.4127, 0.8198],
          [0.3657, 0.1592],
          [0.5912, 0.0990],
          [0.2012, 0.9839]]]),
 torch.Size([3, 4, 2]))

2. Given a 4D tensor of shape `(2, 3, 4, 5)`, transpose it to obtain a tensor of shape `(2, 4, 5, 3)`. Also explore what is_contiguous() means...

In [26]:
a = torch.randn(2, 3, 4, 5)
a, a.shape

(tensor([[[[-0.5419, -1.5553, -0.8628, -0.7371, -0.1246],
           [ 1.8694,  0.9238, -0.4893,  0.0111, -0.1957],
           [-0.4796,  1.8699,  0.7391,  0.6478,  0.7605],
           [ 0.1248, -0.6036,  0.9977, -0.1442,  0.3140]],
 
          [[-0.2667,  0.0552, -0.7417, -0.9283,  0.6616],
           [-1.0319,  0.1761, -0.1887, -0.4732,  1.2245],
           [-1.3073,  2.4665, -0.4699, -0.5913,  1.1067],
           [ 1.2160,  0.4021,  0.1967, -1.9179,  2.3012]],
 
          [[ 0.3485, -1.2077,  0.0474, -0.1938,  0.0351],
           [ 0.1763,  0.4369, -1.2681, -1.0167, -2.1848],
           [ 0.1395, -2.0530,  1.6639,  0.4268,  1.2891],
           [-1.2008, -1.4515,  0.4664, -0.0546,  1.1756]]],
 
 
         [[[ 0.1175, -3.0624,  0.7428,  0.6433,  0.6604],
           [-0.2097,  0.9813, -0.2046,  1.1998,  1.0563],
           [ 0.1624, -0.6652, -1.4304, -0.8119, -2.4574],
           [-0.0463, -1.2224,  0.5761, -0.7996, -1.7347]],
 
          [[-0.0570,  1.4642, -0.0609, -0.2541,  0.0926],

In [27]:
b = torch.transpose(torch.transpose(a, 1, 2),2,3)
b, b.shape

(tensor([[[[-0.5419, -0.2667,  0.3485],
           [-1.5553,  0.0552, -1.2077],
           [-0.8628, -0.7417,  0.0474],
           [-0.7371, -0.9283, -0.1938],
           [-0.1246,  0.6616,  0.0351]],
 
          [[ 1.8694, -1.0319,  0.1763],
           [ 0.9238,  0.1761,  0.4369],
           [-0.4893, -0.1887, -1.2681],
           [ 0.0111, -0.4732, -1.0167],
           [-0.1957,  1.2245, -2.1848]],
 
          [[-0.4796, -1.3073,  0.1395],
           [ 1.8699,  2.4665, -2.0530],
           [ 0.7391, -0.4699,  1.6639],
           [ 0.6478, -0.5913,  0.4268],
           [ 0.7605,  1.1067,  1.2891]],
 
          [[ 0.1248,  1.2160, -1.2008],
           [-0.6036,  0.4021, -1.4515],
           [ 0.9977,  0.1967,  0.4664],
           [-0.1442, -1.9179, -0.0546],
           [ 0.3140,  2.3012,  1.1756]]],
 
 
         [[[ 0.1175, -0.0570, -0.2083],
           [-3.0624,  1.4642,  1.1217],
           [ 0.7428, -0.0609,  0.8902],
           [ 0.6433, -0.2541,  1.2472],
           [ 0.6604,  0.0

In [28]:
a.is_contiguous()

True

In [29]:
b.is_contiguous()

False

3. Given two tensors, one of shape (n, 1) and another of shape (m, ), perform an element-wise addition.

In [ ]:
n = 2 #Random number
m = 3 #Random number

In [ ]:
a = torch.randn(n,1)
b = torch.randn(m,)
a,b

(tensor([[ 0.9178],
         [-0.0512]]),
 tensor([-1.4549, -1.0094,  1.9827]))

In [ ]:
c = torch.add(a,b)
c

tensor([[-0.5371, -0.0915,  2.9005],
        [-1.5061, -1.0606,  1.9314]])

4. Given a 3D tensor of shape `(4, 4, 4)`, extract a sub-tensor of shape `(2, 2, 2)` starting from the element at index `(1, 1, 1)`**bold text**.

In [ ]:
a = torch.arange(4*4*4).reshape(4,4,4)
a

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15]],

        [[16, 17, 18, 19],
         [20, 21, 22, 23],
         [24, 25, 26, 27],
         [28, 29, 30, 31]],

        [[32, 33, 34, 35],
         [36, 37, 38, 39],
         [40, 41, 42, 43],
         [44, 45, 46, 47]],

        [[48, 49, 50, 51],
         [52, 53, 54, 55],
         [56, 57, 58, 59],
         [60, 61, 62, 63]]])

In [ ]:
b = a[(1,1,1)[0]:(1,1,1)[0]+2,(1,1,1)[1]:(1,1,1)[1]+2,(1,1,1)[2]:(1,1,1)[2]+2]
b

tensor([[[21, 22],
         [25, 26]],

        [[37, 38],
         [41, 42]]])

5. Given a 2-tensor of arbitrary shape, rotate it 90 degrees anticlockwise.



In [ ]:
a = torch.randn(2,2)
a

tensor([[ 0.6769, -1.0869],
        [ 0.6262,  0.6471]])

In [ ]:
b = torch.rot90(a, k=1, dims=[0, 1]) #Parameters: (tensor, no. of times to rotate, axis)
b

tensor([[-1.0869,  0.6471],
        [ 0.6769,  0.6262]])

### **EVEN I HAD TO THINK...**

1. Implement a custom operation that computes the **element-wise** **sine** of a tensor *and* its **gradient** using torch.autograd.Function.
- You need to implement both the forward() and backward() methods.
- For an example, look no further than the [PyTorch docs](https://pytorch.org/docs/stable/autograd.html#function)!
- Test it out on a matrix of arbitrary size!

2. One of the most important aspects of improving model performance ins normalization. Implement a custom NN normalization layer that performs either a **batch** or **layer** normalization (based on a **dim** parameter)and integrate it into a simple feedforward neural network.
- Note that you dont need to implement any backward() here, for simplicity.
- Consider your input tensor to the neural network as of shape (m, n) where m is num of examples, n is num of features.
- Which value of **dim** leads to batch and layer normalization?

In [2]:
import torch.nn as nn
import torch.nn.functional as f

In [18]:
class CustomNNNormalizationLayer(nn.Module):
  def __init__(self,dim,NumOfFeatures):
    super(CustomNNNormalizationLayer,self).__init__()
    self.dim = dim
    if dim == "batch":
      self.normalization = nn.BatchNorm1d(NumOfFeatures)
    elif dim == "layer":
      self.normalization = nn.LayerNorm(NumOfFeatures)
    else:
      print("Invalid input: dim is either 'batch' or 'layer'")
  def forward(self, x):
    return self.normalization(x)

In [19]:
# Simple feed forward NN has an input layer, a hidden layer and an output layer
class SimpleFeedforwardNN(nn.Module):
  def __init__(self,inp_size,hid_size,out_size,dim):
    super(SimpleFeedforwardNN,self).__init__()
    self.inpLayer = nn.Linear(inp_size,hid_size)
    self.normalization1 = CustomNNNormalizationLayer(dim,hid_size)
    self.hidLayer = nn.Linear(hid_size,hid_size)
    self.normalization2 = CustomNNNormalizationLayer(dim,hid_size)
    self.outLayer = nn.Linear(hid_size,out_size)
  def forward(self,x):
    x = f.relu(self.normalization1(self.inpLayer(x))) # input layer-->normalised-->activation layer
    x = f.relu(self.normalization2(self.hidLayer(x)))
    x = self.outLayer(x) # output
    return x

In [20]:
inp_size = 10
hid_size = 20
out_size = 1
dim = "batch"
m = 5 #No of examples
n = 10 #No of features

In [21]:
model = SimpleFeedforwardNN(inp_size,hid_size,out_size,dim)

In [22]:
a = torch.randn(m,n)
a

tensor([[-1.1352, -0.5793,  0.8846, -0.0318,  1.1484,  0.3455,  0.4456,  0.9709,
          0.4508,  0.7723],
        [-0.9453, -0.9917, -1.4682, -0.1451,  0.2378, -0.1158, -0.2972, -0.1230,
          1.6163,  1.3793],
        [ 1.2445, -0.7728, -0.7577, -0.7851, -0.5544, -0.2819, -0.8853,  0.9011,
          1.1709,  0.6983],
        [ 0.4574, -1.5362,  1.2753, -0.2709, -0.3550,  2.4130, -1.0506,  1.2159,
          0.6877,  0.4095],
        [-0.9770, -0.9323,  0.1917, -0.0888, -0.4950, -2.7382,  1.7589,  1.6086,
         -0.1658,  1.6587]])

In [23]:
b = model(a)
b

tensor([[-0.0633],
        [-0.3487],
        [-0.2714],
        [ 0.7469],
        [-0.1309]], grad_fn=<AddmmBackward0>)

3. Given a 4D tensor of shape (2, 3, 4, 5), create a mask that sets all elements in positions where the sum of indices is even to zero.

In [25]:
a = torch.randn(2,3,4,5)
a

tensor([[[[ 1.9375, -1.9024,  1.8641, -0.4257, -1.3650],
          [ 0.5279, -0.3060, -0.6539,  1.4566,  0.2199],
          [ 1.4433,  0.4831, -0.9246,  0.9083, -1.0661],
          [ 0.6366,  0.9666, -0.2143,  0.8072, -0.6770]],

         [[-0.0323, -0.8825,  1.7307, -0.9670, -0.2540],
          [-0.0065, -1.2614,  0.3421,  0.4335, -1.3133],
          [ 0.4454, -2.9778,  0.4832,  0.8423, -1.0675],
          [ 0.0620, -1.6692,  1.2287,  0.4357,  0.7899]],

         [[-1.0397, -0.3182,  0.0556, -0.1501, -1.5564],
          [ 0.0344, -0.8691,  0.8632,  0.0264, -0.0656],
          [-0.0749, -1.9194,  1.1419, -0.1716,  2.1654],
          [-0.3581, -0.4383, -0.5277,  0.0213,  0.6186]]],


        [[[-0.2185,  0.9721, -1.0493, -1.1103,  0.5849],
          [ 0.8093,  0.4266, -0.2970,  1.5539, -0.3785],
          [ 0.2704, -1.7535, -0.1151, -1.2962, -0.7218],
          [ 1.4517, -0.1919, -0.1908,  0.1001, -0.0834]],

         [[ 0.9635, -0.2082, -0.1503, -0.1414, -0.4588],
          [ 0.6452, -

In [32]:
for i in range (0,2):
  for j in range (0,3):
    for k in range (0,4):
      for l in range (0,5):
        if(i+j+k+l)%2==0:
          a[i][j][k][l]=0
a

tensor([[[[ 0.0000, -1.9024,  0.0000, -0.4257,  0.0000],
          [ 0.5279,  0.0000, -0.6539,  0.0000,  0.2199],
          [ 0.0000,  0.4831,  0.0000,  0.9083,  0.0000],
          [ 0.6366,  0.0000, -0.2143,  0.0000, -0.6770]],

         [[-0.0323,  0.0000,  1.7307,  0.0000, -0.2540],
          [ 0.0000, -1.2614,  0.0000,  0.4335,  0.0000],
          [ 0.4454,  0.0000,  0.4832,  0.0000, -1.0675],
          [ 0.0000, -1.6692,  0.0000,  0.4357,  0.0000]],

         [[ 0.0000, -0.3182,  0.0000, -0.1501,  0.0000],
          [ 0.0344,  0.0000,  0.8632,  0.0000, -0.0656],
          [ 0.0000, -1.9194,  0.0000, -0.1716,  0.0000],
          [-0.3581,  0.0000, -0.5277,  0.0000,  0.6186]]],


        [[[-0.2185,  0.0000, -1.0493,  0.0000,  0.5849],
          [ 0.0000,  0.4266,  0.0000,  1.5539,  0.0000],
          [ 0.2704,  0.0000, -0.1151,  0.0000, -0.7218],
          [ 0.0000, -0.1919,  0.0000,  0.1001,  0.0000]],

         [[ 0.0000, -0.2082,  0.0000, -0.1414,  0.0000],
          [ 0.6452,  

4. Given two tensors, one of shape `(3, 1, 4)` and another of shape `(1, 5, 1)`, compute their element-wise multiplication using broadcasting and then sum over specific axes to obtain a tensor of shape `(3, 5)`.

In [33]:
a = torch.randn(3,1,4)
a

tensor([[[-1.3007,  0.9623,  0.5491, -0.9326]],

        [[ 0.9413,  0.0506,  0.7132, -0.4946]],

        [[-0.2614,  0.8274, -1.2676, -0.6881]]])

In [34]:
b = torch.randn(1,5,1)
b

tensor([[[-0.4749],
         [ 0.0511],
         [ 0.8801],
         [ 0.9046],
         [-0.3102]]])

In [36]:
c = a*b
c, c.shape

(tensor([[[ 0.6177, -0.4571, -0.2608,  0.4429],
          [-0.0664,  0.0491,  0.0280, -0.0476],
          [-1.1447,  0.8469,  0.4833, -0.8208],
          [-1.1766,  0.8706,  0.4967, -0.8437],
          [ 0.4035, -0.2985, -0.1703,  0.2893]],
 
         [[-0.4471, -0.0240, -0.3387,  0.2349],
          [ 0.0481,  0.0026,  0.0364, -0.0253],
          [ 0.8285,  0.0445,  0.6277, -0.4353],
          [ 0.8516,  0.0458,  0.6452, -0.4474],
          [-0.2920, -0.0157, -0.2212,  0.1534]],
 
         [[ 0.1241, -0.3930,  0.6020,  0.3268],
          [-0.0133,  0.0423, -0.0647, -0.0351],
          [-0.2300,  0.7282, -1.1156, -0.6056],
          [-0.2364,  0.7485, -1.1467, -0.6225],
          [ 0.0811, -0.2567,  0.3932,  0.2135]]]),
 torch.Size([3, 5, 4]))

In [38]:
d = c.sum(dim=2)
d, d.shape

(tensor([[ 0.3428, -0.0369, -0.6353, -0.6530,  0.2239],
         [-0.5749,  0.0618,  1.0654,  1.0951, -0.3755],
         [ 0.6600, -0.0710, -1.2230, -1.2571,  0.4311]]),
 torch.Size([3, 5]))