<a href="https://colab.research.google.com/github/nagamukesh/NLP-SMP/blob/vedh/PyTorch_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  **PyTorch Practice Assignment**
**Name**: VEDH ADLA

**Roll Number**: 231AI004

## **Instructions:**

- Copy this Notebook to your own Drive! You cannot directly modify it.
- Please show the output of the cells, in case of some operation. You can specify your own **non-trivial** test-case. Also, try and make your snippets into functions to organize your logic.
- You can use any number of cells for a question, you are not restricted to just 1 cell!
- **No using ChatGPT for this assignment**: we highly recommend using the [Pytorch Docs](https://pytorch.org/docs/stable/index.html) as your start reference, as well as the vast internet however. You can also contact any of your mentors for some hints/help!
- You can work on this assignment in Google Colab or on Your Local Machine!

### **Build Up Your Understanding**

1. Write a PyTorch snippet to test whether none of the elements of a given tensor are zero.

In [4]:
import torch
tensor1 = torch.tensor([1,9,0,4])
tensor2 = torch.tensor([2,1,34,3])
check1 = torch.all(tensor1 != 0)
check2 = torch.all(tensor2 !=0)
print(check1)
print(check2)

tensor(False)
tensor(True)


2. Write a PyTorch snippet to test element-wise for NaN of a given tensor.

In [5]:
tensor1 = torch.tensor([2.3,2.4,3.2,float('nan'),5.4,6.9])
check1 = torch.isnan(tensor1)
print(check1)

tensor([False, False, False,  True, False, False])


3. Write a PyTorch snippet to test whether two tensors are element-wise equal within a tolerance.

In [6]:
tensor1 = torch.tensor([1,2,3,4])
tensor2 = torch.tensor([1,2,4,3])
tensor3 = torch.tensor([1,2,3,4])
torch.equal(tensor1,tensor2) , torch.equal(tensor1,tensor3)


(False, True)

4. Write a PyTorch snippet to create a tensor of 10 zeros, 10 ones, and 10 fives stacked on top of each other (try & accomplish everything using nested function calls).

In [7]:
tensor = torch.vstack((torch.zeros(10) , torch.ones(10), torch.full((10,) ,5)))
tensor

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])

5. Write a PyTorch snippet to generate a random number between 0 and 1.

In [8]:
temp = torch.rand(1).item()
temp

0.9471277594566345

6. Write a PyTorch snippet to generate a tensor of 15 random numbers from a standard normal distribution.

In [9]:
tensor = torch.randn(15)
tensor

tensor([-0.1147, -0.9686, -1.1091,  0.0729, -1.8293,  1.3941,  0.1574, -0.3828,
         0.2664, -0.5455, -1.3127,  1.5737,  0.3579, -0.1459, -0.0305])

7. Write a Pytorch snippet to create a tensor of length 10 with values evenly distributed between 5 and 50.

In [10]:
tensor = torch.linspace(5,50,10)
tensor

tensor([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

8. Write a Pyorch program to create a tensor with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15.

In [12]:

tensor = torch.arange(0,21)
tensor[(tensor>=9) & (tensor<=15)] *= -1
tensor

tensor([  0,   1,   2,   3,   4,   5,   6,   7,   8,  -9, -10, -11, -12, -13,
        -14, -15,  16,  17,  18,  19,  20])

9. Write a PyTorch snippet to create a 3x4 2-tensor filled with values from 10 to 21. Same but 12 to 24.

In [13]:
tensor1 = torch.arange(10,22).reshape(3,4)
tensor2 = torch.arange(12,24).reshape(3,4)
tensor1,tensor2

(tensor([[10, 11, 12, 13],
         [14, 15, 16, 17],
         [18, 19, 20, 21]]),
 tensor([[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]))

10. Write a PyTorch snippet to create a 10x10 2-tensor, in which the elements on the borders will be equal to 1, and inside 0.

In [11]:
tensor = torch.zeros(100).reshape(10,10)
tensor[:,0] =1
tensor[0,:] =1
tensor[9,:]=1
tensor[:,9]=1
tensor

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

11. Write a PyTorch snippet to create a 5x5 zero 2-tensor with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [14]:
a = torch.tensor([1,2,3,4,5])
torch.diag(a)

tensor([[1, 0, 0, 0, 0],
        [0, 2, 0, 0, 0],
        [0, 0, 3, 0, 0],
        [0, 0, 0, 4, 0],
        [0, 0, 0, 0, 5]])

12. Write a PyTorch snippet to save a given tensor as a binary to a given path.

In [15]:

tensor = torch.tensor([1,2,3])
path = 'tensor.path'
torch.save(tensor,path)
print(f"Tensor saved to {path}")


Tensor saved to tensor.path


13. Write a NumPy program to create a two-dimensional array of a specified format.

In [16]:
tensor =torch.arange(0,10).reshape(2,5)
tensor

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

14. Write a PyTorch snippet to create a 2-tensor with shape (8,5) of random numbers. Select these random numbers (to create the tensor) from a normal distribution (200,7) (mean, variance).

In [17]:
mean = 100
variance =5
std_dev = variance**0.5

tensor =torch.normal(mean=mean,std=std_dev,size=(8,5))
tensor


tensor([[ 97.3245, 101.1390,  98.9060, 100.4144,  99.8282],
        [102.7466,  98.2947, 103.9949,  98.0626, 101.8822],
        [100.7115, 100.3590,  98.7394, 101.4808,  98.7231],
        [ 94.1792,  98.4813,  99.7529, 103.1524, 103.8257],
        [ 97.6044,  98.4210, 102.0457,  99.3041,  98.0248],
        [ 99.7888, 100.9189, 100.2761,  98.9501,  98.4718],
        [ 97.3357,  96.2343,  94.9213, 100.4695,  99.3858],
        [101.3405, 100.2128,  96.8253, 100.0292, 100.3733]])

15. Write a PyTorch snippet to generate a uniform, non-uniform random sample from a given vector with and without replacement (do all 4 combinations possible).

In [18]:
vector = torch.tensor([1,2,3,4,5,6])

#1.) uniform with replacement
tensor1 =vector[torch.randint(len(vector),(5,))]
print(tensor1)

#2.) uniform without replacement
tensor2 = vector[torch.randperm(len(vector))[:3]]
print(tensor2)

#3.) non-uniform with replacement
prob = torch.tensor([0.1,0.2,0.3,0.1,0.1,0.2])
tensor3 = torch.multinomial(prob,6,replacement=True)
tensor3 = vector[tensor3]
print(tensor3)

#4.) non-uniform without replacement
prob = torch.tensor([0.1,0.2,0.3,0.3,0.1,0.0])
tensor4 = torch.multinomial(prob,4,replacement=False)
tensor4 = vector[tensor4]
print(tensor4)

tensor([3, 1, 2, 1, 2])
tensor([5, 4, 3])
tensor([3, 2, 4, 3, 6, 4])
tensor([1, 4, 3, 2])


16. Write a Pyorch snippet to create an nxn(input to function) tensor with random values. Create an array from the said array swapping first and last rows.

In [19]:
def create(n):
  tensor = torch.randn(n,n)

  print(tensor)
  temp =tensor[0].clone()
  tensor[0] = tensor[-1]
  tensor[-1] =temp
  print("\nAfter excahnging\n")
  print(tensor)

n=4
create(n)

tensor([[ 0.9842, -0.5585,  0.6940, -1.2789],
        [ 1.5867,  1.3790,  0.4870, -1.6523],
        [-0.7585,  1.0766,  0.4936,  0.5006],
        [-2.0302,  0.8649, -0.6028,  0.1823]])

After excahnging

tensor([[-2.0302,  0.8649, -0.6028,  0.1823],
        [ 1.5867,  1.3790,  0.4870, -1.6523],
        [-0.7585,  1.0766,  0.4936,  0.5006],
        [ 0.9842, -0.5585,  0.6940, -1.2789]])


17. Write a PyTorch snippet to sort a given tensor (1D or 2D) in ascending order.

In [20]:
tensor1 = torch.tensor([5,54,1,46,9])
tensor2 =torch.tensor([10,1,9,2,8,5,3,4,6,7]).reshape(2,5)
print(torch.sort(tensor1).values)
print("\n\n")
print(torch.sort(tensor2).values)


tensor([ 1,  5,  9, 46, 54])



tensor([[ 1,  2,  8,  9, 10],
        [ 3,  4,  5,  6,  7]])


18. Write a PyTorch snippet to create a tensor of equal shape and data type for a given tensor (any dimensional)

In [21]:
def equal(n):
  tensor = torch.randn(n,n)
  print(tensor,tensor.dtype)

n =3
equal(n)


tensor([[ 1.4603,  0.8513, -0.2709],
        [-0.6372,  0.2758,  0.1029],
        [ 1.2578,  0.1381, -0.1189]]) torch.float32


19. Write a PyTorch snippet to create an 8x8 matrix and fill it with a checkerboard pattern.
Checkerboard pattern:
```py
[[0 1 0 1 0 1 0 1]
..........
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]]
```

In [22]:
tensor = torch.ones(8,8)

indices = [(i,j) for i in range(8) for j in range(8) if (i+j)%2==0]

rows,cols = zip(*indices)

tensor[rows,cols]=0

tensor

tensor([[0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0.],
        [0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0.],
        [0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0.],
        [0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0.]])

20. Write a Pytorch snippet to convert Centigrade to Fahrenheit and vice versa (controlled by a parameter). Ensure you operation is vectorized i.e **no explicit looping**

Sample Array: `[0, 12, 45.21, 34, 99.91]`

In [23]:
Celsius = torch.tensor([0, 12, 45.21, 34, 99.91])
Farenheit = torch.tensor([0, 12, 45.21, 34, 99.91])
#Celsius to Fareheit
Faren = Celsius*9/5 +32
Cels = (Farenheit-32)*5/9
print(Faren)
print(Cels)

tensor([ 32.0000,  53.6000, 113.3780,  93.2000, 211.8380])
tensor([-17.7778, -11.1111,   7.3389,   1.1111,  37.7278])


21. Write a PyTorch snippet to get the values of the elements that are bigger than a given *number* in a given tensor.

Original tensor:
```
[[ 0 10 20]
[20 30 40]]
```
Number: 10

Values bigger than 10 = `[20 20 30 40]`

In [24]:
tensor = torch.tensor([[9,10,20],[20,30,40]])
tensor[tensor>10]

tensor([20, 20, 30, 40])

22. Write a PyTorch snippet to create another shape from an array without changing its data. After carrying out the operation, change the data in one place and see if the other tensor changes

Reshape 3x2:
```
[[1 2]
[3 4]
[5 6]]
```
Reshape 2x3:
```
[[1 2 3]
[4 5 6]]
```

In [25]:
tensor = torch.arange(1,7).reshape(3,2)
print(tensor)
tensor.reshape(2,3)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


tensor([[1, 2, 3],
        [4, 5, 6]])

23. Write a PyTorch snipppet to change an tensor's data type.
```
[[ 2 4 6]
[ 6 8 10]]
```
Data type of the array x is: `int32`

New Type: `float64`
```
[[ 2. 4. 6.]
[ 6. 8. 10.]]
```

24. Write a PyTorch snippet to insert a new axis within a 2-tensor, based on a **parameter**.

Ex: If 2-tensor has shape (3, 4).

Then, new shape can be (1, 3, 4), (3, 1, 4), or (3, 4, 1) depending on....

In [26]:
tensor = torch.randn(3,4)
tensor1 =torch.unsqueeze(tensor,0)
tensor2 =torch.unsqueeze(tensor,1)
tensor3 =torch.unsqueeze(tensor,2)
print(tensor1.shape,tensor2.shape,tensor3.shape)


torch.Size([1, 3, 4]) torch.Size([3, 1, 4]) torch.Size([3, 4, 1])


25. Write a PyTorch snippet to stack tensors based on a parameter, **axis**.
First discover what this means with 2-tensors, then extend it to 3-tensors. Print your findings.

Sample Output:

Original tensors:

Tensor-1
```
[[0 1 2]
[3 4 5]
[6 7 8]]
```
Tensor-2
```
[[ 0 3 6]
[ 9 12 15]
[18 21 24]]
```
Stack tensors such that axis=1:
```
[[ 0 1 2 0 3 6]
[ 3 4 5 9 12 15]
[ 6 7 8 18 21 24]]
```

In [27]:
tensor1 = torch.tensor([[0, 1, 2],
                        [3, 4, 5],
                        [6, 7, 8]])

tensor2 = torch.tensor([[ 0 ,3, 6],
                        [ 9 ,12 ,15],
                        [18, 21, 24]])
tensor = torch.hstack((tensor1,tensor2))
tensor

tensor([[ 0,  1,  2,  0,  3,  6],
        [ 3,  4,  5,  9, 12, 15],
        [ 6,  7,  8, 18, 21, 24]])

26. Write a PyTorch snippet to extract the **m**th to **n**th elements of the **m**th to **n**th rows from the **m**th to nth elemnts of given 3-tensor, of shape `(p, q, r)` where m, n < p, q, r.

Take a 3-tensor of (say) size `(5,6,7)` and `(m, n)` = `(4, 5)` as a test case!

In [28]:
tensor =torch.randn(3,4,5)
print(tensor)
tensor[:,:,4:5]


tensor([[[ 0.9720,  0.9479,  0.6521,  0.4660,  1.1860],
         [-0.7718, -0.3991, -0.6023,  1.3383,  0.1568],
         [ 0.1202, -0.8339, -0.5142,  0.0847,  0.3879],
         [ 0.4600, -1.7999,  0.6513, -0.3862, -1.2778]],

        [[ 0.1922, -0.2616,  0.0687,  1.2591, -0.4633],
         [ 0.5040, -0.4333,  1.3600, -1.7822, -0.9354],
         [ 1.0861,  0.4948, -0.2196,  0.6617,  0.8910],
         [ 0.8244,  0.1097,  2.0245, -2.3931, -1.0113]],

        [[ 0.4610,  0.0374,  0.5106,  0.3945,  1.1833],
         [ 1.4653, -0.5597, -0.2940,  0.3636, -0.8084],
         [-0.6797,  0.1243,  0.3129,  0.1099, -2.4462],
         [-1.9726,  2.6365,  1.1013,  1.0841,  0.4997]]])


tensor([[[ 1.1860],
         [ 0.1568],
         [ 0.3879],
         [-1.2778]],

        [[-0.4633],
         [-0.9354],
         [ 0.8910],
         [-1.0113]],

        [[ 1.1833],
         [-0.8084],
         [-2.4462],
         [ 0.4997]]])

### **Test your Understanding**

1. Given a 3D tensor of shape `(a, b, c)`*italicised text*, permute its axes to obtain tensors of all other shape combinations (i.e 5).

In [29]:
ensor = torch.randn(2, 3, 4)

# Permute the 3 axes
permutations = [(0, 1, 2), (0, 2, 1), (1, 0, 2), (1, 2, 0), (2, 0, 1), (2, 1, 0)]

for permutation in permutations:
  print(tensor.permute(permutation))

tensor([[[ 0.9720,  0.9479,  0.6521,  0.4660,  1.1860],
         [-0.7718, -0.3991, -0.6023,  1.3383,  0.1568],
         [ 0.1202, -0.8339, -0.5142,  0.0847,  0.3879],
         [ 0.4600, -1.7999,  0.6513, -0.3862, -1.2778]],

        [[ 0.1922, -0.2616,  0.0687,  1.2591, -0.4633],
         [ 0.5040, -0.4333,  1.3600, -1.7822, -0.9354],
         [ 1.0861,  0.4948, -0.2196,  0.6617,  0.8910],
         [ 0.8244,  0.1097,  2.0245, -2.3931, -1.0113]],

        [[ 0.4610,  0.0374,  0.5106,  0.3945,  1.1833],
         [ 1.4653, -0.5597, -0.2940,  0.3636, -0.8084],
         [-0.6797,  0.1243,  0.3129,  0.1099, -2.4462],
         [-1.9726,  2.6365,  1.1013,  1.0841,  0.4997]]])
tensor([[[ 0.9720, -0.7718,  0.1202,  0.4600],
         [ 0.9479, -0.3991, -0.8339, -1.7999],
         [ 0.6521, -0.6023, -0.5142,  0.6513],
         [ 0.4660,  1.3383,  0.0847, -0.3862],
         [ 1.1860,  0.1568,  0.3879, -1.2778]],

        [[ 0.1922,  0.5040,  1.0861,  0.8244],
         [-0.2616, -0.4333,  0.4948,  

2. Given a 4D tensor of shape `(2, 3, 4, 5)`, transpose it to obtain a tensor of shape `(2, 4, 5, 3)`. Also explore what is_contiguous() means...

In [30]:

tensor = torch.randn(2, 3, 4, 5)

#transpose
transposed_tensor = tensor.transpose(1, 2)

print("Original tensor shape:", tensor.shape)
print("Transposed tensor shape:", transposed_tensor.shape)

print("\n\n")

# Check
print("Is the transposed tensor contiguous?", transposed_tensor.is_contiguous())

print("Is the original tensor contiguous?", tensor.is_contiguous())


Original tensor shape: torch.Size([2, 3, 4, 5])
Transposed tensor shape: torch.Size([2, 4, 3, 5])



Is the transposed tensor contiguous? False
Is the original tensor contiguous? True


3. Given two tensors, one of shape (n, 1) and another of shape (m, ), perform an element-wise addition **manually**. Then, test out what direct addition does and compare your results!

In [31]:
n=3
m=2
tensor1 = torch.randn(n,1)
tensor2 = torch.randn(m)
print(tensor1)
print(tensor2)
tensor = tensor1 + tensor2
print("\n\n")
print(tensor)

manual_tensor1 = tensor1.expand(n,m)
manual_tensor2 = tensor2.expand(n,m)
manual_tensor = manual_tensor1 + manual_tensor2
print("\n\n")
print(manual_tensor)
print("\n\n")

torch.equal(tensor,manual_tensor)

tensor([[ 0.8210],
        [-0.8038],
        [ 1.7009]])
tensor([-0.2325,  1.2342])



tensor([[ 0.5885,  2.0552],
        [-1.0362,  0.4305],
        [ 1.4684,  2.9352]])



tensor([[ 0.5885,  2.0552],
        [-1.0362,  0.4305],
        [ 1.4684,  2.9352]])





True

4. Given a 3D tensor of shape `(4, 4, 4)`, extract a sub-tensor of shape `(2, 2, 2)` starting from the element at index `(1, 1, 1)`**bold text**.

In [32]:
tensor = torch.randn(4, 4, 4)
sub_tensor = tensor[1:3, 1:3, 1:3]
print(sub_tensor)

tensor([[[-1.2798, -0.5552],
         [ 0.3249,  0.7982]],

        [[ 1.2052, -1.3532],
         [ 3.1477,  2.1114]]])


5. Given a 2-tensor of arbitrary shape, rotate it 90 degrees anticlockwise.



In [33]:
tensor = torch.randn(3,4)
print(tensor)
print("\n\n")
tensor = torch.rot90(tensor,3) #3 means rotating clockwise 3 times
print(tensor)

tensor([[ 0.0898, -2.3222,  1.1285, -0.7734],
        [-0.2061,  0.4672, -0.5706, -0.0225],
        [ 1.2154,  0.2715,  1.4083,  1.1021]])



tensor([[ 1.2154, -0.2061,  0.0898],
        [ 0.2715,  0.4672, -2.3222],
        [ 1.4083, -0.5706,  1.1285],
        [ 1.1021, -0.0225, -0.7734]])


### **EVEN I HAD TO THINK...**

1. Implement a custom operation that computes the **element-wise** **sine** of a tensor *and* its **gradient** using torch.autograd.Function.
- You need to implement both the forward() and backward() methods.
- For an example, look no further than the [PyTorch docs](https://pytorch.org/docs/stable/autograd.html#function)!
- Test it out on a matrix of arbitrary size!

2. One of the most important aspects of improving model performance ins normalization. Implement a custom NN normalization layer that performs either a **batch** or **layer** normalization (based on a **dim** parameter)and integrate it into a simple feedforward neural network.
- Note that you dont need to implement any backward() here, for simplicity.
- Consider your input tensor to the neural network as of shape (m, n) where m is num of examples, n is num of features.
- Which value of **dim** leads to batch and layer normalization?

In [34]:
import torch
import torch.nn as nn

class normalization(nn.Module):
  def __init__(self,dim):
    super(normalization,self).__init__()
    self.dim =dim

  def forward(self,x):
    if self.dim ==0:
      mean = x.mean(dim=0,keepdim=True)
      std = x.std(dim=0,keepdim=True)

    elif self.dim==1:
      mean = x.mean(dim=1,keepdim=True)
      std = x.std(dim=1,keepdim=1)

    else:
      raise ValueError("Not Correct")

    x_norm = (x-mean)/(std+1e-5)
    return x_norm

class SimpleNN(nn.Module):
  def __init__(self,input_size,hidden_size,output_size,norm_dim):
    super(SimpleNN,self).__init__()
    self.fc1 = nn.Linear(input_size,hidden_size)
    self.norm = normalization(norm_dim)
    self.relu = nn.ReLU()
    self.fc2 = nn.Linear(hidden_size,output_size)

  def forward(self,x):
    x = self.fc1(x)
    x = self.norm(x)
    x = self.relu(x)
    x = self.fc2(x)
    return x

if __name__ == "__main__":
  m,n =5,3
  tensor = torch.randn(5,3)

  #batch
  model_batch = SimpleNN(input_size=n,hidden_size=4,output_size=2,norm_dim=0)
  output_batch = model_batch(tensor)
  print(output_batch)

  print("\n\n")

  #layer
  model_layer = SimpleNN(input_size=n,hidden_size=4,output_size=2,norm_dim=0)
  output_layer = model_layer(tensor)
  print(output_layer)

tensor([[-0.0592,  1.2750],
        [-0.2473,  0.2331],
        [ 0.1036,  1.1715],
        [-0.1791,  0.3176],
        [-0.8226, -0.5026]], grad_fn=<AddmmBackward0>)



tensor([[ 0.3340, -0.1965],
        [-0.0983, -0.6730],
        [ 0.2544, -0.0654],
        [-0.3093, -0.4969],
        [ 1.5090, -1.4989]], grad_fn=<AddmmBackward0>)


3. Given a 4D tensor of shape (2, 3, 4, 5), create a mask that sets all elements in positions where the sum of indices is even to zero.

In [35]:
tensor = torch.randn(2,3,4,5)
i = torch.arange(2).view(-1, 1, 1, 1)
j = torch.arange(3).view(1, -1, 1, 1)
k = torch.arange(4).view(1, 1, -1, 1)
l = torch.arange(5).view(1, 1, 1, -1)

index_sum = i+j+k+l

mask = (index_sum%2==0)
tensor[mask] =0

print(tensor)


tensor([[[[ 0.0000, -1.6475,  0.0000, -0.5387,  0.0000],
          [ 0.0697,  0.0000,  0.5631,  0.0000,  1.6045],
          [ 0.0000, -0.2592,  0.0000,  0.0337,  0.0000],
          [ 0.3270,  0.0000, -0.4858,  0.0000, -0.6199]],

         [[ 0.8279,  0.0000, -1.1658,  0.0000,  0.0081],
          [ 0.0000,  1.3926,  0.0000, -0.3098,  0.0000],
          [ 0.2183,  0.0000, -1.4111,  0.0000,  0.5677],
          [ 0.0000,  0.0384,  0.0000, -1.5945,  0.0000]],

         [[ 0.0000, -0.1669,  0.0000,  0.8992,  0.0000],
          [-0.0738,  0.0000, -0.2106,  0.0000,  0.2936],
          [ 0.0000,  0.2517,  0.0000,  0.2960,  0.0000],
          [-0.9834,  0.0000, -0.0791,  0.0000,  0.2900]]],


        [[[ 0.3692,  0.0000, -0.0204,  0.0000,  0.4495],
          [ 0.0000,  0.0578,  0.0000, -0.5097,  0.0000],
          [ 0.0727,  0.0000,  0.3776,  0.0000,  0.7413],
          [ 0.0000, -2.4670,  0.0000,  0.6007,  0.0000]],

         [[ 0.0000,  0.7961,  0.0000, -0.3215,  0.0000],
          [-0.5923,  

3. Given two tensors, one of shape `(3, 1, 4)` and another of shape `(1, 5, 1)`, compute their element-wise multiplication using broadcasting and then sum over specific axes to obtain a tensor of shape `(3, 5)`.

In [36]:

tensor1 =torch.randn(3,1,4)
tensor2 = torch.randn(1,5,1)

resultant = tensor1*tensor2

summed = resultant.sum(dim=2)
print(tensor1)
print("\n")
print(tensor2)
print("\n")
print(resultant)
print("\n")
print(summed)
print("\n")

tensor([[[-1.6828, -0.6164,  0.6536,  1.4282]],

        [[ 0.1375, -0.6794, -0.9313,  0.5996]],

        [[-0.0821,  0.0272, -0.8441,  0.9502]]])


tensor([[[ 1.0385],
         [ 0.6847],
         [-1.1113],
         [ 0.6025],
         [-0.4667]]])


tensor([[[-1.7475, -0.6402,  0.6787,  1.4831],
         [-1.1523, -0.4221,  0.4475,  0.9779],
         [ 1.8700,  0.6850, -0.7263, -1.5871],
         [-1.0139, -0.3714,  0.3938,  0.8605],
         [ 0.7853,  0.2877, -0.3050, -0.6665]],

        [[ 0.1428, -0.7056, -0.9671,  0.6226],
         [ 0.0942, -0.4652, -0.6377,  0.4105],
         [-0.1528,  0.7550,  1.0349, -0.6663],
         [ 0.0828, -0.4094, -0.5611,  0.3613],
         [-0.0642,  0.3171,  0.4346, -0.2798]],

        [[-0.0852,  0.0283, -0.8765,  0.9868],
         [-0.0562,  0.0186, -0.5780,  0.6506],
         [ 0.0912, -0.0303,  0.9380, -1.0559],
         [-0.0495,  0.0164, -0.5086,  0.5725],
         [ 0.0383, -0.0127,  0.3939, -0.4434]]])


tensor([[-0.2259, -0.1489,  0.2417