<a href="https://colab.research.google.com/github/nagamukesh/NLP-SMP/blob/Shubhang_S_Galagali/PyTorch_Assignment_Shubhang_Galagali.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  **PyTorch Practice Assignment**
**Name**: Shubhang S Galagali

**Roll Number**: 231MT049

## **Instructions:**

- Copy this Notebook to your own Drive! You cannot directly modify it.
- Please show the output of the cells, in case of some operation. You can specify your own **non-trivial** test-case. Also, try and make your snippets into functions to organize your logic.
- You can use any number of cells for a question, you are not restricted to just 1 cell!
- **No using ChatGPT for this assignment**: we highly recommend using the [Pytorch Docs](https://pytorch.org/docs/stable/index.html) as your start reference, as well as the vast internet however. You can also contact any of your mentors for some hints/help!
- You can work on this assignment in Google Colab or on Your Local Machine!

### **Build Up Your Understanding**

1. Write a PyTorch snippet to test whether none of the elements of a given tensor are zero.

In [1]:
import torch as t

In [10]:
random_size = t.randint(0, 10, (1,)).item() # get the dim of the tensor
print(f"{random_size}")

#given = t.tensor([0,11,23])

given = t.rand(random_size, random_size)
print(f"Given Tensor is {given}")

answer = t.all(given != 0)

print(f"Are none of the elements of the given tensor 0? - {answer}")

2
Given Tensor is tensor([[0.5550, 0.4629],
        [0.7190, 0.7182]])
Are none of the elements of the given tensor 0? - True


2. Write a PyTorch snippet to test element-wise for NaN of a given tensor.

In [13]:
random_size = t.randint(0, 10, (1,)).item() # get the dim of the tensor
print(f"{random_size}")

given = t.rand(random_size, random_size)
print(f"Given Tensor is {given}")

answer = t.isnan(given)

print(f"{answer}")

3
Given Tensor is tensor([[0.1103, 0.4364, 0.6931],
        [0.0823, 0.0790, 0.7981],
        [0.1016, 0.5166, 0.8498]])
tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])


3. Write a PyTorch snippet to test whether two tensors are element-wise equal within a tolerance.

In [15]:
random_size = t.randint(0, 10, (1,)).item() # get the dim of the tensor
print(f"{random_size}")
print()

given1 = t.rand(random_size, random_size)
print(f"Given Tensor 1 is {given1}")
print()

given2 = t.rand(random_size, random_size)
print(f"Given Tensor 2 is {given2}")
print()

answer = t.eq(given1,given2)

print("Checking element-wise equality:")
print()

print(f"{answer}")

5

Given Tensor 1 is tensor([[0.2432, 0.5685, 0.9122, 0.5243, 0.4772],
        [0.5069, 0.0830, 0.7516, 0.6118, 0.2734],
        [0.8212, 0.0163, 0.9352, 0.2175, 0.1748],
        [0.7343, 0.9970, 0.6570, 0.6742, 0.7968],
        [0.3226, 0.1220, 0.9948, 0.1091, 0.6441]])

Given Tensor 2 is tensor([[0.5169, 0.2139, 0.2789, 0.8817, 0.1568],
        [0.8065, 0.1589, 0.4257, 0.9801, 0.8038],
        [0.3072, 0.2692, 0.2805, 0.4669, 0.8693],
        [0.2829, 0.7837, 0.5395, 0.6902, 0.8596],
        [0.6853, 0.2469, 0.9933, 0.0680, 0.5836]])

Checking element-wise equality:

tensor([[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]])


4. Write a PyTorch snippet to create a tensor of 10 zeros, 10 ones, and 10 fives stacked on top of each other (try & accomplish everything using nested function calls).

In [22]:
op = t.stack([t.zeros(10), t.ones(10), t.full((10,), 5)])

print(op)

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])


**5**. Write a PyTorch snippet to generate a random number between 0 and 1.

In [23]:
op = t.rand(1).item()
print(op)

0.7265648245811462


6. Write a PyTorch snippet to generate a tensor of 15 random numbers from a standard normal distribution.

In [24]:
op = t.randn(15)
print(op)

tensor([-1.6460,  0.7189,  1.2063, -1.4908, -0.3808, -0.6917, -0.4906,  0.3103,
         0.1672, -1.6141,  2.6294, -0.0709, -0.0326,  0.6297,  2.6569])


7. Write a Pytorch snippet to create a tensor of length 10 with values evenly distributed between 5 and 50.

In [25]:
len10 = t.linspace(5, 50, steps=10)
print(len10)

tensor([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])


8. Write a Pyorch program to create a tensor with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15.

In [31]:
initial = t.arange(0,21)
##print(f"{initial=}")

for element in initial:
  if element in range(9,16):
    initial[element] = element*(-1)

print(f"Final={initial}")

Final=tensor([  0,   1,   2,   3,   4,   5,   6,   7,   8,  -9, -10, -11, -12, -13,
        -14, -15,  16,  17,  18,  19,  20])


9. Write a PyTorch snippet to create a 3x4 2-tensor filled with values from 10 to 21. Same but 12 to 24.

In [38]:
t1= t.arange(10,22).reshape(3,4)
t2= t.arange(12,24).reshape(3,4) # 12 to 23, not 24

print(f'''{t1=}

{t2=}''')

t1=tensor([[10, 11, 12, 13],
        [14, 15, 16, 17],
        [18, 19, 20, 21]])
      
t2=tensor([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])


10. Write a PyTorch snippet to create a 10x10 2-tensor, in which the elements on the borders will be equal to 1, and inside 0.

In [44]:
op = t.zeros(10,10)

print(f"Initially - {op}")

op[0,:] = 1 # first row taken care of
op[-1,:] = 1 # last row taken care of

#now for the border columns

for i in range(10):
  op[i,0] = 1
  op[i,-1] = 1


print(f"Finally - {op}")


Initially - tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])
Finally - tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 1., 1., 1., 1.

11. Write a PyTorch snippet to create a 5x5 zero 2-tensor with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [46]:
op = t.zeros(5,5)

print(f"Initially - {op}")

count = 1
for i in range(5):
  op[i,i] = count
  count+=1

print(f"Finally - {op}")


Initially - tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
Finally - tensor([[1., 0., 0., 0., 0.],
        [0., 2., 0., 0., 0.],
        [0., 0., 3., 0., 0.],
        [0., 0., 0., 4., 0.],
        [0., 0., 0., 0., 5.]])


12. Write a PyTorch snippet to save a given tensor as a binary to a given path.

In [52]:
#given is a tensor generated in cell no.2
print(f"{given=}")
print()

save_path = 'the path I want'

t.save(given, save_path)

print(f"Tensor saved to '{save_path}'")

given=tensor([[0.1103, 0.4364, 0.6931],
        [0.0823, 0.0790, 0.7981],
        [0.1016, 0.5166, 0.8498]])

Tensor saved to 'the path I want'


13. Write a NumPy program to create a two-dimensional array of a specified format.

In [54]:
import numpy as np

np.random.rand(4, 5)

array([[0.14001624, 0.92584897, 0.63277764, 0.32097889, 0.48527854],
       [0.17188425, 0.16771599, 0.02435464, 0.94770238, 0.07067956],
       [0.94354087, 0.70484373, 0.74989333, 0.14789005, 0.58964732],
       [0.24954735, 0.54458983, 0.06335399, 0.74926888, 0.7396751 ]])

14. Write a PyTorch snippet to create a 2-tensor with shape (8,5) of random numbers. Select these random numbers (to create the tensor) from a normal distribution (200,7) (mean, variance).

In [56]:
example =t.normal(200,7, (8,5))

print(example)

tensor([[195.8454, 187.9802, 203.3245, 203.9157, 181.6701],
        [206.0673, 201.1381, 211.5117, 200.6692, 199.5974],
        [203.7042, 194.9453, 191.3013, 206.3701, 204.2129],
        [205.7095, 190.4256, 195.4592, 191.5993, 215.2676],
        [196.1461, 207.0939, 183.2612, 194.0096, 196.6248],
        [207.7585, 196.0197, 220.8057, 199.8261, 193.7132],
        [196.8313, 187.4853, 202.7191, 211.0807, 199.2720],
        [195.0094, 205.0468, 214.0340, 194.7855, 198.5608]])


15. Write a PyTorch snippet to generate a uniform, non-uniform random sample from a given vector with and without replacement (do all 4 combinations possible).

In [67]:
given_vec = t.rand(7,)
print(f"Given vector sample = {given_vec}")
print()
## Uniform without replacement:
t1 = given_vec[t.randperm(len(given_vec))[:3]]
print(f'''Uniform without replacement:

{t1}
''')

Given vector sample = tensor([0.6211, 0.4438, 0.3121, 0.0736, 0.0275, 0.8731, 0.8383])

Uniform without replacement:

tensor([0.0736, 0.8383, 0.4438])



In [68]:
## Uniform with replacement:
t2 = given_vec[t.randint(len(given_vec), size=(3,))]
print(f'''Uniform with replacement:

{t2}
''')

Uniform with replacement:

tensor([0.8383, 0.8731, 0.6211])



In [69]:
## Non-uniform with replacement:
pbb = t.tensor([0.13, 0.24, 0.35, 0.27, 0.92])

t3 = given_vec[t.multinomial(pbb, 3, replacement=True)]
print(f'''Non-uniform with replacement:

{t3}
''')

Non-uniform with replacement:

tensor([0.0275, 0.3121, 0.3121])



In [70]:
## Non-uniform without replacement:
t4 = given_vec[t.multinomial(pbb, 3, replacement=True)]
print(f'''Non-uniform without replacement:

{t4}
''')

Non-uniform without replacement:

tensor([0.3121, 0.0275, 0.0736])



16. Write a Pyorch snippet to create an nxn(input to function) tensor with random values. Create an array from the said array swapping first and last rows.

In [79]:
def hookah(n):
    my_thing = t.rand(n, n)

    print("Before Swapping:")
    print(my_thing)

    ##dancestep1 = my_thing[0]
   ## dancestep2 = my_thing[-1]
    ##my_thing[-1] = dancestep1

   ## my_thing[0] = dancestep2
    dance = my_thing[0].clone()
    my_thing[0] = my_thing[-1]
    my_thing[-1] = dance

    print()
    print("After swapping:")
    print(my_thing)
    print()

    return "DanceOver"

#trying to see the effects of hookah on my dance --> n = 6
print(hookah(6))


Before Swapping:
tensor([[0.8306, 0.2534, 0.6951, 0.0735, 0.0962, 0.9618],
        [0.3766, 0.3011, 0.9669, 0.3798, 0.8090, 0.3434],
        [0.1616, 0.2446, 0.7965, 0.7259, 0.4787, 0.9500],
        [0.3502, 0.7137, 0.9711, 0.4214, 0.4309, 0.4853],
        [0.7906, 0.4102, 0.5273, 0.2128, 0.0833, 0.1664],
        [0.7523, 0.0630, 0.0397, 0.4618, 0.1127, 0.4768]])

After swapping:
tensor([[0.7523, 0.0630, 0.0397, 0.4618, 0.1127, 0.4768],
        [0.3766, 0.3011, 0.9669, 0.3798, 0.8090, 0.3434],
        [0.1616, 0.2446, 0.7965, 0.7259, 0.4787, 0.9500],
        [0.3502, 0.7137, 0.9711, 0.4214, 0.4309, 0.4853],
        [0.7906, 0.4102, 0.5273, 0.2128, 0.0833, 0.1664],
        [0.8306, 0.2534, 0.6951, 0.0735, 0.0962, 0.9618]])

DanceOver


17. Write a PyTorch snippet to sort a given tensor (1D or 2D) in ascending order.

In [81]:
t1 = t.rand(5)

t2 = t.rand(3,7)

print(f'''Before Sorting -

{t1=}

{t2=}''')

t1, indicest1 = t.sort(t1)

t2, indicest2 = t.sort(t2)

print(f'''After Sorting -

{t1=}

{t2=}''')

Before Sorting -

t1=tensor([0.3907, 0.7669, 0.1120, 0.4887, 0.7014])
      
t2=tensor([[0.7682, 0.7086, 0.2112, 0.9773, 0.2655, 0.2361, 0.0585],
        [0.6390, 0.8849, 0.0044, 0.9665, 0.5605, 0.6486, 0.5404],
        [0.0714, 0.8374, 0.7727, 0.1584, 0.0420, 0.7645, 0.7253]])
After Sorting -

t1=tensor([0.1120, 0.3907, 0.4887, 0.7014, 0.7669])
      
t2=tensor([[0.0585, 0.2112, 0.2361, 0.2655, 0.7086, 0.7682, 0.9773],
        [0.0044, 0.5404, 0.5605, 0.6390, 0.6486, 0.8849, 0.9665],
        [0.0420, 0.0714, 0.1584, 0.7253, 0.7645, 0.7727, 0.8374]])


18. Write a PyTorch snippet to create a tensor of equal shape and data type for a given tensor (any dimensional)

In [84]:
t1=t.randn(3,4, dtype=t.float32)
t2=t.randn(*(t1.shape), dtype=t1.dtype)
print(f"{t1=}\n\n{t2=}\n\n{t2.shape=}\n\n{t2.dtype=}")


t1=tensor([[ 0.0696, -0.7696, -0.8457,  1.1300],
        [-1.5772, -0.9574,  1.6772, -1.1260],
        [-0.9368, -0.4827,  0.3322,  0.6868]])

t2=tensor([[ 0.1724,  0.8018, -0.1402, -0.4211],
        [ 1.5033,  0.4356,  0.5575,  0.1728],
        [-0.7429, -1.0531, -0.0055,  1.5766]])

t2.shape=torch.Size([3, 4])

t2.dtype=torch.float32


19. Write a PyTorch snippet to create an 8x8 matrix and fill it with a checkerboard pattern.
Checkerboard pattern:
```py
[[0 1 0 1 0 1 0 1]
..........
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]]
```

In [89]:
mat = t.zeros(8,8)

for rows in range(8):
  if rows % 2:
    for i in range(0,8,2):
      mat[rows][i]=1
  else:
    for i in range(1,8,2):
      mat[rows][i]=1


print(mat)

tensor([[0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0.],
        [0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0.],
        [0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0.],
        [0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0.]])


20. Write a Pytorch snippet to convert Centigrade to Fahrenheit and vice versa (controlled by a parameter). Ensure you operation is vectorized i.e **no explicit looping**

Sample Array: `[0, 12, 45.21, 34, 99.91]`

In [100]:
def c_to_f(c):
    return (c * 9/5) + 32

def f_to_c(f):

    return (f - 32) * 5/9

sample = t.tensor([0, 12, 45.21, 34, 99.91])

def ip():
  print("Do you want to convert from Centigrade to Fahrenheit [C] or vice versa [F]?")
  ##wish = input()
  wish = "C"

  if wish == "C" or wish == "c":
    answer = c_to_f(sample)
  else:
    answer = f_to_c(sample)
  return answer

print(ip())

Do you want to convert from Centigrade to Fahrenheit [C] or vice versa [F]?
tensor([ 32.0000,  53.6000, 113.3780,  93.2000, 211.8380])


21. Write a PyTorch snippet to get the values of the elements that are bigger than a given *number* in a given tensor.

Original tensor:
```
[[ 0 10 20]
[20 30 40]]
```
Number: 10

Values bigger than 10 = `[20 20 30 40]`

In [104]:
given = t.tensor([[0,10, 20], [20, 30, 40]])

number = 10

answer = given[given > number]

print(answer)


tensor([20, 20, 30, 40])


22. Write a PyTorch snippet to create another shape from an array without changing its data. After carrying out the operation, change the data in one place and see if the other tensor changes

Reshape 3x2:
```
[[1 2]
[3 4]
[5 6]]
```
Reshape 2x3:
```
[[1 2 3]
[4 5 6]]
```

In [105]:
given = t.tensor([[1,2], [3,4], [5,6]])

print(f"Given Tensor: {given}")

given = given.reshape(2,3)

print(f"Reshaped Tensor: {given}")


Given Tensor: tensor([[1, 2],
        [3, 4],
        [5, 6]])
Reshaped Tensor: tensor([[1, 2, 3],
        [4, 5, 6]])


23. Write a PyTorch snipppet to change an tensor's data type.
```
[[ 2 4 6]
[ 6 8 10]]
```
Data type of the array x is: `int32`

New Type: `float64`
```
[[ 2. 4. 6.]
[ 6. 8. 10.]]
```

In [106]:
given = t.tensor([[2,4,6], [6,8,10]])

print(f"Given Tensor: {given}")

given = given.type(t.float64)

print(f"New Tensor: {given}")



Given Tensor: tensor([[ 2,  4,  6],
        [ 6,  8, 10]])
New Tensor: tensor([[ 2.,  4.,  6.],
        [ 6.,  8., 10.]], dtype=torch.float64)


24. Write a PyTorch snippet to insert a new axis within a 2-tensor, based on a **parameter**.

Ex: If 2-tensor has shape (3, 4).

Then, new shape can be (1, 3, 4), (3, 1, 4), or (3, 4, 1) depending on....

In [107]:
tensor = torch.randn(3,4)
t1 =torch.unsqueeze(tensor,0)
t2 =torch.unsqueeze(tensor,1)
t3 =torch.unsqueeze(tensor,2)
print(f"{t1=}\t\t{t1.shape}\n\n{t2=}\t\t{t2.shape}\n\n{t3=}\t\t{t3.shape}")

t1=tensor([[[-0.5532, -0.0861,  0.0593, -1.1861],
         [ 0.8103,  0.2917, -0.0779, -0.8307],
         [-1.2993,  1.1429, -0.0151, -2.1338]]])		torch.Size([1, 3, 4])

t2=tensor([[[-0.5532, -0.0861,  0.0593, -1.1861]],

        [[ 0.8103,  0.2917, -0.0779, -0.8307]],

        [[-1.2993,  1.1429, -0.0151, -2.1338]]])		torch.Size([3, 1, 4])

t3=tensor([[[-0.5532],
         [-0.0861],
         [ 0.0593],
         [-1.1861]],

        [[ 0.8103],
         [ 0.2917],
         [-0.0779],
         [-0.8307]],

        [[-1.2993],
         [ 1.1429],
         [-0.0151],
         [-2.1338]]])		torch.Size([3, 4, 1])


25. Write a PyTorch snippet to stack tensors based on a parameter, **axis**.
First discover what this means with 2-tensors, then extend it to 3-tensors. Print your findings.

Sample Output:

Original tensors:

Tensor-1
```
[[0 1 2]
[3 4 5]
[6 7 8]]
```
Tensor-2
```
[[ 0 3 6]
[ 9 12 15]
[18 21 24]]
```
Stack tensors such that axis=1:
```
[[ 0 1 2 0 3 6]
[ 3 4 5 9 12 15]
[ 6 7 8 18 21 24]]
```

In [109]:
# 2-tensors

tensor1 = t.tensor([[0, 1, 2],
                        [3, 4, 5],
                        [6, 7, 8]])

tensor2 = t.tensor([[ 0 ,3, 6],
                        [ 9 ,12 ,15],
                        [18, 21, 24]])
tensor = t.cat((tensor1,tensor2), dim=1)

print(tensor)

tensor([[ 0,  1,  2,  0,  3,  6],
        [ 3,  4,  5,  9, 12, 15],
        [ 6,  7,  8, 18, 21, 24]])


In [110]:
# 3-tensors

tensor1=t.rand(2,3,4)
tensor2=t.rand(2,3,4)
tensor3=t.rand(2,3,4)

tensor = t.cat((tensor1,tensor2,tensor3), dim=2)

print(tensor)

tensor([[[0.8150, 0.5642, 0.7459, 0.4109, 0.0882, 0.5353, 0.3751, 0.9796,
          0.4748, 0.1402, 0.2943, 0.2008],
         [0.6681, 0.3981, 0.3394, 0.0305, 0.3987, 0.3201, 0.6120, 0.6899,
          0.0658, 0.1878, 0.6458, 0.1894],
         [0.0906, 0.0330, 0.4907, 0.4609, 0.6443, 0.4632, 0.8289, 0.8451,
          0.2432, 0.2300, 0.7615, 0.0977]],

        [[0.7432, 0.5078, 0.6414, 0.7130, 0.4753, 0.4689, 0.3402, 0.3958,
          0.7894, 0.6447, 0.5745, 0.4180],
         [0.6286, 0.2457, 0.6013, 0.3690, 0.4764, 0.8594, 0.1914, 0.9881,
          0.3903, 0.1782, 0.2852, 0.1293],
         [0.8329, 0.2139, 0.9710, 0.1159, 0.9210, 0.6684, 0.8812, 0.3626,
          0.9993, 0.8794, 0.7049, 0.8913]]])


26. Write a PyTorch snippet to extract the **m**th to **n**th elements of the **m**th to **n**th rows from the **m**th to nth elemnts of given 3-tensor, of shape `(p, q, r)` where m, n < p, q, r.

Take a 3-tensor of (say) size `(5,6,7)` and `(m, n)` = `(4, 5)` as a test case!

In [111]:
tensor_3d = t.rand(5,6,7)

print("Original 3D Tensor:")
print(tensor_3d)
# Define m and n
m, n = 1, 3

extract = tensor_3d[m:n+1, m:n+1, m:n+1]

# Print original tensor and extracted subset tensor
print("Original 3D Tensor:")
print(tensor_3d)

print("Extarcted Tensor")
print(extract)


Original 3D Tensor:
tensor([[[9.1510e-01, 4.2335e-01, 6.9992e-01, 6.0898e-01, 9.2227e-01,
          2.9295e-01, 5.5813e-01],
         [1.4003e-01, 7.5087e-01, 9.8201e-01, 5.7190e-01, 3.8630e-01,
          8.2824e-01, 1.5793e-01],
         [8.1800e-01, 8.7009e-01, 8.0536e-01, 4.7612e-01, 1.6580e-01,
          7.2321e-01, 8.9627e-01],
         [5.2322e-01, 6.7408e-01, 8.3688e-01, 8.2338e-02, 3.8327e-01,
          6.8665e-01, 5.4722e-01],
         [8.8653e-01, 3.6844e-01, 3.5965e-01, 1.4338e-01, 7.6595e-01,
          9.1877e-01, 6.8661e-02],
         [5.0458e-01, 3.5117e-01, 1.9875e-01, 2.7881e-01, 8.2565e-01,
          6.1958e-01, 2.9625e-01]],

        [[2.6361e-01, 3.2173e-01, 1.8746e-01, 5.0927e-01, 5.1820e-01,
          4.3448e-02, 9.5477e-01],
         [7.1592e-01, 2.7008e-01, 9.4318e-01, 5.3696e-01, 8.6168e-01,
          1.4534e-01, 9.3458e-01],
         [2.2238e-01, 1.4351e-01, 2.2715e-01, 5.4464e-01, 7.6746e-01,
          4.4548e-01, 6.3141e-01],
         [9.3259e-02, 6.4031e-01,

### **Test your Understanding**

1. Given a 3D tensor of shape `(a, b, c)`, permute its axes to obtain tensors of all other shape combinations (i.e 5).

In [114]:
select = t.randn(2, 3, 4)
print(select)
print()
possibilities = [(0, 1, 2), (0, 2, 1),(1, 0, 2), (1, 2, 0),
 (2, 0, 1), (2,1,0)]

for permutation in possibilities:
  print(select.permute(permutation))

tensor([[[ 1.7222,  0.5198, -1.5316, -0.7469],
         [-0.1292,  1.5123, -0.9654, -0.6833],
         [-1.0220,  0.9289, -0.7984,  0.7688]],

        [[-1.7656, -0.2388, -0.4222,  0.4860],
         [-0.6053, -0.7229,  0.3086,  0.1484],
         [-0.6672, -0.2459,  1.6184, -2.2320]]])

tensor([[[ 1.7222,  0.5198, -1.5316, -0.7469],
         [-0.1292,  1.5123, -0.9654, -0.6833],
         [-1.0220,  0.9289, -0.7984,  0.7688]],

        [[-1.7656, -0.2388, -0.4222,  0.4860],
         [-0.6053, -0.7229,  0.3086,  0.1484],
         [-0.6672, -0.2459,  1.6184, -2.2320]]])
tensor([[[ 1.7222, -0.1292, -1.0220],
         [ 0.5198,  1.5123,  0.9289],
         [-1.5316, -0.9654, -0.7984],
         [-0.7469, -0.6833,  0.7688]],

        [[-1.7656, -0.6053, -0.6672],
         [-0.2388, -0.7229, -0.2459],
         [-0.4222,  0.3086,  1.6184],
         [ 0.4860,  0.1484, -2.2320]]])
tensor([[[ 1.7222,  0.5198, -1.5316, -0.7469],
         [-1.7656, -0.2388, -0.4222,  0.4860]],

        [[-0.1292,  1.5

2. Given a 4D tensor of shape `(2, 3, 4, 5)`, transpose it to obtain a tensor of shape `(2, 4, 5, 3)`. Also explore what is_contiguous() means...

In [129]:
given = t.randn(2, 3, 4, 5)

print("Given Tensor Shape:", given.shape)

transposed_tensor = given.permute(0, 2, 3, 1)

print("\nTransposed Tensor Shape:", transposed_tensor.shape)
print(f"\n\n{transposed_tensor}")

'''A tensor is contiguous
if its elements are stored in a single, contiguous block of memory,
 such that the order of elements matches the memory layout order of
  the tensor shape.'''

print(f"{transposed_tensor.is_contiguous()}")

Given Tensor Shape: torch.Size([2, 3, 4, 5])

Transposed Tensor Shape: torch.Size([2, 4, 5, 3])


tensor([[[[-1.3515,  0.2408,  0.1456],
          [-1.1245,  1.8293, -0.1455],
          [-1.6605,  1.2858, -0.2586],
          [ 1.3433,  0.9583,  1.1740],
          [ 0.0832, -0.1515, -1.1243]],

         [[-0.7717,  0.8412,  0.8652],
          [-0.9978, -0.7679,  0.4663],
          [ 1.7200,  0.1615,  0.1132],
          [-0.3666, -0.4152,  0.5914],
          [ 0.0861, -0.2696, -0.9748]],

         [[ 0.2062, -0.3653, -0.4244],
          [-0.3280,  1.6820, -0.5588],
          [-0.2000, -0.5059, -0.7855],
          [-0.2967, -1.4307,  1.2314],
          [ 1.3239,  1.4319, -0.1987]],

         [[ 0.5605,  1.1380,  0.5718],
          [-0.6335, -1.0056,  0.2904],
          [ 0.3839,  1.4845,  0.0414],
          [-1.3317, -1.9445, -0.9331],
          [ 0.0867, -0.1277,  0.1472]]],


        [[[-0.7145,  2.1848, -1.5485],
          [-0.9720, -0.8689,  0.6800],
          [-0.3206, -0.9084, -1.32

*3*. Given two tensors, one of shape (n, 1) and another of shape (m, ), perform an element-wise addition.

In [124]:
t1 = t.tensor([[452], [54552], [4245]])  # shape (n, 1)
t2 = t.tensor([64, 452, 445, 94])    # shape (m, )

t2 = t2[:t1.shape[0]]

# Perform element-wise addition
answer = t1 + t2

# Print the result
print("After element-wise addition:")
print(answer)


After element-wise addition:
tensor([[  516,   904,   897],
        [54616, 55004, 54997],
        [ 4309,  4697,  4690]])


4. Given a 3D tensor of shape `(4, 4, 4)`, extract a sub-tensor of shape `(2, 2, 2)` starting from the element at index `(1, 1, 1)`

In [126]:
given = t.randn(4, 4, 4)

print(f"Given Tensor Shape: {tensor_3d.shape}")

sub_tensor = given[1:3, 1:3, 1:3]

print(f"\n{sub_tensor=}")


Given Tensor Shape: torch.Size([5, 6, 7])

sub_tensor=tensor([[[-0.0946,  1.0220],
         [ 0.8292,  0.8875]],

        [[-0.1087, -0.5549],
         [-0.4417,  0.0131]]])


5. Given a 2-tensor of arbitrary shape, rotate it 90 degrees anticlockwise.



In [122]:
t1=t.randn(size=(5,3))

answer = t.rot90(t1)

print(t1)
print()
print(answer)

tensor([[ 0.0692,  0.9189,  0.5229],
        [-0.3938, -0.2937,  0.9429],
        [-0.0963, -0.3670, -0.1541],
        [-1.1687,  0.6419,  0.8983],
        [-1.2873,  0.3952, -0.3019]])

tensor([[ 0.5229,  0.9429, -0.1541,  0.8983, -0.3019],
        [ 0.9189, -0.2937, -0.3670,  0.6419,  0.3952],
        [ 0.0692, -0.3938, -0.0963, -1.1687, -1.2873]])


### **EVEN I HAD TO THINK...**

1. Implement a custom operation that computes the **element-wise** **sine** of a tensor *and* its **gradient** using torch.autograd.Function.
- You need to implement both the forward() and backward() methods.
- For an example, look no further than the [PyTorch docs](https://pytorch.org/docs/stable/autograd.html#function)!
- Test it out on a matrix of arbitrary size!

In [ ]:
###pass  --> AuthorError xD

2. One of the most important aspects of improving model performance ins normalization. Implement a custom NN normalization layer that performs either a **batch** or **layer** normalization (based on a **dim** parameter)and integrate it into a simple feedforward neural network.
- Note that you dont need to implement any backward() here, for simplicity.
- Consider your input tensor to the neural network as of shape (m, n) where m is num of examples, n is num of features.
- Which value of **dim** leads to batch and layer normalization?

In [135]:
##will submit soon

3. Given a 4D tensor of shape (2, 3, 4, 5), create a mask that sets all elements in positions where the sum of indices is even to zero.

In [136]:
##will submit soon

4. Given two tensors, one of shape `(3, 1, 4)` and another of shape `(1, 5, 1)`, compute their element-wise multiplication using broadcasting and then sum over specific axes to obtain a tensor of shape `(3, 5)`.

In [128]:
t1 = t.randn(3, 1, 4)
t2 = t.randn(1, 5, 1)

# Perform element-wise multiplication using broadcasting
res = t1 * t2

# Sum over axes 1 and 2 to obtain shape (3, 5)

res_summed = res.sum(dim=1).squeeze()

# Print shapes and result
print("Shape of t1:", t1.shape)
print()
print("Shape of t2:", t2.shape)
print()
print("Shape of element-wise product:", res.shape)
print()
print("Shape after summation over axes 1 and 2:", res_summed.shape)
print()
print("Result:")
print()
print(res_summed)


Shape of t1: torch.Size([3, 1, 4])

Shape of t2: torch.Size([1, 5, 1])

Shape of element-wise product: torch.Size([3, 5, 4])

Shape after summation over axes 1 and 2: torch.Size([3, 4])

Result:

tensor([[ 1.9582,  3.2623,  1.2423,  2.5556],
        [-1.3900, -0.2116,  0.5591, -0.1344],
        [-3.9499,  1.5888, -3.8395,  0.6340]])
